### ISSUE TITLE
"Task timed out" error on some Laravel endpoints

### ISSUE THREAD

**Issue by nickrupert7** [brefphp/bref#1001]
**Description:**

We have recently migrated one of our Laravel 8 projects to use serverless deployment with Bref on AWS Lambda.

SOME of our endpoints are consistently failing with the error `{"message":"Internal Server Error"}` (`Task timed out after 28.03 seconds` in CloudWatch logs) while other endpoints work perfectly. 

I have seen https://github.com/brefphp/bref/issues/475 but I am not convinced that the error has to do with the database being inaccessible due to our VPC, because again, other endpoints which use the database seem to have no such connection issues. It is also worth noting that our `serverless.yml` file _is_ configured to host the lambdas in the VPC. 

I'm also not convinced that the error is a failure to connect to some other external resource, because logging indicates that the code is crashing before `boot` in `AppServiceProvider` is called, which means that the error is not caused by any code specifically within the failing endpoints. 

The nature of this error suggests that it should be happening on _every_ request, or not at all, which is why it's weird to me that it's only happening on SOME endpoints. And again, it's consistent about which endpoints work and don't work. I also haven't noticed any sort of pattern that links the consistently failing endpoints together.

**How to reproduce:**

_I'm not sure what is causing the issue, so I can't provide generic steps to reproduce._

**Comment by mnapoli** [comment]
Hey! Just to be sure, are you aware of this limitation: https://bref.sh/docs/environment/database.html#accessing-the-internet
