### ISSUE TITLE
[PHP-FPM] getcwd() will return '/'

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#1017]
When using the PHP FPM layer, calling `getcwd()` will return `"/"`. I would expect it to return `"/var/task"`. 

I will double check with the PSR-15 handler. I think that returns `"/var/task"`. See https://github.com/brefphp/bref/blob/dcf224abb57bbb757091c2b3a73132f149295d9d/src/Event/Http/Psr7Bridge.php#L34

**Comment by mnapoli** [comment]
Should be fixed in Bref v2
