### ISSUE TITLE
Local Function invocation broken in bref 1.3

### ISSUE THREAD

**Issue by veerendrapatel** [brefphp/bref#1037]
**Description:**

“bref/bref”: “1.3"  breaking local invocation of functions, whereas  “bref/bref”: “1.2" runs fine for  vendor/bin/bref local hello

**How to reproduce:**
 with 1.2 docker run --rm -it --entrypoint= -v $(PWD):/var/task:ro bref/php-80 vendor/bin/bref local hello => runs fine
with 1.3  docker run --rm -it --entrypoint= -v $(PWD):/var/task:ro bref/php-80 vendor/bin/bref local hello => PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /var/task/vendor/bref/bref/src/Console/Command/Local.php:110

I compared 1.3 and 1.2 Local.php and found in 1.3 Local.php $serverlessConfig[‘functions’] expects string
serverless.yml
service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    hello:
        handler: index.php
        description: ''
        layers:
            - ${bref:layer.php-80}

# Exclude files from deployment
package:
    exclude:
        - '!tests/**'

**Comment by GrahamCampbell** [comment]
Fixed in 1.3.1.

**Comment by mnapoli** [comment]
Right thanks!
