### ISSUE TITLE
Allow psr/container 2.0

### ISSUE THREAD

**Issue by swiffer** [brefphp/bref#1057]
I'm currently getting conflicting dependencies when trying composer update as bref is requiring psr/container: ^1.0 while cakephp raised there minimum required league/container to v4 which has psr/container: ^2.0

can psr/container: ^2.0 be allowed as well?

https://github.com/cakephp/cakephp/commit/6c2cb80071fb8d016f42f98dad2dcfce8f950523

**Comment by swiffer** [comment]
@t-richard thanks for the change - I still can't upgrade because mnapoli/silly has the same limitations. The repo seems to be really quite but as @mnapoli is also part of this repo maybe you can quickly change it over there as well?

**Comment by t-richard** [comment]
Also, a new release need to be published in Bref
