### ISSUE TITLE
bref layers: AWS authorization issue with `layer:php-80:29`

### ISSUE THREAD

**Issue by fbnfgc** [brefphp/bref#1101]
**Description:**

Hi there, and thanks for your amazing work on bref!

We use bref with serverless and AWS lambda for weeks but today we upgraded from `1.3.4`to `1.3.6` and fetching the PHP bref lambda layers didn't work anymore:

```
Serverless Error ----------------------------------------
 
An error occurred: ConsoleLambdaFunction - Resource handler returned message: "User: arn:aws:iam::***:user/[REDACTED] is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:209497400698:layer:php-80:29 because no identity-based policy allows the lambda:GetLayerVersion action (Service: Lambda, Status Code: 403, Request ID: 9c165a7c-3d26-4378-bf7b-45ad20bad9e9, Extended Request ID: null)" (RequestToken: [REDACTED] , HandlerErrorCode: AccessDenied).
```

The error seems related to the permissions on `arn:aws:lambda:eu-west-1:209497400698:layer:php-80:29`.
After rolling back to `arn:aws:lambda:eu-west-1:209497400698:layer:php-80:27`, everything works fine.

**How to reproduce:**

Use bref `1.3.6` and 

```
# serverless.yaml

        layers:
            - ${bref:layer.php-80}

```

**Comment by deleugpn** [comment]
This is very strange, I just tested the exact same Layer posted here (`arn:aws:lambda:eu-west-1:209497400698:layer:php-80:29`) and I don't get any issue.

I'm just guessing here, but could it be that your user no longer have access to `lambda:GetLayerVersion` but returning to the previous version it means your account used the cached version of the layer?

Could you maybe try with version 28 and 26?

**Comment by fbnfgc** [comment]
Thanks for your time and for looking at it so quickly @deleugpn. I did the tests you suggested with different versions of the layer (23 & 28) and I had the same problem. This comes from the user's permissions and therefore from us.

Sorry for the inconvenience and thanks again for your help. :pray:
