### ISSUE TITLE
Upgrading bref to 1.4 causes third party api calls to fail

### ISSUE THREAD

**Issue by justageek** [brefphp/bref#1111]
We recently upgrade bref from an old .5 version to the latest 1.4 version, and calls to a critical third party api we use suddenly stopped working.  So far I suspect that this third party api is using a self signed certificate, and this suddenly started causing an exception in the api call, even though it never has before for over a year.  I cannot find any changes to other composer packages that accompanied the bref upgrade and would have affected this logic, does anyone have any ideas.  Would Amazon Linux 2 be the problem somehow, maybe something changed with the underlying curl libraries?

**Comment by shabanbx** [comment]
check to see if your lambda still has internet access.

**Comment by shabanbx** [comment]
in your lambda go to configuration->VPC

there you will have your VPC attached to the lambda which helps to get the internet.

but if the downgrade get's the api working maybe that's not the case.

**Comment by justageek** [comment]
@shabanbx thanks, I also upgraded our dev environment and confirmed that if I tell Guzzle to ignore the self signed certificate, it works fine, which does not make sense as we have by verifying this certificate by default for over a year, so I don't know why bref version would affect that all .

**Comment by deleugpn** [comment]
@justageek have you investigated this further? One thing that pops to mind is the fact that openssl version differs between Bref versions as well as Guzzle version. A self-signed certificate could have been some sort of edge-case overlooked by one of the layers of abstraction that the code goes through?

**Comment by mnapoli** [comment]
I'll close this for now because it is an inactive issue and we have had no other report. Let's reopen if we have more data.
