### ISSUE TITLE
Serverless deploy error: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by nsaliu** [brefphp/bref#1147]
**Description:**

When I try to deploy my project I get this error when I run: `serverless deploy`

```
$ serverless deploy 
Environment: linux, node 12.22.5, framework 3.0.1, plugin 6.0.0, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read property 'bind' of undefined
    at new ServerlessPlugin (/home/xxx/projects/personal/xxx-api/vendor/bref/extra-php-extensions/index.js:45:33)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:88:28)
    at /usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:33
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:8)
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/serverless.js:137:30)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:529:7
```

Can someone help me on this?

**Comment by t-richard** [comment]
Hi

It seems you are running the v3 version of serverless framework.

The bref extra extensions package is not yet compatible with the latest version from serverless framework.

A PR is opened to do it: https://github.com/brefphp/extra-php-extensions/pull/311

In the meantime, please downgrade to serverless framework v2 or use the fork of the person who submitted the PR.

**Comment by nsaliu** [comment]
Thanks for this useful information 👍

I've already downgraded serverless to 2.x (the latest one before 3.x) and all works fine. 

Hope that this thread will be useful also to other peers 👍

**Comment by mnapoli** [comment]
Current status: https://github.com/brefphp/extra-php-extensions/pull/308#issuecomment-1026030179

**Comment by mnapoli** [comment]
Please upgrade bref/extra-php-extensions to the latest version 🎉
