### ISSUE TITLE
Incorrect symfony/console version constraint

### ISSUE THREAD

**Issue by hardyjohnson** [brefphp/bref#1157]
**Description:**

Currently bref declares a requirement for the following version constraint for "symfony/console": "^3.0|^4.0|^5.0|^6.0"
https://github.com/brefphp/bref/blob/1.5.2/composer.json#L25.

**How to reproduce:**

Create an application with a constraint for symfony/console lower than 5.1. I see this currently with a Laravel application based on the 6.x release.

Unfortunately when something goes wrong during a bref command (which should be handled by the proper exit code) a fatal error is triggered due to an undefined constant reference in `src/Console/Command/Cli.php` line 52.

The reference is to the constant `Symfony\Component\Console\Command\Command::FAILURE` which was introduced in the `symfony/console` component 5.1 branch.

```
PHP Fatal error:  Uncaught Error: Undefined class constant 'FAILURE' in /vendor/bref/bref/src/Console/Command/Cli.php:52
Stack trace:
#0 /vendor/symfony/console/Command/Command.php(255): Bref\Console\Command\Cli->execute()
#1 /vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#2 /vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#3 /vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#4 /vendor/bref/bref/bref(28): Symfony\Component\Console\Application->run()
#5 /vendor/bin/bref(112): include('/home/runner/wo...')
#6 {main}
  thrown in /vendor/bref/bref/src/Console/Command/Cli.php on line 52
```

I believe the constraint for `symfony/console` should be `^5.1|^6.0` due to this issue.

**Comment by t-richard** [comment]
Thanks for reporting that issue.

If that's the only incompatibility, we could just replace all `return Command::FAILURE` by `return 1`

**Comment by t-richard** [comment]
@hardyjohnson could you test there are no more issues if using version dev-master for Bref in your composer.json?

**Comment by hardyjohnson** [comment]
@t-richard I will test locally thanks for jumping on this!
