### ISSUE TITLE
Log the  lambda request id in the timeout exception

### ISSUE THREAD

**Issue by allan-simon** [brefphp/bref#1187]
So that it's easier to map this log to other log in tools like kibana /grafana 

Implementation:  make the  TimeOut exception take a second parameter (optional  so that it works in the local docker environment ?) which is the lambda request id coming from the context 

If you think it is a good idea, I can provide the PR

**Comment by mnapoli** [comment]
Hey, on paper that sounds like a good idea!

I think there's still a request ID in Docker invocations, so it might not be worth making an exception for this.

**Comment by allan-simon** [comment]
@mnapoli  actually that was pretty simple to implement :)
