### ISSUE TITLE
Support for Lambda Insights

### ISSUE THREAD

**Issue by kevohagan** [brefphp/bref#1208]
I've been trying to set up Lambda insights but to no avail. 
Is there support for it with the custom runtime? I don't seem to find any information only about bref + lambda insights.

**Comment by mnapoli** [comment]
I'm sorry but we'll need more context here. What did you do, what did you expect to happen and what happened instead? I don't use Lambda insights so I'm not sure how that relates to Bref.

**Comment by FRoepstorf** [comment]
I'm just adding the lambdaInsights to our docker image , bref does not care nor interfere:

`RUN curl -O https://lambda-insights-extension.s3-ap-northeast-1.amazonaws.com/amazon_linux/lambda-insights-extension.rpm && \
    rpm -U lambda-insights-extension.rpm && \
    rm -f lambda-insights-extension.rpm`

**Comment by kevohagan** [comment]
> I'm sorry but we'll need more context here. What did you do, what did you expect to happen and what happened instead? I don't use Lambda insights so I'm not sure how that relates to Bref.

Sorry about that @mnapoli , let me give you more context : 

- I'm trying to get the enhanced monitoring from Lambda Insights, this normally should be straightforward from the docs , add a lambda layer and add a IAM policy to call the cloudwatch insights service from lambda https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-cloudformation.html

- I suspected this should work out of the box for bref but it doesn't seem to be the case, Lambda Insights uses the Lambda Extensions API to get this working and supports all Lambda runtimes , since Bref is a custom runtime there might be some extra work needed for it to work I guess.  https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html

I unfortunately don't have enough knowledge about this to know if that's the case. Also I am not using a docker image so the solution @FRoepstorf gave would not work for me

**Comment by mnapoli** [comment]
Oh, interesting. TBH I never used it. From the docs I gather that there shouldn't be a problem with Bref in itself (i.e. no problem with anything using the `provided.al2` runtime). But I don't have more information unfortunately.

**Comment by kevohagan** [comment]
Okay, so it seems my issue has nothing to do with Bref, but with the fact that I have my lambda in a VPC and it doesnt have network access to Cloudwatch Insights service. Closing issue , sorry for the noise!

**Comment by fredericgboutin-yapla** [comment]
> I'm just adding the lambdaInsights to our docker image , bref does not care nor interfere:
> 
> `RUN curl -O https://lambda-insights-extension.s3-ap-northeast-1.amazonaws.com/amazon_linux/lambda-insights-extension.rpm && \ rpm -U lambda-insights-extension.rpm && \ rm -f lambda-insights-extension.rpm`

Official doc from AWS - [Enabling Lambda Insights on a Lambda container image deployment](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-docker.html) 🎉

**Comment by mnapoli** [comment]
Hi @fredericgboutin-yapla, thanks for sharing!
I'd be curious about your use case: how Lambda insights is useful in your case, and whether you'd be interested in X-Ray support too (I'm looking into it right now and you seem like it might be a good fit too). Would you have 10 minutes to discuss this?

**Comment by fredericgboutin-yapla** [comment]
TBH I'm still quite novice with serverless but I used it in a couple of different nodejs projects in the last year and lambda insights provided me with those useful extra info for profiling and tweaking my lambda functions.

<img width="1232" alt="image" src="https://github.com/brefphp/bref/assets/91906601/7c739747-e607-4b4c-8454-2eb56eb1c5b5">

For example, memory consumption and CPU usage VS lambda memory profile. In a perfect scenario you can double the memory profile, which doubles the pricing but reduces in half execution time, so in the end it costs literally the same but takes half the time.

It seems there is an automated way to do this, tough.

- https://docs.aws.amazon.com/lambda/latest/operatorguide/profile-functions.html
- https://github.com/alexcasalboni/aws-lambda-power-tuning
