### ISSUE TITLE
Terminating runtimes

### ISSUE THREAD

**Issue by tillkruss** [brefphp/bref#1209]
It would be great if we could call a `terminate()` or similar when exiting runtimes, instead of the current `exit(0)`
https://github.com/brefphp/bref/blob/904e3f3f13848a24e830a2d87d3a4438435e702e/runtime/layers/function/bootstrap.php#L39-L42

This would allow custom behaviour such as closing persistent database connections. Maybe as simple as calling `terminate()` on the `$handler` if the method exists.

Happy to open a PR.

**Comment by deleugpn** [comment]
I like the idea, but one important aspect for bref has been parity with how AWS native runtimes work. If you could provide a code snippet on how you'd achieve the same thing on NodeJS we could then evaluate what's missing on Bref and how we can replicate the same behavior. What do you think?

**Comment by tillkruss** [comment]
@deleugpn: I'm not familiar with the parity, but I'll gladly do that. Could you point me to a Node.js code example as a foundation?

**Comment by mnapoli** [comment]
How about https://www.php.net/manual/function.register-shutdown-function.php ?

**Comment by tillkruss** [comment]
@mnapoli If `register_shutdown_function()` works, perfect!

**Comment by fredericgboutin-yapla** [comment]
FYI - Using `register_shutdown_function` as a substitute for terminating runtimes won't work in conjunction with `BREF_LOOP_MAX` greater than `1` - aka https://github.com/brefphp/bref/issues/100#issuecomment-443680470
