### ISSUE TITLE
Allow Bref layers to be used with Localstack Pro

### ISSUE THREAD

**Issue by shadowhand** [brefphp/bref#1261]
Localstack Pro can be used with Serverless Framework for local deploys, but it currently fails because the layers are not accessible. Localstack Lambda _does_ have the ability to automatically pull the layers down from AWS proper, but it needs [access granted to the Localstack account][1].

Can the referenced permissions be added so that we can use Bref + Localstack?

```
aws lambda add-layer-version-permission
  --layer-name <layer-name-here>
  --version-number <layer-version-here>
  --statement-id layerAccessFromLocalStack
  --principal 886468871268
  --action lambda:GetLayerVersion
```

[1]: https://docs.localstack.cloud/aws/lambda/#referencing-lambda-layers-from-real-aws

**Comment by shadowhand** [comment]
The only other alternative we have to move forward with Localstack deploys is [download the layers][1], upload them into Localstack, and create a different serverless.yml for local deploys. This will be a nightmare to maintain and keep in sync with the main serverless.yml, so I hope this will be implemented.

[1]: https://stackoverflow.com/questions/56614037/how-to-download-aws-lambda-layer

**Comment by deleugpn** [comment]
Layers already have permission on `*` otherwise people wouldn't be able to pull them inside their own AWS account. The permission error is likely caused by your IAM Role and not lack of layer permission.
It's also common to get access denied if you have a typo on the layer and/or have the wrong version
