### ISSUE TITLE
RFC: Switch to `->warning()` when `serverless` executable is not found

### ISSUE THREAD

**Issue by nealio82** [brefphp/bref#1262]
I've been putting together a sample application for a workshop on refactoring a stateful PHP application to run on top of Lambda with Bref, starting with an alpine PHP-FPM container and a separate Serverless container.

I'm starting with the bog-standard PHP-FPM alpine image rather than the Bref image because I want to show a step-by-step refactoring to using Serverless from first-principles _without_ a lot of the abstractions and improvements which does the hard stuff for you.

But... when I try to run `vendor/bin/bref init` I run into the blocking exception

```
'The `serverless` command is not installed.'
```

And then the script quits with `return 1;`

As far as I can see this is just a sanity check to make sure the project would be deployable with the current setup.

However, I know that serverless _is_ installed, it's just not available within the PHP container I'm running in my local env. I've had to add the following additional concerns into my dockerfile just to be able to init the project (which feels like a coupling it shouldn't need to be aware of):

```
RUN apt update
RUN apt install nodejs npm -y

RUN npm i -g serverless
```

I propose to change the `$io->error(...)` to `$io->warning(...)` and allow the script to continue, so that Docker setups which have moved the SLS executable into another container can proceed without hacking the existing Dockerfile.

Currently we have this:

```
$exeFinder = new ExecutableFinder;
if (! $exeFinder->find('serverless')) {
    $io->error(
        'The `serverless` command is not installed.' . PHP_EOL .
        'Please follow the instructions at https://bref.sh/docs/installation.html'
    );

    return 1;
}
```

I propose to switch to:

```
$exeFinder = new ExecutableFinder;
    if (! $exeFinder->find('serverless')) {
        $io->warning(
        'The `serverless` command is not installed locally.' . PHP_EOL .
        'You will not be able to deploy your application unless it is installed' . PHP_EOL .
        'Please follow the instructions at https://bref.sh/docs/installation.html to install'  . PHP_EOL .
        'If you have the `serverless` command available elsewhere (eg in a Docker container) you can ignore this warning'
    );
}
```

WDYT?

**Comment by mnapoli** [comment]
Hey @nealio82, that sounds great, 100% for it  👍

**Comment by t-richard** [comment]
Seems legit, we often run in a similar setup where Docker containers are "single-purpose".

**Comment by nealio82** [comment]
Cool, I'll make a PR a bit later then :)
