### ISSUE TITLE
Bad management format for IntlDateFormatter

### ISSUE THREAD

**Issue by piolet** [brefphp/bref#1276]
Hi all,

I use **intl extension** to replace deprecated strftime in php 8.1. For this, i follow [documentation](https://bref.sh/docs/environment/php.html#extensions-installed-but-disabled-by-default) and it's OK.

But, in PHP document, about [IntlDateFormatter::formatObject](https://www.php.net/manual/en/intldateformatter.formatobject.php), the formatting used is as follows : [format](https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax)

In my case, i used this format to display month's name : `"MMM"`
In my local environnement (with a docker with PHP 8.1), it's ok. I have `sept.` displayed.
But, when i deploy my lambda with bref:layer.php-81-fpm and a specific php.ini (with only `extension=intl`) i have `9` displayed instead of `sept.`.

do you have any idea what I missed or it's a bug ?

I understand that for version 9 of PHP **Intl** will be the standard, so I try to anticipate

**Comment by afu-dev** [comment]
Hello @piolet! 🙂

I tested with a fresh install of Bref (v1.7.5) with the `php-81-fpm` layer.

The function and the class correctly return `Sep` for a DateTime set to now.

![image](https://user-images.githubusercontent.com/15209405/190984344-bd9911ca-77e8-4219-a2b7-6f244123d374.png)

Can you share a bit of code with us?

**Comment by piolet** [comment]
Hi @afu-dev 

you saved my day ;)
My piece of code is :
`IntlDateFormatter::formatObject($date, $format, $timezone_name)`
and the difference with your code is the timezone.
With timezone, it's not ok, without, it's ok like you.

Thank you

**Comment by afu-dev** [comment]
The third parameter is for the locale (the language), not the timezone 😉 

![image](https://user-images.githubusercontent.com/15209405/191095620-55054272-c3f5-4f01-a7ef-19980119633f.png)

Don't worry, it happens to everyone 😅

**Comment by piolet** [comment]
often for me ;)
