### ISSUE TITLE
Some php.ini values are overridden

### ISSUE THREAD

**Issue by josephLaurent** [brefphp/bref#1288]
Hi,

I use a `php/conf.d/php.ini` file to override the bref default php configuration and I am not able to update some of them.

In my case, I tried to update the `display_errors` value (I also tried to update the `error_reporting` for the example).
This is my `php/conf.d/php.ini` file:
```
display_errors = 0
error_reporting = E_USER_DEPRECATED
```
But at the first line of my `index.php`, I tried to get these two values and I get this:
```
Directive => Local Value => Master Value
display_errors => STDOUT => Off
error_reporting => 32767 (E_ALL) => 16384 (E_USER_DEPRECATED)
```
The master value is well updated, but the local value has been overriden.
If I add the following line, everything is fine again but I would like to avoid doing this:
`ini_set('display_errors', 0)`

I only get this issue when using the php-function layer and not with the php-fpm layer.

I'm guessing that the value is probably updated by bref just when the lambda start, maybe there https://github.com/brefphp/bref/blob/master/runtime/layers/function/bootstrap.php#L6 ?

If yes, Is there a reason why bref update these values outside of the initial php.ini file https://github.com/brefphp/bref/blob/master/runtime/layers/function/php.ini ?

Thank you in advance for your responses :)

**Comment by mnapoli** [comment]
Ohhh this is very good investigation! Indeed I don't remember why the value is re-set manually in bootstrap.php 🤔 

It's been there since the beginning (e.g. in 2018 https://github.com/brefphp/bref/blob/cadc1f93243a4aa2bf44885adcd936126b59d98c/runtime/default/bootstrap) when FPM didn't exist.

I think we can remove the `ini_set` calls.

**Comment by josephLaurent** [comment]
Ok, I just created a pull request to delete it :)  https://github.com/brefphp/bref/pull/1290
I also removed the `error_reporting(E_ALL);` as it is set in the php.ini but with an other value.

**Comment by mnapoli** [comment]
Thank you for the report, I'll make this as solved in v2.
