### ISSUE TITLE
Expose layers to JS apps via a NPM package

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#1300]
WIP: https://github.com/brefphp/layers.js

This will allow writing:

- a Serverless Framework plugin distributed via NPM (no need for Composer install to deploy, requested by some)
- a CDK integration
- a Pulumi integration

This isn't mandatory and will not affect most Bref users. But it will unlock more use cases.

**Comment by GrahamCampbell** [comment]
> no need for Composer install to deploy, requested by some

Who are these animals? 😆 :trollface:

**Comment by mnapoli** [comment]
Done and automated!

https://github.com/brefphp/layers.js has layers.json updated and a new release tagged automatically whenever we publish new layers 🎉
