### ISSUE TITLE
Remove `intl` from the layers by default in Bref 2.0?

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#1301]
The `intl` extension is the biggest extension by far. It includes the following files in the layer:

- `intl.so`: 0.47MB
- `libicuio.so.71`: 0.06MB
- `libicui18n.so.71`: 3.2MB
- `libicuuc.so.71`: 2MB
- `libicudata.so.71`: 29MB

In total it's 34.7MB.

The layer weighs 66MB. Intl is half of that 🤷 

What I'm wondering is:

- is `intl` used by most applications or not?
- if not, can we make it easy to install it 🤔  (extra layer?)

**Comment by georgeboot** [comment]
We use `intl` all the time in our (monolithic) projects. Formatting currencies, large numbers etc.

If you are using bref, you probably at least have some idea about what is what, so adding a custom layer isn't thát big of a deal.

**Comment by kevincerro** [comment]
As @georgeboot said.

On a typical Laravel/Symfony app `intl` is required to format currencies etc 

I prefer having `intl` in a separate layer than bundled in the default PHP layer.

- Bref for functions, no need to use intl if your project doesn't requires it
- Bref for Laravel/Symfony, add the layer ARN and you are ready to go

**Comment by GrahamCampbell** [comment]
I think this would be fine. People can opt to load an intl extension in, if they want it, right?

**Comment by GrahamCampbell** [comment]
Could always have it installed by default in examples. People can then delete 2 lines or whatever.

**Comment by afu-dev** [comment]
`intl` is used by only one of my applications. I think it should be installed via a `bref-extra` layer like others extensions.

**Comment by mnapoli** [comment]
The more I think about this the more I really want Bref to work out of the box for Symfony/Laravel. Making this a separate layer is some effort for users, but also internally. Will keep thinking about it.

**Comment by GrahamCampbell** [comment]
I don't think having it work out of the box is incompatible with it being there as an extension. We'd just have to make sure all the examples and whatnot include the extension. Easier for people to remove it that way. You do have a good point that probably most people will want it, and that those that don;t are unlikely to care that it's being loaded, still.

**Comment by GrahamCampbell** [comment]
Has anyone ever complained about the bref image being too large? Or just that their vendor dir was massive, of their own making?

**Comment by mnapoli** [comment]
For sure the vendor directory is the biggest thing that can cause issues with the 250MB limit.

**Comment by Riches** [comment]
I would be in favour of removing it to reduce the overall size of the layers and to speed up cold starts. Personally, I would explore using the Symfony polyfills as they'd likely be much lighter than deploying the full extension.

I'm not sure if there is also scope to release a bare skeleton bref with no extensions, where you can add extra extensions as layers (as long as this is possible) alongside a turnkey/default bref that will just work for most use cases albeit considerably heavier.

**Comment by kevincerro** [comment]
> I would be in favour of removing it to reduce the overall size of the layers and to speed up cold starts. Personally, I would explore using the Symfony polyfills as they'd likely be much lighter than deploying the full extension.
> 
> I'm not sure if there is also scope to release a bare skeleton bref with no extensions, where you can add extra extensions as layers (as long as this is possible) alongside a turnkey/default bref that will just work for most use cases albeit considerably heavier.

A bare skeleton isn't a good choice for most of the use cases because lambda supports up to 5 layers max.

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

**Comment by mnapoli** [comment]
Some update here: with the new builds (where we compile PHP from scratch) the difference with/without intl is less drastic.

We can basically go from 16MB -> 15MB if we get rid of `intl.so`, which is not a lot. A such I'll close this issue.

If you want to investigate and look at other ways to improve cold starts by lightening the layers, here is the content of the PHP 8.2 FPM layer (ARM, but shouldn't be different from x86):

```
   - 14 fév 11:36 ├── ssl
217k 14 fév 11:36 │  └── cert.pem
   - 14 fév 11:36 ├── bin
 18M 14 fév 11:36 │  ├── php
 18M 14 fév 11:36 │  └── php-fpm
   - 16 fév 11:57 ├── bref
   - 16 fév 11:57 │  ├── etc
   - 16 fév 11:57 │  │  ├── php
   - 16 fév 11:57 │  │  │  └── conf.d
2,0k 29 jan 21:14 │  │  │     └── bref.ini
1,1k 15 oct  2022 │  │  └── php-fpm.conf
   - 14 fév 11:36 │  ├── extensions
 77k 14 fév 11:36 │  │  ├── pdo_mysql.so
 82k 14 fév 11:36 │  │  ├── pdo_pgsql.so
702k 14 fév 11:36 │  │  ├── apcu.so
2,1M 14 fév 11:36 │  │  ├── intl.so
2,2M 14 fév 11:36 │  │  └── opcache.so
 509 15 fév 16:31 │  └── bootstrap.php
   - 14 fév 11:36 ├── lib
 68k 14 fév 11:36 │  ├── libgpg-error.so.0
136k 14 fév 11:36 │  ├── libexslt.so.0
165k 14 fév 11:36 │  ├── libzip.so.5
271k 14 fév 11:36 │  ├── libxslt.so.1
303k 14 fév 11:36 │  ├── libssh2.so.1
308k 14 fév 11:36 │  ├── libnghttp2.so.14
440k 14 fév 11:36 │  ├── libpq.so.5
546k 14 fév 11:36 │  ├── libgcrypt.so.11
755k 14 fév 11:36 │  ├── libcurl.so.4
852k 14 fév 11:36 │  ├── libssl.so.1.1
1,2M 14 fév 11:36 │  ├── libsodium.so.23
1,7M 14 fév 11:36 │  ├── libonig.so.5
2,1M 14 fév 11:36 │  ├── libxml2.so.2
3,7M 14 fév 11:36 │  └── libcrypto.so.1.1
 843 15 fév 16:31 └── bootstrap
```

A few ideas that could be worth exploring:

- why is `libcrypto.so.1.1` so big and could we optimize that?
- why is `opcache.so` so big? on my Mac it's 1.7MB, not much less but still…
- could we skip shipping `php` and `php-fpm` binaries and only have one? This is where we would gain the most, but I don't think it's possible… If we could use `php-fpm` like the `php` binary we could save a lot.

**Comment by GrahamCampbell** [comment]
opcache has to do a lot. ;)
