### ISSUE TITLE
[Question] Change of AWS account for layers is faulted?

### ISSUE THREAD

**Issue by negoziator** [brefphp/bref#1302]
**Description:**

I'm experiencing after updating the bref-layers, that are using the new AWS account ( `209497400698` --> `534081306603` )
the layer does not recognize the bref/bref composer package anymore.

**How to reproduce:**

update bref layer from

`arn:aws:lambda:eu-north-1:209497400698:layer:php-81:30`
to
`arn:aws:lambda:eu-north-1:534081306603:layer:php-81:2`

**Erros seen**

```
Fatal error: Uncaught RuntimeException: Bref is not installed in your application (could not find the class "Bref\FunctionRuntime\Main" in Composer dependencies). 

Did you run "composer require bref/bref"? in /opt/bref/bootstrap.php:14
```

**How to fix**

rollback breflayer to `arn:aws:lambda:eu-north-1:209497400698:layer:php-81:30`

**Comment by mnapoli** [comment]
Hi, where did you find instructions to change the account for the layers? Or another way to phrase the question: why was the account ID changed?

Are you trying to intentionally use Bref v2? Because it seems you didn't install Bref's v2 version, you just used Bref v2 layers with v1 codebase.

**Comment by negoziator** [comment]
I found it right here:

https://bref.sh/docs/runtimes/index.html

Is the documentation only pointing towards V2 now?

**Comment by mnapoli** [comment]
Ohhh thank you, that is indeed a mistake in the docs 😄 

https://runtimes.bref.sh/ was updated to let visitors select v2 (beta), but v1 stays the default. However in the "embedded" view in the page you linked, the v2 layers are shown by default. This is my mistake.

I'll fix that on https://github.com/brefphp/runtimes.bref.sh and redeploy 👍

**Comment by mnapoli** [comment]
(also to clarify, v2 is completely in beta, it shouldn't be used unless you absolutely want to, that's why I was surprised that you were using these layers)

**Comment by mnapoli** [comment]
Fixed, https://bref.sh/docs/runtimes/index.html is updated. Thank you for opening an issue!

**Comment by negoziator** [comment]
Very nice @mnapoli 🚀
