### ISSUE TITLE
Bref/Application class not found

### ISSUE THREAD

**Issue by maverick108** [brefphp/bref#1309]
**Description:**
I am trying to run a SLIMMVC API with brief

The below code is throwing a class not found an error 
$app = new \Bref\Application;

**How to reproduce:**

composer install bref/bref or mnapoli/bref and slim 3.x
`<?php

use Bref\Bridge\Slim\SlimAdapter;

require __DIR__.'/vendor/autoload.php';

$slim = new Slim\App;
$slim->get('/dev', function ($request, $response) {
    $response->getBody()->write('Hello world!');
    return $response;
});

$app = new \Bref\Application;
$app->httpHandler(new SlimAdapter($slim));
$app->run();

?>`

Run the index.php file, you will get the error

Is there a bridge for bref and SLIM framework?

**Comment by mnapoli** [comment]
Hi, it seems you are following an outdated tutorial. I would recommend to uninstall Bref and start from scratch here: https://bref.sh/docs/installation.html

**Comment by maverick108** [comment]
I have followed those. But I was not able to make the SLIM framework with bref. It not routing properly. It says page not found

**Comment by maverick108** [comment]
> I have followed those. But I was not able to make the SLIM framework with bref. It not routing properly. It says page not found. Do you have any sample code for SLIM MVC API or bridge like you have for Laravel?
