### ISSUE TITLE
Add Laravel Nova Specific docs

### ISSUE THREAD

**Issue by CodeTechNL** [brefphp/bref#1335]
Hi,

Would you mind to have a Laravel Nova specific section at the Laravel documentation? A while ago I've had issues with the X-Inertia header and this time with the php extension intl which is required if you want to use the money field. I know that the docs do have a section about PHP extensions, but its simple to mis that section.

**Comment by mnapoli** [comment]
Hi! Sure, feel free to send a PR, I think that would be very useful!

**Comment by CodeTechNL** [comment]
Will do with Nova!

Maybe a tips & tricks section? I was stuck on a API that sends X-Some-Value-Headers, but like 4 or 5 different ones. As AWS only supports 10, I created a API gateway mapper. The webhooks with headers are send to https://aws-api-gateway-url.com/webhooks, a lambda function takes that request, makes a new URL to my application and set the request headers to the URL. Example:

https://aws-api-gateway-url.com/webhooks

X-Header-A: ValueA
X-Header-B: ValueB
X-Header-C: ValueC

Catch and resend:

`axios.post('https://my-domain.com/webhooks/header-a/ValueA/header-b/ValueB/header-c/ValueC');`

In Laravel you can catch the params by:

`Route::get('/header-a/{paramA}/header-b/{paramB}/header-c/{paramC}')`

**Comment by mnapoli** [comment]
FYI the headers issues have been fixed by https://github.com/getlift/lift/pull/306
