### ISSUE TITLE
Custom Path php.ini (PHP_INI_SCAN_DIR) broken in 2.0.0-beta1

### ISSUE THREAD

**Issue by swiffer** [brefphp/bref#1362]
**Description:**

The Docs of 2.0.0-beta1 still mention to support a custom php.ini dir:
https://github.com/brefphp/bref/blob/v2/docs/environment/php.md#customizing-phpini-using-a-custom-path

however this is no longer working in 2.0.0-beta1, i think because of:
https://github.com/brefphp/aws-lambda-layers/blob/main/layers/function/bootstrap.sh

**How to reproduce:**

Bref 2.0.0-beta1: https://github.com/brefphp/bref/releases/tag/2.0.0-beta1
Set custom PHP_INI_SCAN_DIR according to docs (e.g. enabling intl extension, in a folder other than ./php/conf.d/)
Check if extension is loaded within the handler: `extension_loaded('intl')` (should be true but is false)

**Comment by mnapoli** [comment]
Thank you for the report! That should be fixed with https://github.com/brefphp/aws-lambda-layers/pull/41

I'll publish a new Bref version this afternoon.
