### ISSUE TITLE
[Beta] Could not execute the command on AWS lambda with `bref:cli`

### ISSUE THREAD

**Issue by theofidry** [brefphp/bref#1364]
So previously I was running:

```
$ vendor/bin/bref cli symfony-dev-web --region="eu-central-1" -- about
```

This was a close to new app, really more to try things out. I found a bit weird that I had to specify the region when it's already specified in the serverless config but that's a different topic.

After trying the beta:

```
$ serverless bref:cli about
$ serverless bref:cli --args=about
$ serverless bref:cli --command=about
```

This is an issue created on top of my head to not forget. If you do need more details  like the serverless config let me know.

**Comment by mnapoli** [comment]
Thanks for the report, that sounds like a very obvious/dumb bug somewhere 👍 I'll check this out!

Could you let me know what the error was though?

I'd also love to make sure that you are using the `${bref:layer.console}` variable in `serverless.yml` (not referencing the layer ARN directly), could you confirm that? ([this is how the console function is identified](https://github.com/brefphp/bref/blob/v2/plugin/run-console.js#L15-L39))

**Comment by theofidry** [comment]
From memory the output just fell completely off, it was giving the result of `bin/console` (i.e. listing the commands) instead of `about`. So I had the impression that either is was failing to pick up the function to execute (I doubt it though since a CLI for the web would give a different error) or more likely the additional options were not passed

**Comment by theofidry** [comment]
If you do need a more detail report I'll have to checkout that test repo again, won't be able to before 1-2 day if before Christmas

**Comment by mnapoli** [comment]
Oh I see it now, you have to use the `--args` option:

```
serverless bref:cli --args="<command to run in lambda>"
```

See https://github.com/brefphp/bref/blob/v2/docs/runtimes/console.md#usage

I'll keep this issue open to try and add a better error message though, I'm surprised the serverless CLI didn't throw an error because of the extra arguments.

**Comment by theofidry** [comment]
But that was the second example no?:

```
serverless bref:cli --args="about"
```

At least that's what I inferred from the doc, I was a bit confused with `--commands` and was wondering if there were any back-and-forth so in doubt I tried both. Your documentation gives this example as well:

```
serverless bref:cli --args="doctrine:migrations:migrate"
```

But at the very least from the output it was clear this was just the list of commands, not the output of the `about` command.

**Comment by jacovdbergh** [comment]
Running into the same issue I think, where the arguments are not forwarded to the console handler function.
I'm using the console layer (`bref:layer.console`), and running `sls bref:cli --command="inspire"`, which just dumps the possible artisan commands, as if no arguments were provided.

Ps, think the docs for V2 is wrong at the moment, it states that the argument for bref:cli is `--args` but from index.js it looks like it should be `--command`, or `-a`.

**Comment by mnapoli** [comment]
Thanks! Sorry about the confusion, I need to look into this 😅

**Comment by jacovdbergh** [comment]
Could it be line 9 in run-console.js 
```
options.data = options.args;
```
that should be using `options.command`?

Or index.js should define args instead command :)

**Comment by mnapoli** [comment]
💯 I think I copy-pasted code too quickly when I implemented this ^^

It should be `--args` because the command is defined in `serverless.yml`, we are passing the "arguments" to the command. Anyway I pushed a commit and just tagged https://github.com/brefphp/bref/releases/tag/2.0.0-beta4

Let me know if that works better!

**Comment by jacovdbergh** [comment]
![image](https://user-images.githubusercontent.com/24895833/209319359-c615ec72-117a-4481-bdbe-ed4cacc4ccd9.png)

Perfect, thanks for the quick fix!

**Comment by theofidry** [comment]
Won't be able to give it a try but I doubt my case was anything special so if it works for @jacovdbergh I'm pretty sure it will work for me :) Thanks for the fix!
