### ISSUE TITLE
Make handlers more easily testable by removing `final` keyword

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#1396]
Reported by @marcguyer on Slack.

### Problem

Typed events (like `SqsEvent`) and `Context` are all `final`.

That was so that we could add any method without fearing breaking BC.

However, it makes mocking in tests very hard. You have to do create the payload manually, for example:

```php
$handler->handleSqs(
		$sqsEvent = new SqsEvent(['Records' => [[
			'eventSource' => 'aws:sqs',
			'body' => '{"eventRequestId":999,"startingState":"event_planned","targetState":"event_canceled"}',
		]]]),
		new Context('', intval(microtime(true) * 1000) + 6000, '', '')
);
```

Removing `final` would allow using `$this->createMock()`.

### Proposed solution

Remove `final` on these classes, but **document** in phpdoc that these classes should not be extended with new methods (no BC promise). They are "final" in spirit, but not in practice to allow mocking.

**Comment by mnapoli** [comment]
Alternative approach: adding helper methods to quickly create instances without having to create a fake Lambda payload by hand.

Here's an example with just the `Context` class: https://github.com/brefphp/bref/pull/1398

**Comment by mnapoli** [comment]
Note: the approach above is great for `Context` I think, but is much more work to apply (and apply consistently) across all typed events.

It turns out `@final` is enforced by Phpstan and Psalm (https://phpstan.org/r/80a438f2-775f-4c79-b0e0-624bd17dd4f2), so relying on this annotation and removing `final` could work!

**Comment by Slamdunk** [comment]
The classes you mention here should never be mocked. Mocks serve a controlled and manipulated behaviour. Those classes are, as far as I can tell, value objects therefore with a behavior that do not rely on external nor internal states.

Fake helpers are the correct way to go.

`@final` keyword enforced by SA works, but hides a technical debt under the carpet: fake helpers should be easy to create and maintain; if they aren't, I'd say there's a smell somewhere in the code architecture.

**Comment by mnapoli** [comment]
@Slamdunk I'm not really interested in debating generic theoretical ideas, because in my experience these are never useful to solve a specific problem.

I'm more interested in solving the problem here specifically. And the problem is, these typed handlers are hard to write tests for.

How can we solve that problem? It may be by making it easier to use `createMock`, it may be via another solution. I'd rather discuss concrete solutions rather than discuss abstract programming principles. Because "fake helpers" handwaves a lot of how we can make that happen in a realistic and practical way both for maintainers and users.

**Comment by bambamboole** [comment]
I prepared a solution via a factory here: https://github.com/brefphp/bref/pull/1399

**Comment by Slamdunk** [comment]
@mnapoli It seems my communication has been received by you as a theoretical debate: that wasn't my intention.
I've seen your tweet, I've seen you questioning yourself on the correct approach and asking the community for a feedback, so I gave you mine.

I would have completely avoided my (sparse) contribution if you would just have asked for the quickest workaround.

**Comment by mnapoli** [comment]
Understood, let's ignore whether or not its theoretical and move forward. We still aren't closer to a concrete example that improves the lives of users compared to what they can do today. That's what I'm interested in discussing.

Today it's mildly inconvenient. How can we make that experience better.

**Comment by marcguyer** [comment]
I first ran into some difficulty when writing tests to assert some "approaching" timeout behaviors. Due to the temporal nature of this method:

https://github.com/brefphp/bref/blob/master/src/Context/Context.php#L43-L46

... I wanted to mock it... to say something like `Context::getRemainingTimeInMillis() will return 10`... but the `final` keyword prevents that of course. Instead, we need to do this to end up getting a "real" value that fits into our test run window...

```php
new Context('', intval(microtime(true) * 1000) + 6000, '', '')
```

**Comment by i906** [comment]
I encountered this as well. I am using [dg/bypass-finals](https://github.com/dg/bypass-finals) to workaround this.

Below is my Pest test file:

```php
<?php

use App\Handlers\KinesisEventHandler;
use App\Jobs\TestJob;
use Bref\Context\Context;
use Bref\Event\Kinesis\KinesisEvent;
use Bref\Event\Kinesis\KinesisRecord;
use Illuminate\Support\Facades\Bus;
use Mockery\MockInterface;

beforeEach(function () {
    DG\BypassFinals::enable();
});

test('processes kinesis event', function () {
    $record = $this->mock(KinesisRecord::class, function (MockInterface $mock) {
        $contents = file_get_contents('tests/Resources/kinesis/event.json');
        $data = json_decode($contents, true);

        $mock
            ->shouldReceive('getData')
            ->andReturn($data);
    });

    $event = $this->mock(KinesisEvent::class, function (MockInterface $mock) use ($record) {
        $mock
            ->shouldReceive('getRecords')
            ->andReturn([$record]);
    });

    $context = $this->mock(Context::class);

    $handler = app(KinesisEventHandler::class);

    Bus::fake();

    $handler->handleKinesis($event, $context);

    Bus::assertDispatched(function (TestJob $job) {
        return $job->parameter == 1;
    });
});
```

**Comment by marcguyer** [comment]
@mnapoli Cool convenience for creating a simple object as long as you know of its existence... However, it doesn't address the temporal testing issue mentioned above: https://github.com/brefphp/bref/issues/1396#issuecomment-1419584849

**Comment by mnapoli** [comment]
@marcguyer I believe #1398 helps fixing that.

I.e. for scenarios where you want a valid context easily, you use the `fake()` method. If you want to create a custom context, you have to use the constructor. It's a tiny bit less convenient, but I don't want to create a helper method for every scenario, and making the class not final here doesn't seem to make sense since the constructor isn't too complex to use (you have to pass 3 extra `''` parameters… using a mock would not be simpler than that).

**Comment by marcguyer** [comment]
I think I've been unclear, sorry. The `fake` method is only a convenience. It doesn't really help with anything. I'm not suggesting there should be a convenience here. I can call the constructor, no problem. 

I want to test my function's behavior as it approaches timeout. Since the `Context::getRemainingTimeInMillis` method is relative to actual time, then its response is dependent upon the runtime/overhead of the test environment (the "temporal" issue").

I guess my question is this: How would you test the behavior of your function as it approaches timeout? My thought was to mock the response of the method to return a static value, but of course that's not possible. My caveman brain can understand "this will return 20". It's more difficult to conceptualize the test otherwise, imo... I'm sure there're other (better?) ways...
