### ISSUE TITLE
Make bref 2 even lighter by making `async-aws/ssm` optional

### ISSUE THREAD

**Issue by GrahamCampbell** [brefphp/bref#1409]
Move dep to suggest and adjust code to to do a class_exists check and crash out with good DX if someone tries to resolve an env variable via ssm without installing the dep (https://github.com/brefphp/bref/blob/2.0.0-beta11/src/Secrets/Secrets.php#L90).

**Comment by mnapoli** [comment]
@GrahamCampbell I opened https://github.com/brefphp/bref/pull/1425 with another approach, let me know what you think.

**Comment by GrahamCampbell** [comment]
Looks like a reasonable approach to me. Is basically the same approach, just a little more radical. ;)
