### ISSUE TITLE
Bref v2 - can't put the new runtime setting under provider/aws

### ISSUE THREAD

**Issue by oppiansteve** [brefphp/bref#1431]
**Description:**

Previously we could put the `runtime` under the `provider` / `aws` in the serverless yaml file, but now the newly supported values, e.g. `runtime: php-81` can't be put there and shared for all functions; it needs to be under the function directly.

Obviously, this isn't an important issue as the work-around is just to copy the line to each function, but it would be nice if it was supported.

**How to reproduce:**

bref 2.0.0-beta14

**Comment by mnapoli** [comment]
Thanks for the report, fixed with #1431!
