### ISSUE TITLE
PHP pdo_mysql driver seems not enabled in bref v2

### ISSUE THREAD

**Issue by kevincerro** [brefphp/bref#1455]
**Description:**

Bref v2 docker images seems to have pdo_mysql driver disabled
I'm receiving this error 
![Captura de pantalla 2023-03-14 a las 19 23 19](https://user-images.githubusercontent.com/13980708/225101675-04b07250-8772-43dd-b5a0-031859e0bc61.png)
```
In Driver.php line 27:
2023-03-14T18:22:31.635869484Z                          
2023-03-14T18:22:31.635871453Z   could not find driver
```

php -m output
```
bash-4.2# php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
random
readline
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

```
**How to reproduce:**

1. Create docker container using "bref/php-82-fpm-dev" Docker image
![Captura de pantalla 2023-03-14 a las 19 26 27](https://user-images.githubusercontent.com/13980708/225102359-8e242b4b-0f56-4fa8-b14d-82fb2e8143ca.png)

2. Try to run SF project with Bref 2.0.0
![Captura de pantalla 2023-03-14 a las 19 23 19](https://user-images.githubusercontent.com/13980708/225101675-04b07250-8772-43dd-b5a0-031859e0bc61.png)

**Comment by mnapoli** [comment]
Thanks, looking into this right now!

**Comment by mnapoli** [comment]
The php.ini files are messed up in the dev image, I'm working on a fix 👍

**Comment by mnapoli** [comment]
It should be fixed once https://github.com/brefphp/aws-lambda-layers/actions/runs/4419551974 completes 🤞
