### ISSUE TITLE
SqsHandler does not delete successfully processed messages from the queue  

### ISSUE THREAD

**Issue by ievgeniiskliarenko** [brefphp/bref#1461]
**Description:**

After the migration to v2 `SqsHandler` changed its behaviour. When all the messages were processed successfully, it returned an empty array instead of void as it was previously. That led to a problem in communication with AWS. As a result, the successfully processed messages stay in the queue. 

**How to reproduce:**

The bug was found after deploying an app to the test environment. It's hard to reproduce it locally without a fully functional integration test. I made a next temporary "patch"  to confirm an issue: in the build process, after the `composer install`, I replaced `SqsHandler` with the older version, and everything works again.

**Comment by mnapoli** [comment]
@ievgeniiskliarenko thank you for the report and the details, I'm working on it right now!
