### ISSUE TITLE
bref extra sqlsrv not work on bref 2.0

### ISSUE THREAD

**Issue by mickael-fd** [brefphp/bref#1463]
This config work in bref 1.7.24 but not in 2.0

![Capture d'écran 2023-03-15 123248](https://user-images.githubusercontent.com/82392088/225297559-9043ed74-fec2-47dd-a6c5-9617e8872f65.png)

![Capture d'écran 2023-03-01 112858](https://user-images.githubusercontent.com/82392088/225297955-7aab5c73-2b6e-4684-9bf1-678188ba937a.png)

![image](https://user-images.githubusercontent.com/82392088/225298489-0e86fd73-2459-4f03-9b38-1f71eea6ae1a.png)

**Comment by mnapoli** [comment]
Still working on bref-extra extensions to be compatible with v2: https://github.com/brefphp/extra-php-extensions/issues/375

**Comment by mnapoli** [comment]
Released now: https://github.com/brefphp/extra-php-extensions/releases/tag/1.0.0
