### ISSUE TITLE
Exit code 255 in lambda for bref/php-82-fpm V2

### ISSUE THREAD

**Issue by nerdherdme** [brefphp/bref#1465]
Following Dockerfile config works fine with versions before 2, even with php warning of not resolving extensions:

FROM bref/php-82-fpm
COPY --from=bref/extra-imagick-php-82:latest /opt/bref-extra /opt/bref-extra
COPY --from=bref/extra-xlswriter-php-82:latest /opt/bref-extra /opt/bref-extra
COPY --from=bref/extra-gd-php-82:latest /opt/bref/ /opt/bref

COPY . /var/task
CMD ["public/index.php"]

But using the latest docker image or version 2, ends up with lambda error:

RequestId: XXXXX Error: Runtime exited with error: exit status 255
Runtime.ExitError

**Comment by mnapoli** [comment]
We would need logs to understand, but I believe this is caused by the bref-extra extensions not being compatible with v2 right now.

**Comment by nerdherdme** [comment]
Unfortunately AWS is not providing the docker logs on lambda. The only thing I could find from cloudwatchlogs was: runtime exited with error: exit status 255.

I have removed the bref-extra from my docker file, but it did not solve the issue. The only way to fix it was downgrading to bref/php-82-fpm:1.7.23.

**Comment by nerdherdme** [comment]
Yeah, the issue was outdated package in composer.
My bad :(

Thanks for the help

**Comment by mnapoli** [comment]
No worries!
