### ISSUE TITLE
Cannot access FPM 8.2 runtimes > 19

### ISSUE THREAD

**Issue by RobHarveyDev** [brefphp/bref#1470]
I kept getting a permissions issue for the latest PHP FPM 8.2 layer and tried to get the layer via the cli to investigate.

I am running this aws cli command to get the layer:
`aws lambda get-layer-version --layer-name arn:aws:lambda:eu-west-2:209497400698:layer:php-82-fpm --version-number X`

This command works when using 19 as the version, but not any of the version after, 20 - 27.

This is the permissions error message:
An error occurred (AccessDeniedException) when calling the GetLayerVersion operation: User: arn:aws:iam::xxx:user/xxx is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-2:209497400698:layer:php-82-fpm:28 because no resource-based policy allows the lambda:GetLayerVersion action.

I can access the latest 8.1 layer (arn:aws:lambda:eu-west-2:209497400698:layer:php-81-fpm:37)

**Comment by peterabarry** [comment]
Same is true on latest layers on Bref v2. Blocker for us.

**Comment by mnapoli** [comment]
Bref v2 layers are on a different AWS account. That lets us keep releasing Bref v1 layers without mixing up layer numbers (e.g. layer 24 being a v2 layer and layer 25 being a v1 layer).

So for Bref v2 layers, you need to use `534081306603` as the AWS account number.

How can we make this experience better for users upgrading to v2 and avoiding the confusion you went through?

**Comment by RobHarveyDev** [comment]
Thanks, I think the https://runtimes.bref.sh site should be updated to show the correct account for the version you select. Or at least some notice there about the different account for V2

**Comment by RobHarveyDev** [comment]
I see it does change the account when selecting V2 (beta), but shows the V1 account number for V2.0.1 (latest)

**Comment by RobHarveyDev** [comment]
I think I have found the issue for the account number being incorrect for the 2.0.1 version. I have created a pull request with the fix https://github.com/brefphp/runtimes.bref.sh/pull/15

**Comment by mnapoli** [comment]
Thank you for the PR. I also added a note in the upgrade guide: #1472
