### ISSUE TITLE
Deploy to Digitalocean functions

### ISSUE THREAD

**Issue by Lennix** [brefphp/bref#1494]
Digitalocean has its own PaaS offering called functions. They have a native php 8 runtime making it a great fit for bref.

A function is invoked by running its main method. The method stub is
``function main(array $args) : array``

So no request->response, just very basic arrays.

Here's the documentation: https://docs.digitalocean.com/products/functions/

1. Is it in the interest of this project to support PaaS providers other than AWS?
2. How difficult is it to add additional providers to the project?

**Comment by mnapoli** [comment]
Short version: https://twitter.com/matthieunapoli/status/1641386293748695043

Adding support for more providers like Digital Ocean would definitely be great. However, it isn't something achievable without (financial) support from Digital Ocean. The reason for that is that it would be quite a bit of work to implement and then maintain.

**Comment by aknosis** [comment]
I'm curious, what would you want from bref that isn't provided by DO functions? AWS doesn't have native support for PHP so bref fills that gap.

**Comment by mnapoli** [comment]
@aknosis on top of the actual PHP runtimes for Lambda, Bref aims to provide a complete developer experience. Here's what Bref provides on top of just the runtimes:

- infrastructure as code (`serverless.yml`)
- deployment tooling (`serverless deploy` & related commands)
- dev & prod monitoring/debugging commands (tail logs, invoke functions manually, manage async jobs, run CLI commands like DB migrations, etc.)
- documentation/tutorial/examples
- framework integrations (Laravel, Symfony) for one-step deployments
- integration with async job libs, like Symfony Messenger and Laravel Queues

I'm sure I'm forgetting a few details, but that should help get the idea.

**Comment by Lennix** [comment]
> framework integrations (Laravel, Symfony) for one-step deployments

Thats a main point for me. I have a monolith written in symfony and I would like to outsource parts of it. DO Functions looked like a good fit, but without being able to easily use my existing stack, its not interesting.

@mnapoli Thanks for the quick response. I understand your reasoning. Maybe DO frees up some budget if they want to push functions adoption.

**Comment by nicodemuz** [comment]
I also run Symfony on DO. Support for DigitalOcean functions on Bref would be awesome.
