### ISSUE TITLE
The IntlDateFormatter class

### ISSUE THREAD

**Issue by ssmarco** [brefphp/bref#1515]
## The IntlDateFormatter class

https://www.php.net/manual/en/class.intldateformatter.php

Is there a way you can include this extension or add it on the list of optional extensions to add?
Testing in AWS I got this error below:
```
[Emergency] Uncaught Error: Class "IntlDateFormatter" not found
```
Keen to contribute to your project but might need your directions on how to do this one.

Thanks!

**Comment by hmimthiaz** [comment]
Hello @ssmarco 

Bref has the extension intl and it is disabled by default. You should enabled it.

You can read further reading here 

[https://bref.sh/docs/environment/php.html#extensions-installed-but-disabled-by-default](url)

**Comment by ssmarco** [comment]
Thanks @hmimthiaz for your help :+1:
