### ISSUE TITLE
File uploads get's corrupted in local development images

### ISSUE THREAD

**Issue by dannieleadfamly** [brefphp/bref#1537]
**Description:**
File uploads appear to be corrupted using the new Bref 2.X local dev images. Files uploaded through the local dev images doesn't report back the correct mime types when checking with finfo (https://www.php.net/manual/en/class.finfo.php).

All seems to point to the file being corrupted, as attempts at extracting it out of the container and opening it on the host system also failed.

No matter what file you upload, `application/octet-stream` is always the one that is being reported back.

**How to reproduce:**
Created a small repo that makes it easy to reproduce: https://github.com/dannieleadfamly/bref-local-dev-file-upload-issue

**Comment by mnapoli** [comment]
This might duplicate #1524 too? Or is it different?

**Comment by dannieleadfamly** [comment]
@mnapoli Can i test with the latest release of the local dev image? Then i can confirm if it covers both 👍

**Comment by mnapoli** [comment]
I'm pushing updated images, unfortunately it's hard to test without building everything.

**Comment by dannieleadfamly** [comment]
@mnapoli Alrighty. I see. Looking at the PR it looks to mostly concern the response of existing binary files. However, in this case it's concerning files that are uploaded through multipart form posts. So the issue may be different.

**Comment by mnapoli** [comment]
Oh ok no good point, that's a different issue indeed! I'm thinking these lines need to be edited so that if the request body contains binary data, then the Lambda event must use base64 encoding:

https://github.com/brefphp/local-api-gateway/blob/091bc036c6bee766550db30dbb7a6af5266c949f/src/apiGateway.ts#L46-L47

**Comment by dannieleadfamly** [comment]
@mnapoli Thank you for the hint at potential cause. I'll try and work on a MR this Thursday to resolve the issue if no other have looked at it before 👍

**Comment by danniehansen** [comment]
Found the problem. Created a PR. Very unsure of the implementation. I feel like it's hard to guess when we should and shouldn't send base64. As I'm not sure we can reliably detect binary non-UTF8 data in the request body. I may be wrong.
