### ISSUE TITLE
`WebsocketEvent::getRegion` is incompatible with custom domain names.

### ISSUE THREAD

**Issue by Shkeats** [brefphp/bref#1593]
**Description:**

`Bref\Event\ApiGateway\WebsocketEvent` has a method `getRegion()` that should return the current AWS region e.g. `eu-west-1` 

This is implemented by parsing it out of the `domainName` from the event `requestContext`. 

This makes sense only in the case that default AWS provided API gateway domains are used. When you set up your own domain for the websocket API you end up getting a segment of that domain returned as your region. 

For example if you have a domain configured of `websocket.example.org` the AWS region returned by this method would be `org` which isn't correct.

Hope that makes sense, it's a fairly straightforward one but happy to provide more context if needed. I'm not sure if it's a good solution but the current region is available in Lambda via an environment variable. 

The below resolves it for me:

<img width="433" alt="image" src="https://github.com/brefphp/bref/assets/2048674/df902927-9832-453a-91fe-21762f82d48b">

**Comment by Shkeats** [comment]
PR added with this change https://github.com/brefphp/bref/pull/1594

**Comment by mnapoli** [comment]
Thanks for the PR!
