### ISSUE TITLE
Separate Serverless .yml files

### ISSUE THREAD

**Issue by AtteR** [brefphp/bref#1674]
Hello,

I noticed that the `serverless bref:cli` command now reads always serverless.yml file, but in my projects I have for example serverless-staging.yml and serverless-production.yml. Normally you could select any of these with `serverless --profile=<.yml file>`, but I did not figure out if this is supported and docs did not mention it.

In the docs there is mention of --stage but not sure what this does.

So, please add --profile flag to the `serverless bref:cli` command.

Thank you!

**Comment by mnapoli** [comment]
`serverless bref:cli` is a `serverless` command, so all the options you usually use with other commands (like `serverless deploy`) should work.

Have you tried that?

**Comment by AtteR** [comment]
Hmm, yes sorry, seems I was using wrong command. :face_with_spiral_eyes: It is --config not --profile, should have looked today first with fresh eyes before opening issue.

Thanks! I will close this.
