### ISSUE TITLE
Mistake in custom domains documentation

### ISSUE THREAD

**Issue by Adesin-fr** [brefphp/bref#1687]
In the page main/src/pages/docs/use-cases/http/custom-domains.mdx

There might be a mistake : If I create the certificate on us-east-1, I can't find it when I create the API Gateway on my app region.
To find the certificate, I must either create the API gateway to us-east-1, or create the certificate on the app regipon.

**Comment by mnapoli** [comment]
For REST APIs (API Gateway v1), you must create it in `us-east-1`.

For HTTP APIs (API Gateway v2), you must create it in your region.

Bref switched to v2 recently, that's maybe why the docs still mention us-east-1. Happy to merge a PR that updates this.
