### ISSUE TITLE
Stop truncating multi-value headers

### ISSUE THREAD

**Issue by timkelty** [brefphp/bref#1691]
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

> Format 2.0 doesn't have multiValueHeaders or multiValueQueryStringParameters fields. Duplicate headers are combined with commas and included in the headers field

As API Gateway 2.0 doesn't support `multiValueHeaders` – Bref takes only the last value.

It seems like a better solution to not do anything and allow APIG to join them with a comma – at least that way there isn't any data loss, and your app can adjust to get the values.

Related: https://github.com/brefphp/bref/issues/818

**Comment by mnapoli** [comment]
Hi, I'm not sure I understand everything.

Could you clarify with:

- what you expect to happen
- what happens instead

Thanks!

**Comment by timkelty** [comment]
### What currently happens
Given a response with multi-value headers (2 unique headers with the same name), Bref will only keep the last header: https://github.com/brefphp/bref/blob/master/src/Event/Http/HttpResponse.php#L37

Eg, given

```
x-foo: bar
x-foo: baz
```

The APIG response will be constructed with only `x-foo: baz`

### What I expect to happen
I expect headers with duplicate names to be joined with a `,`, which is API Gateway v2's default behavior:

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

> Format 2.0 doesn't have multiValueHeaders or multiValueQueryStringParameters fields. Duplicate headers are combined with commas and included in the headers field

So, it seems like Bref shouldn't do any special handling for these headers, and instead rely on APIG's default handling.

**Comment by berenddeboer** [comment]
i'm having a similar, but not the same issue with CloudFront + function urls. This is the request that is sent:

```
POST https://example.com/media-library?
  media_library_opener_id=media_library.opener.editor&
  media_library_allowed_types%5B0%5D=image&
  media_library_selected_type=image&
  media_library_remaining=1&
  media_library_opener_parameters%5Bfilter_format_id%5D=basic_html&
  hash=Y0GzprGKj6n2Vs7_sMumYICU-hNpfhtmFiOnEdVJnuY&
  _wrapper_format=drupal_modal&
  ajax_form=1&
  _wrapper_format=drupal_ajax
```

So duplicated `_wrapper_format`.

This causes this crash: `Symfony\Component\HttpFoundation\Exception\BadRequestException: Input value "_wrapper_format" contains a non-scalar value. in Symfony\Component\HttpFoundation\InputBag->get() (line 38 of /var/task/vendor/symfony/http-foundation/InputBag.php).`

Am I right to think that this fix is the cause of my error? So I get "drupal_model,drupal_jax" where the thing just expects "drupal_ajax" (the last one)?

If so it seems bref would almost need to know how to handle this right? Some backends support the comma, some don't.

**Comment by mnapoli** [comment]
This issue is about headers but your example is about query strings, I don't think these are related?

If they aren't, can you open a separate issue? (if they are, let's continue the discussion here)
