### ISSUE TITLE
OPENSSL_3.3.0' not found (required by /opt/lib/libssl.so.3)

### ISSUE THREAD

**Issue by pra-cloud** [brefphp/bref#1790]
Error:- 

![error-bref](https://github.com/brefphp/bref/assets/64471391/bc61b1fe-2200-4a65-9388-43e2b925eb3a)

**composer.json**

"require": {
        "php": "^8.2",
        "bref/bref": "^2.1.15",
        "bref/extra-php-extensions": "^1.4.2",
        "bref/laravel-bridge": "^2.1",
        
**Dockerfile**

FROM bref/php-82-fpm

COPY --from=bref/extra-mongodb-php-82:1 /opt /opt
COPY --from=bref/extra-imagick-php-82:1 /opt /opt

COPY . /var/task

CMD ["public/index.php"]

**Comment by salmanarshad321** [comment]
getting the same issue :\

**Comment by siddiquiazam** [comment]
Getting the same error. @mnapoli

**Comment by mnapoli** [comment]
Do you think it's related to one extension? Or the fact that it's running in Docker? What happens if you remove the extensions?

I tried the latest Bref version and it worked for me, but did not use Docker nor extensions.

**Comment by pra-cloud** [comment]
@mnapoli it was working fine with the same configuration but from today its stopped working and throwing this error , i am trying some hit and try from my side .  In the meantime, if you have any suggestions or possible solutions that you think might be helpful, I would greatly appreciate your input.

**Comment by pra-cloud** [comment]
Hey i got the issue after commented these two lines in dockerfile for extension then its working fine , but without those extension's my app is not working properly.

:- **Dockerfile**

FROM bref/php-82-fpm

#COPY --from=bref/extra-mongodb-php-82:1 /opt /opt
#COPY --from=bref/extra-imagick-php-82:1 /opt /opt

COPY . /var/task

CMD ["public/index.php"]

**Comment by mnapoli** [comment]
Which extension is causing issues? Both of them?

**Comment by siddiquiazam** [comment]
I checked this issue on my end and tried commenting the extensions mentioned by @pra-cloud 

The imagick extension was causing the issue

`COPY --from=bref/extra-imagick-php-82:1 /opt /opt`

**Comment by pra-cloud** [comment]
@mnapoli yes , @siddiquiazam  is right imagick is occurring issue. Mongodb is running fine.

**Comment by mnapoli** [comment]
Please try the latest version of the bref extra extensions.

**Comment by siddiquiazam** [comment]
Its working thanks @mnapoli
