### ISSUE TITLE
NOTICE since upgrading to v2

### ISSUE THREAD

**Issue by eroltoker** [brefphp/bref#1793]
**Description:**
I'm currently upgrading to brefv2 to get access to the php-fpm-83 image and everything is working fine.  However, I started seeing the following in the lambda logs

[23-Apr-2024 10:25:30] NOTICE: [pool default] 'user' directive is ignored when FPM is not running as root
[23-Apr-2024 10:25:30] NOTICE: fpm is running, pid 10
[23-Apr-2024 10:25:30] NOTICE: ready to handle connections

Here is my yml:

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
functions:
    api:
        handler: lambdaHandler.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        memorySize: 256
        runtime: php-83-fpm
        layers:
#            - ${bref:layer.php-83-fpm}
            - ${bref-extra:redis-php-83}
        events:
            -   httpApi: '*'

Am I doing something wrong?

**Comment by mnapoli** [comment]
This is normal.
