### ISSUE TITLE
PDO_SQLITE version

### ISSUE THREAD

**Issue by kevincerro** [brefphp/bref#1833]
Its possible to upgrade pdo_sqlite version in bref docker images?

Seems that installed version of pdo_sqlite in bref docker images are too old (3.7.17)

I'm encountering following error with phpunit tests
```
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near "(": syntax error
Executing tests from my machine 
```

Trying in my host machine works because I have a more recent version of pdo_sqlite (3.46.0)

### Sample dockerfile
```
FROM composer:2 AS composer
FROM bref/php-83-fpm-dev
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Install unzip and git (required by composer)
RUN yum install -y unzip git

WORKDIR /var/task
```

### Command to print pdo_sqlite version
`php -r 'echo "SQLite version: " . SQLite3::version()["versionString"] . PHP_EOL;'`

**Comment by kevincerro** [comment]
Tryed to upgrade pdo_sqlite on my own without success.
I cannot find where is installed in bref source Dockerfiles

**Comment by kevincerro** [comment]
With AL2023 this will be solved because provides a more recent version of sqlite-devel

https://github.com/brefphp/aws-lambda-layers/pull/122

**Comment by mnapoli** [comment]
Yes AL2023 would come with dependency updates, however this will be a major version change for Bref (or at least an opt-in change).

Having sqlite work today (with current layers) is definitely something we want. It should work, it's interesting that you're facing issues 🤔 Do you know what specific query causes the problem?
