### ISSUE TITLE
Add Support for us-gov-west-1 / us-gov-east-1 regions

### ISSUE THREAD

**Issue by michaelaguiar** [brefphp/bref#1887]
AWS GovCloud regions please!

**Comment by Adesin-fr** [comment]
Hi, 
This probably won't help you, but as far as I know, supported regions are those supported by Serverless framework and AWS Lambda. 
If both those doesn't support the regions you're needed, Bref won't be able to help you (bref is in fact an abstraction layer for serverless framework...)

**Comment by michaelaguiar** [comment]
Thanks for the info. Yea I found that I can deploy a container instead since the runtimes aren't in the unsupported region.
