### ISSUE TITLE
Add support for the new multiValueHeaders (which then allows multiple set-cookie headers)

### ISSUE THREAD

**Issue by gregmsanderson** [brefphp/bref#213]
While investigating #211 I found that only one cookie appears to be set in the response. When I run Laravel locally, it sends two. So one of them is getting lost. I think I know why.

For many years there was a known issue with APIG/Lambda where you could only send one cookie, since you could only send one _set-cookie_ header. People came up with awkward hacks like sending multiple cookies in one, or changing the case like _Set-Cookie_. But last year, AWS finally added official support for returning multiple cookies in a single response. Hurrah. See https://forums.aws.amazon.com/ann.jspa?annID=6185

I had a look at what Bref currently does when building the LambdaResponse and I _believe_ it is this key bit where it formats the php-fpm response:

```
public function toApiGatewayFormat(): array
    {
        // The headers must be a JSON object. If the PHP array is empty it is
        // serialized to `[]` (we want `{}`) so we force it to an empty object.
        $headers = empty($this->headers) ? new \stdClass : $this->headers;

        // This is the format required by the AWS_PROXY lambda integration
        // See https://stackoverflow.com/questions/43708017/aws-lambda-api-gateway-error-malformed-lambda-proxy-response
        return [
            'isBase64Encoded' => false,
            'statusCode' => $this->statusCode,
            'headers' => $headers,
            'body' => $this->body,
        ];
    }
```

The new response (changed since the referenced stackoverflow link, as that was from 2017) has gained a 'multiValueHeaders' :) See: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format

What's neat is it seems the _multiValueHeaders_ can contain single value ones too:

> The multiValueHeaders key can contain multi-value headers as well as single-value headers. You can use the multiValueHeaders key to specify all of your extra headers, including any single-value ones.

So I'm thinking if that _multiValueHeaders_ was used, it _may_ be that Laravel is returning multiple set-cookie headers but currently only _one_ is returned because they each are called set-cookie and so they overwrite each other.

(Note, despite finding this, I currently haven't closed #211 since there still may be a particular issue with a cookie when used as a Laravel session driver, but I _suspect_ adding _this_ support will have the neat side-effect of fixing that too. So you may want to close that, and keep _this_ one instead as this will add potentially other benefits too)

**Comment by mnapoli** [comment]
Good point, thanks for all the details!

That sounds like something that's definitely worth adding! I'll go ahead and close #211 then as this issue here sounds like the real blocker (and if there are other issues discovered along the way we'll open new issues).

**Comment by mnapoli** [comment]
What we need to do first is add support to multi-headers in Hoa/FastCGI.

@atrope started this work in https://github.com/hoaproject/Fastcgi/pull/28

**Comment by roenschg** [comment]
The implementation does not seem to be correct. The "headers" key must be set all the time.

The documentation explains that the output format must look like this:
`{
    "isBase64Encoded": true|false,
    "statusCode": httpStatusCode,
    "headers": { "headerName": "headerValue", ... },
    "multiValueHeaders": { "headerName": ["headerValue", "headerValue2", ...], ... },
    "body": "..."
}`

See https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format and https://aws.amazon.com/premiumsupport/knowledge-center/malformed-502-api-gateway/

**Comment by mnapoli** [comment]
@roenschg thank you for the report, that is interesting. AFAIK nobody is reporting errors, do you see any error related to that?

If you do, could you open a separate issue? We might want to fix this then.

**Comment by mnapoli** [comment]
Multi-value headers are now supported, let me know if something is missing.
