### ISSUE TITLE
Windows 10 get bootstrap: permission denied for sam local

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [brefphp/bref#242]
Getting below error when testing locally on a windows system.
Error: fork/exec /opt/bootstrap: permission denied

**Comment by mnapoli** [comment]
Please provide more details, for example the runtimes, the code you actually wrote, the commands you are running, template.yaml, etc.

**Comment by ashish-dirkmedia-de** [comment]
when sam deployed this package it works from api gateway.
But gives error fork/exec /opt/bootstrap: permission denied when "sam local start-api"

Used the simplest created by the vendor\bin\bref init in windows system for http application. 
step 1 => composer require mnapoli/bref

template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Globals:
    Function:
        Environment:
            Variables:
                # Laravel environment variables
                APP_STORAGE: '/tmp'
				
Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'my-function'
            Description: ''
            CodeUri: .
            Handler: index.php
            Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-72-fpm:1'
            Events:
                # The function will match all HTTP URLs
                HttpRoot:
                    Type: Api
                    Properties:
                        Path: /
                        Method: ANY
                HttpSubPaths:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY

# Outputs show up in the CloudFormation dashboard
Outputs:
    DemoHttpApi:
        Description: 'URL of our function in the *Prod* environment'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'

index.php
<?php

echo 'Hello world!'
	
?>

**Comment by ashish-dirkmedia-de** [comment]
Work env. (Please help)
aws --version
aws-cli/1.16.103 Python/3.6.0 Windows/10 botocore/1.12.93

sam --version
SAM CLI, version 0.11.0

Docker desktop Version 2.0.0.2

**Comment by mnapoli** [comment]
It's really hard for me to help here unfortunately, I don't have Windows to do any kind of test.

Maybe you could post an issue at https://github.com/awslabs/aws-sam-cli to check whether SAM actually works correctly with Windows, especially with custom layers. Maybe they can help?

**Comment by nealio82** [comment]
Can you set file permissions in Windows? A few times I've had to `chmod +x` the `bootstrap` file on my Mac because of the same thing. I understand Windows uses ACL rather than the *nix file permissions system but it does sound similar.

**Comment by mnapoli** [comment]
@nealio82 but here there should be no bootstrap file written by @ashish-dirkmedia-de if I understand correctly. They are only using the FPM layer as-is.

@ashish-dirkmedia-de can you confirm that you have not created a `bootstrap` file?

Oh or maybe it is #134 -> Laravel's bootstrap directory is creating problems on Windows specifically?

**Comment by ashish-dirkmedia-de** [comment]
No I dont have any bootstrap file. Not even laravel. Just mnapoli/bref.
It works when deployed.

**Comment by jsamouh** [comment]
same error for me on Windows 10 with docker Hyper-V
sam local invoke
Error: fork/exec /opt/bootstrap: permission denied
I think it comes from permission problem on bootstrap (called in the php layer)

**Comment by mnapoli** [comment]
Have you looked or asked in https://github.com/awslabs/aws-sam-cli if Windows is supported (as well as for lambdas using custom runtimes)? From what I could tell at the time it was, but maybe it's best to make sure.

**Comment by ashish-dirkmedia-de** [comment]
I have posted the issue https://github.com/awslabs/aws-sam-cli/issues/1014. Hope they reply with solution

**Comment by ashish-dirkmedia-de** [comment]
I more issue hope you can help me in that. Should be some thing small. Not sure why but now the laravel output is showing many times in cloudwatch with timeout. It is calling the same controller many times and goes to timeout and shows the output on cloudwatch

**Comment by ashish-dirkmedia-de** [comment]
I frequently get -> related to hoa/socket for accessing aws services s3, cognito
/var/task/vendor/hoa/socket/Connection/Connection.php(197): Hoa\Stream\Stream->__construct('unix:///tmp/.br...', NULL)
Is it a know issue. Do you have a solution.

**Comment by ashish-dirkmedia-de** [comment]
> 
> 
> Can you set file permissions in Windows? A few times I've had to `chmod +x` the `bootstrap` file on my Mac because of the same thing. I understand Windows uses ACL rather than the *nix file permissions system but it does sound similar.

Can you describe how you did the changed the permission for the bootstrap. Had you given in the downloaded layer.

**Comment by mnapoli** [comment]
I don't understand either, `bootstrap` is in the layer so it shouldn't visible to you.

**Comment by angrybrad** [comment]
Running into this as well. :(

Browsing through https://github.com/awslabs/aws-sam-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+windows it looks as though there are people successfully running AWS SAM on Windows locally.

Not running Laravel, but a custom Yii 2 app.  Happy to do any sort of debugging necessary to get to the bottom with some guidance.

**Comment by mnapoli** [comment]
Closing since we have switched to Serverless.
