### ISSUE TITLE
Laravel: mix() does not work

### ISSUE THREAD

**Issue by viezel** [brefphp/bref#255]
When using Laravel Mix in frontend views, the output path is incorrect.

```blade
<link rel="stylesheet" href="{{ mix('css/app.css') }}">
```

becomes:

```html
<link rel="stylesheet" href="/css/app.css">
```

but should become:

```html
<link rel="stylesheet" href="/var/task/public/css/app.css">
```

Of course a quick fix is to use `public_path('css/app.css')` but then the cache busting feature of Laravel Mix is gone. 

Or maybe I dont understand how to read assets in html using Bref?

**Comment by mnapoli** [comment]
I don't see how `/var/task/public/css/app.css` is a valid URL for a CSS file, because `/var/task/public/` is a directory on the server (not a URL).

Am I missing something on how Mix works?

**Comment by viezel** [comment]
you are right. I found out that non of the files in `/public` folder was accessable. Hence, images, svg, css, js etc.  So is the support for the public facing files missing? How do I specify what is public readable when I do not have a nginx?
I can tell that it is the same with your laravel-demo app that cannot find `favicon.ico`.

**Comment by viezel** [comment]
`public_path('somefile.ext')` is used a lot by laravel apps. It need to point to public facing folder

**Comment by mnapoli** [comment]
Ah OK that makes more sense.

As mentioned in https://bref.sh/docs/runtimes/http.html#assets there is no documentation yet for all of this (as you can see there is still a lot to document ^^).

Fortunately Bref is no different from any other Lambda application, there are examples online on how to serve assets using (for example) AWS S3. @nealio82 even did a presentation on how to do this with Symfony, maybe he can provide the URL to the video here.

To upload to S3 and have Laravel Mix work with that it seems [there are resources online](https://www.google.com/search?q=laravel+mix+aws+s3&oq=laravel+mix+aws+s3&aqs=chrome..69i57j69i64.3575j0j4&sourceid=chrome&ie=UTF-8) to do this.

Here is also a bit of documentation on how to put a custom domain for assets stored on S3: https://bref.sh/docs/environment/custom-domains.html#custom-domains-for-static-websites-on-s3 I highly recommend you put them on a separate domain from your website to simplify the whole setup (e.g. `assets.yourwebsite.com`).

**Comment by nealio82** [comment]
Link to my Bref presentation: https://skillsmatter.com/skillscasts/13519-running-symfony-on-aws-lambda. At about 21:30 I start talking about taking a fully-featured website (with assets, session storage, file uploads) and converting it to use Bref. The example is using Symfony but that's just an implementation detail - the concepts behind it are the same.

I haven't tried it, but this walkthrough seems quite comprehensive on using `mix()` with a CDN: https://medium.com/@avosalmon/cache-busting-using-laravel-mix-and-cloudfront-s3-eb222b569f88

**Comment by viezel** [comment]
Great guys. I’ll try it out 👍🏻

**Comment by viezel** [comment]
This did it: https://medium.com/@avosalmon/cache-busting-using-laravel-mix-and-cloudfront-s3-eb222b569f88

Ill try to make a Gitlab CI pipeline yaml file and submit a PR to the docs on this matter.

**Comment by nealio82** [comment]
@mnapoli can this be closed?

**Comment by mnapoli** [comment]
:+1:
