### ISSUE TITLE
Bref cli and invoke: read the region from ~/.aws/config

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#259]
Bref cli and invoke do not read the region from `~/.aws/config`. This leads to confusion because the `aws` and `sam` CLI tools have different behaviors.

The `vendor/bin/bref` CLI should pick up the region with the same logic as the other tools.

**Comment by akrabat** [comment]
As more than one profile can be stored in `~/aws/config` (`default` being the default), the cli should support `--profile` to select which profile to use in the same way that the `aws` CLI tool does.

**Comment by mnapoli** [comment]
A quick note: the serverless framework has another approach here: the region is stored in the configuration file (`serverless.yml` which is the equivalent of `template.yaml`).

I like this as this is even more predictable.

**Comment by mnapoli** [comment]
We don't use SAM anymore, we can close this.
