### ISSUE TITLE
Increase the default timeout for console applications

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#261]
By default lambdas timeout after 3 seconds.

For the console layer this isn't much. We could set it for example to 30 seconds, just like [in HTTP applications](https://github.com/mnapoli/bref/blob/a22adc8002ac34c2573c1ee070961f6a8fea6f6a/template/http/template.yaml#L13).

The file to edit would be [`template/console/template.yaml`](https://github.com/mnapoli/bref/blob/master/template/console/template.yaml).

**Comment by mnapoli** [comment]
As documented in https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/ the default is 6 seconds with `serverless.yml`.

The file to edit has changed, it is now https://github.com/brefphp/bref/blob/master/template/console/serverless.yml

**Comment by Luitame** [comment]
Hey @mnapoli do you want to set this timeout for the specific function or should it setted on the provider?
