### ISSUE TITLE
Document `sam local` limitations

### ISSUE THREAD

**Issue by kaihendry** [brefphp/bref#300]
I think I am following the documentation using `sam local start-api` with a `export AWS_PROFILE=$mycreds` setup in advance with my credentials.

https://bref.sh/docs/local-development.html#http-applications

However I've had two problems:
* ssm env variables not exported, _{{resolve:ssm:MYSQL_HOST:1}}_
* unable to IAM access my database

https://media.dev.unee-t.com/2019-04-08/sam-local.mp4
https://github.com/unee-t/enterprise/tree/youtube

Maybe I am missing something? Btw `sam local start-api --profile $mycreds` doesn't appear to work either.

**Comment by mnapoli** [comment]
Right that's unfortunately correct. `sam local` supports very little things actually, I'm discovering that along the way.

I've also found that the functions run using the local user permissions (i.e. me) and not what's defined in `template.yaml`: that means if I can access a resource with my CLI credentials, the function will be able to access it too

We should add a warning to the documentation.

**Comment by kaihendry** [comment]
Oh, how did you confirm it was running with your credentials? I was unable to connect to the database via IAM so I assumed it wasn't running under any CLI credentials. 

I wonder what [AWS SAM issues](https://github.com/awslabs/aws-sam-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22local+start-api%22) are worth tracking for this.

**Comment by mnapoli** [comment]
Well now I am starting to doubt, but I could swear I am able to query e.g. DynamoDB locally without having set up any permissions (often the thing is that I deploy and I find I am lacking permissions in my `template.yaml`).

**Comment by mnapoli** [comment]
Wait @kaihendry this is actually documented: https://bref.sh/docs/environment/variables.html#local-development Does that cover your problem?

**Comment by kaihendry** [comment]
Pity it can't just grab the Env variables from my AWS_PROFILE's parameter store?

I'm still very confused how or if my ~/.aws credentials are passed into the `local start-api`. Are you suggesting I use **AWS_ACCESS_KEY_ID** and **AWS_SECRET_ACCESS_KEY** instead?

**Comment by mnapoli** [comment]
That might be worth asking directly on the SAM repository to be honest. They will be able to explain clearly how things work. I'm just speculating and my experience so far has always been "it works" so I didn't look further into this.

**Comment by nealio82** [comment]
AFAICT `sam local start-api` will read your `~/.aws/credentials` file. You can test it by setting your default region in your profile and trying to invoke `sam local` using a layer in a different region (you'll get errors). However it might just be that only a sub-set of variables defined in your credentials file are actually read?

**Comment by kaihendry** [comment]
Hoping someone can do the research and fill in the gaps: https://stackoverflow.com/questions/55615241/can-one-develop-locally-with-aws-sam-using-a-role

**Comment by kaihendry** [comment]
I think the relevant AWS SAM issue is: https://github.com/awslabs/serverless-application-model/issues/865

The current behaviour is that $AWS_PROFILE is assumed in `sam local start-api` **instead of the lambda role**, which one might expect.

<img src="https://media.dev.unee-t.com/2019-04-15/get-caller-identity.png">


```
<?php
require './vendor/autoload.php';
use Aws\Sts\StsClient;

$stsClient = StsClient::factory(array(
  'region' => 'ap-southeast-1',
  'version' => 'latest'
));
$result = $stsClient->getCallerIdentity([]);
print_r($result);
?>
```

I guess one possible workaround is to assume role in the code?

**Comment by mnapoli** [comment]
@kaihendry this issue seems to be related to yours as well: https://github.com/awslabs/aws-sam-cli/issues/332

**Comment by mnapoli** [comment]
Closing since this is related to `sam local`.
