### ISSUE TITLE
Use bref inside a docker container

### ISSUE THREAD

**Issue by matiux** [brefphp/bref#303]
I trying to use bref inside a docker project. Everything works fine except when I try to run the handler locally. I have docker inside my docker container, in fact I can see the containers list inside the container but running this command

```
sam local invoke -t template.yaml -e event.json MyFunction
```

I get this error:

```
019-04-11 12:35:19 Found credentials in shared credentials file: ~/.aws/credentials
2019-04-11 12:35:19 Invoking index.php (provided)
2019-04-11 12:35:19 arn:aws:lambda:eu-west-3:209497400698:layer:php-73:3 is already cached. Skipping download
2019-04-11 12:35:19 Requested to skip pulling images ...

2019-04-11 12:35:19 Mounting /var/www/app as /var/task:ro inside runtime container
Could not open input file: /var/task/index.php
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72  Init Duration: 12.02 ms Duration: 0.00 ms       Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 12 MB
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Error: Runtime exited without providing a reason"
}
```
I think that the main error is
```
Could not open input file: /var/task/index.php
```

Obviously the index.php file exists in my root directory

**Comment by matiux** [comment]
I tried to run sam `sam local invoke -t template.yaml -e event.json MyFunction` outside the project container and works. So i'm wondering how i can make it work inside too

**Comment by bubba-h57** [comment]
Probably a permissions issue on the `index.php` file. Anytime I ran into similar issues, that was the root. Typically, the file in question needed executable permissions. Occasionally, the issue was that the file had `-rw-------` permissions. In this case, only the creator can access it and the process running in the docker file is not the creator.

**Comment by matiux** [comment]
Inside a container i work with a non root user
`-rw-r--r--    1 user   user       371 Apr  5 10:11 index.php`

With executable permission the error is the same:
`-rwxr-xr-x    1 user   user       371 Apr  5 10:11 index.php`

Anche con permessi completi
`-rwxrwxrwx    1 user   user       371 Apr  5 10:11 index.php`

**Comment by mnapoli** [comment]
Maybe this is an issue that may be better asked in the [SAM repository](https://github.com/awslabs/aws-sam-cli) as this is SAM running here, not really Bref (and the error doesn't seem to be about the layers). I've done a quick search and I've found: https://github.com/awslabs/aws-sam-cli/issues/181 so it might not be supported in SAM.

**Comment by deleugpn** [comment]
From your description it seems you're getting volume errors. I've had that  before. When you run docker inside docker with volume, you need to mount volume using the original host path, not the intermediate docker filesystem.
