### ISSUE TITLE
[Documentation] Sidebar > Active page link looks like a normal link

### ISSUE THREAD

**Issue by FredericMartinez** [brefphp/bref#315]
I want to see (on the left) where I'am on the documentation.
The active look (bold/underlined for menu links is missing

**Comment by mnapoli** [comment]
If anyone wants to contribute here you can have a look at how it is done in Couscous.

Here is a page example: http://couscous.io/docs/templates.html

That page has a `current_menu` variable set: https://github.com/CouscousPHP/Couscous/blob/53fe638587095c5262b71ec8fe3cf2e7ed692c85/docs/templates.md#L1-L3

This variable is used when building the menu: https://github.com/CouscousPHP/Couscous/blob/53fe638587095c5262b71ec8fe3cf2e7ed692c85/website/default.twig#L69
