### ISSUE TITLE
Enhancement: Output logs from console layers

### ISSUE THREAD

**Issue by MaxGiting** [brefphp/bref#347]
It would be useful if logging could be output from console layers to CloudWatch.

My use case was setting up Events in CloudWatch to trigger commands. So some feedback into CloudWatch would be useful.

@mnapoli has suggested looking into the below line to enable this functionality.
https://github.com/brefphp/bref/blob/3450616d2535b13ff086124a6cca5a9000252902/runtime/console/bootstrap#L31

**Comment by mnapoli** [comment]
:+1:

As you mentioned this feature *may be* as simple as adding `echo $output` in the bootstrap file. Hopefully I'm not missing anything :)

Then `bref cli ...` should display the output, but the output should also be sent to CloudWatch.

**Comment by MaxGiting** [comment]
This has been fixed in #349
