### ISSUE TITLE
Cannot click link in docs

### ISSUE THREAD

**Issue by nathanczachur** [brefphp/bref#362]
In the documentation here https://bref.sh/docs/installation.html#aws-tooling (File https://github.com/brefphp/bref/blob/master/docs/installation.md#aws-tooling), you cannot click the anchor text "or by using environment variables".

It looks like it needs some padding below as the "Region" element is above it.

Happens in Chrome 75.0.3770.100 on macOS Mojave 10.14.5.

**Comment by mnapoli** [comment]
Thank you, I have pushed a fix. The link is clickable now (and all those invisible margins are much lower now, they should cause less problems).
