### ISSUE TITLE
How to log info to CloudWatch from Laravel?

### ISSUE THREAD

**Issue by harmenjanssen** [brefphp/bref#366]
I've tried a lot of different things, but I simply cannot seem to have my logs end up in CloudWatch.

I've created an artisan function as described in https://bref.sh/docs/frameworks/laravel.html.

Then in the command I run the following:

```php
$log = new \Monolog\Logger('name');
$log->pushHandler(new \Monolog\Handler\StreamHandler('php://stderr'));
$log->info('hello!');
```
(I also tried just `echo`ing)

I'm using the [Serverless framework](https://serverless.com/) and when I invoke my function like this:

```
$ serverless invoke -f artisan --data '{"cli": "app:foo"}'
```

I do indeed get the output:

```
{
    "exitCode": 0,
    "output": "[2019-07-04 05:50:36] name.INFO: hello! [] []"
}
```

But when I ask for the logs, nothing shows up:

```
$ serverless logs -f artisan
```

This shows only the `START RequestId .... END RequestId` lines, with none of my logs in between. 

Is my assumption incorrect that the log should end up there, or am I simply doing it wrong?

**Comment by mnapoli** [comment]
Hi, this is related to #347 and #349.

I haven't released the fix yet (both in Bref or new layers).

**Comment by harmenjanssen** [comment]
Ah, good to know a solution is on the horizon, great! 

I will keep an eye out for the new bref release and try again.
Thanks!

**Comment by harmenjanssen** [comment]
Ah, good to know a solution is on the horizon, great! 

I will keep an eye out for the new bref release and try again.
Thanks!
