### ISSUE TITLE
Google Search mobile issue

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#370]
I have been notified by the Google Search Console of 2 issues related to mobile accessibility:

- font size too small: https://support.google.com/webmasters/answer/9063469#small_font_size
- touch elements too close: https://support.google.com/webmasters/answer/9063469#touch_elements_too_close

The URL mentioned by the console is https://bref.sh/docs/deploy.html But I guess this applies to the whole documentation?

I am opening this issue to track this. Help is welcome.

I guess a first step is to understand why these issues are reported: which part of the text is too small? Is there a minimum font size required? Which elements are too close to click?

When we know then we can fix those issues (probably by changing the CSS).

Note that when opening the page in the "simulator" there doesn't seem to be any issue: https://search.google.com/test/mobile-friendly?hl=fr&id=0whe-12eC2ANuAqM2mRkYA

**Comment by nealio82** [comment]
I went to a talk _ages_ ago about PWAs and how Google determines quality on mobile devices. I think the lighthouse tool might help point you in the right direction https://developers.google.com/web/tools/lighthouse/

**Comment by nealio82** [comment]
although, having quickly run an audit in lighthouse I can't see anything about font size or touch elements (there are other suggestions, however)

**Comment by nealio82** [comment]
I used lighthouse to check (among other URLs) https://bref.sh/docs/environment/php.html, and came up with the following result referencing the list of extensions and saying they overlap each other.

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/1086726/62080671-05badd80-b249-11e9-9319-26d76710ba97.png">

**Comment by mnapoli** [comment]
> (@mnapoli maybe add a 'good first issue' label onto this..?)

:+1: added the label.
