### ISSUE TITLE
bref cli fails with quoted arguments

### ISSUE THREAD

**Issue by shadowhand** [brefphp/bref#379]
```
bref cli doctrine-cli-develop -- dbal:run-sql 'select * from events'

  Too many arguments, expected arguments "command" "sql".

dbal:run-sql [--depth DEPTH] [--force-fetch] [--] <sql>
```

This happens no matter where I place the `--` and whether or not I use single quotes or double quotes.

**Comment by mnapoli** [comment]
Thanks for the report.

Dropping some debugging things here in case that helps in the future: here is where the CLI script is executed inside the lambda: https://github.com/brefphp/bref/blob/1f56dc9346a92328325a70b1eeeb8aa35c06e24a/runtime/console/bootstrap#L27

There is no escaping going on. But it would be hard to escape there as we don't know what to escape. Maybe Symfony Console drops the quote in the `bref cli` command itself 🤔, here: https://github.com/brefphp/bref/blob/1f56dc9346a92328325a70b1eeeb8aa35c06e24a/bref#L91

**Comment by shadowhand** [comment]
@mnapoli I found a solution that worked locally. I am not 100% certain it is the *right* solution, my goal was only to find a fix that *should* work in most situations.
