### ISSUE TITLE
Internal server error (502)

### ISSUE THREAD

**Issue by jzpeepz** [brefphp/bref#390]
I am trying to get a basic Hello World website going. I have followed all the steps. Everything has went smoothly. But the website displays this:

{"message": "Internal server error"}

Console shows that is a 502 error from CloudFront.

![Screenshot 2019-08-03 08 24 51](https://user-images.githubusercontent.com/14534/62412620-f29e6980-b5ca-11e9-9400-3b76b3df5d37.png)

I have checked logs in both CloudFront and CloudWatch, but they are both clean.

I have seen other issues with the "internal server error" when deployed from Windows. I am on Mac though.

Any ideas what might be going on?

UPDATE: I tried running locally, and I get the following error:

Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]

![Screenshot 2019-08-03 09 06 00](https://user-images.githubusercontent.com/14534/62412882-ee278000-b5cd-11e9-81c4-cf24a70c56cd.png)

I believe this to be related to layers, but I am not quite sure what could be wrong. I am using `${bref:layer.php-73}` from the documentation.

**Comment by mnapoli** [comment]
Hi, which guide have you followed? By default there should not be CloudFront, which is why I’m asking

Sam 03 août 2019, à 15:52, Jonathan Peoples a écrit :

**Comment by victormacko** [comment]
Are you using the '${bref:layer.php-73-fpm}' layer ... this is what you need for HTTP fns (the non-fpm one is for non-http apps).

**Comment by jzpeepz** [comment]
@mnapoli I followed the Getting Started part of https://bref.sh. Then I tweaked the YAML file to make it a basic website.

@victormacko I was using non-fpm, but switching to fpm did not make a difference.

Should layers be "none" like in the screenshot below?

![Screenshot 2019-08-06 08 23 32](https://user-images.githubusercontent.com/14534/62543691-04c71480-b824-11e9-8b6b-7b1042fafa35.png)

**Comment by mnapoli** [comment]
> I was using non-fpm, but switching to fpm did not make a difference.

That could have caused issues, also the fact that you have no layers is a problem.

Could you share the content of `serverless.yml` and your PHP script (`index.php` or whatever its name is)?

**Comment by jzpeepz** [comment]
@mnapoli 
 
Here are those files: https://gist.github.com/jzpeepz/534848adeff9126011a8821f5205aae2

**Comment by mnapoli** [comment]
OK you are using the FPM (HTTP) layer with a non-http application. This will indeed not work.

If you want to create a HTTP application follow the guide: https://bref.sh/docs/runtimes/http.html

In your case you can replace the content of `index.php` with `echo "Hello";` and it should work better.

**Comment by jzpeepz** [comment]
@mnapoli 

That worked. Thanks so much for your help and patience!

BTW my layers still says "none" when I deploy, but hey, it works! Thanks again!

**Comment by mnapoli** [comment]
> BTW my layers still says "none" when I deploy, but hey, it works!

That is good to know, thank you!
