### ISSUE TITLE
Enable the `pdo_mysql` extension by default

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#397]
Since we include the `pdo_mysql` extension, I think we should enable by default.

Using a MySQL db is very common with PHP, and I don't think enabling `pdo_mysql` by default will make anything slower.

What do you think?

**Comment by skyrpex** [comment]
PDO is what Laravel uses by default, right? In that case, I vote yes, all the way.

**Comment by mnapoli** [comment]
@skyrpex yes this is what most people are using, including Laravel, Doctrine/Symfony, etc.

**Comment by nealio82** [comment]
Out of interest, is there a way to re-disable an enabled extension through `php/conf.d/php.ini`? For example, at my work we use `pdo_pgsql`, and so `pdo_mysql` is just (albeit very tiny) unnecessary overhead.

**Comment by mnapoli** [comment]
@nealio82 AFAIK it's not possible to unload an extension, unless by editing the original `php.ini` that loads it. It could be done via an extra layer, but that is a bit overkill.

**Comment by linuxjuggler** [comment]
I agree with @nealio82 on this one, I don't think there is any needs to do so, for example, not all functions or applications is going to use it, in my case am planning to use bref to do som API calls which don't needs `pdo` nor `pdo_mysql` at all, but this does not mean am aginst `pdo`. Plus, as you said unload an extension is not as easy as enabling a new one.

**Comment by jenschude** [comment]
@nealio82 you could override the default php.ini using the PHP_INI_SCAN_DIR environment variable by leaving out the default scan dir and provide only the configuration you need. So yeah with tricks you could override the default configuration.
