### ISSUE TITLE
Change API Gateway/FPM timeouts to 29 seconds

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#401]
I've realized in the API Gateway console that the default timeout is 29 seconds, not 30 seconds:

![Capture d’écran 2019-08-09 à 13 42 29](https://user-images.githubusercontent.com/720328/62776703-a8762600-baab-11e9-9a0c-e414049e5da5.png)

We should update:

- the documentation (anywhere those 30s are mentioned)
- the `serverless.yml` in Bref
- the PHP-FPM configuration

to switch to a 29s timeout. A 30s timeout is useless.

**Comment by Nyholm** [comment]
What benefit is it to limit the Lambda function to 29 seconds? Either PHP is killed by lambda or it is killed by API Gateway though Lambda.. Does it really matter?

We should however update PHP FPM to like 28 seconds? In the PHP world these are still ages for a request. And 28 seconds will give Lambda and PHP FPM to shutdown properly.

**Comment by mnapoli** [comment]
What I want to avoid is to have a PHP-FPM worker process reach 29s, and then the lambda is shut down. But on the next invocation, the lambda resumes. And I am not sure if all processes are killed, or if our FPM worker will keep being busy for 1 second. I am pretty sure that it's not the case (the lambda is cleared and we go through a cold start again) else the same problem would exist for all languages.

But having the same timeout sounds a bit more safe to me. And that helps document to people what the timeout is anyway.

> We should however update PHP FPM to like 28 seconds? In the PHP world these are still ages for a request. And 28 seconds will give Lambda and PHP FPM to shutdown properly.

Agreed, that would be probably an even better option.

@linuxjuggler would you be able to update your pull request to 28 seconds? Sorry for the late changes :/

**Comment by linuxjuggler** [comment]
No worries, I'll do it at the evening

**Comment by linuxjuggler** [comment]
@mnapoli I just updated the PR to be 28sec instead of 29sec. can you check and let me know.

Thanks 👍
