### ISSUE TITLE
Dashboard doesn't seem to work with multiple aws profiles

### ISSUE THREAD

**Issue by tiagobrito** [brefphp/bref#406]
Even when I assume a specific profile role in the command line it seems that the dashboard always tries to run in the "default" AWS credentials profile.

Error:
`Type: Aws\CloudFormation\Exception\CloudFormationException
Message: Error executing "DescribeStackResources" on "https://cloudformation.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://cloudformation.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response: <ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/"> <Error> <Type>Sender</Type> <Code> (truncated...) ValidationError (client): Stack with id bref-demo-symfony-staging does not exist - <ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/"> <Error> <Type>Sender</Type> <Code>ValidationError</Code> <Message>Stack with id bref-demo-symfony-staging does not exist</Message> </Error> <RequestId>61e0c574-bb02-11e9-a7c4-fb2a591804a4</RequestId> </ErrorResponse>
File: /opt/dashboard/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php
Line: 195`

**Comment by mnapoli** [comment]
Indeed, that is not possible yet. Thanks for the report I add this to the todo list.

**Comment by mnapoli** [comment]
Just some notes: maybe what we could do is add a `--profile` flag to the `bref dashboard` command? Or maybe it's even enough to simply pass the `AWS_PROFILE` variable to the Docker container and "it will just work"?

**Comment by tiagobrito** [comment]
passing the `AWS_PROFILE` would be a great idea.
I'm using `zsh` with `aws` plugin and the assume profile command (`asp {profile-name}`) does exactly that. It updates `AWS_PROFILE` to the right `{profile-name}`

**Comment by j0k3r** [comment]
See https://github.com/brefphp/bref/pull/424

**Comment by mnapoli** [comment]
I've released https://github.com/brefphp/bref/releases/tag/0.5.4 !

**Comment by tiagobrito** [comment]
Thank you @mnapoli
