### ISSUE TITLE
Offer PHP 7.4 beta layers

### ISSUE THREAD

**Issue by ondrejmirtes** [brefphp/bref#408]
Hi,
I'd love to have PHP 7.4 beta layers so I could run phpstan.org with them and analyse for example code with native property types. If you don't want to build them yourself, I'd like some pointers how I could do it myself :) Thank you!

**Comment by mnapoli** [comment]
:+1: let's do this! You can find the code related to the runtimes here if you want to look at it: https://github.com/brefphp/bref/tree/master/runtime I'm not sure how much work that entails ^^

**Comment by ondrejmirtes** [comment]
OK, so this is my last checklist item before I'm able to release new PHPStan version with PHP 7.4 support, so I'm looking into it now :)
