### ISSUE TITLE
[proposal] using Discord instead of Slack for the community

### ISSUE THREAD

**Issue by linuxjuggler** [brefphp/bref#410]
Hey,
Since Slack provides limited search functionality for the free version, I was wondering why we don't use Discord app instead? 
Many opensource projects are using it https://discordapp.com/open-source. I think it provides a better alternative and still free too.

**Comment by mnapoli** [comment]
Thanks for the suggestion. My limited experience with discord was pretty poor, but I'm not closed to it. Any other reason besides the history to prefer discord?

**Comment by linuxjuggler** [comment]
Till now discord didn't exclude poeple based on the US sanction (as am aware of) mean while companies like Slack, GitHub ..etc has put restrictions on people living within countries under the US sanctions, therefore they can't be part of the community because of a political matters not because they don't want to.

Also in discord you will have one account to access all the projects that you are part of, so no need to create a new account over and over to join other projects.

**Comment by mnapoli** [comment]
I've been told that there are no threads in Discord.

That unfortunately a huge downside: notifications are either all or nothing (i.e. you get notified of every single message in the room).

**Comment by linuxjuggler** [comment]
True, Discord has no threads and am not sure if they will ever add it, to be honest.
As mentioned in the [help](https://support.discordapp.com/hc/en-us/articles/215253258-Notifications-Settings-101) page, you will be notified based on three things:
1. All
2. Nothing
3. Mentions

So if someone needed your attention, they could mention you, which is good as you don't get notified about each and every message.

**Comment by mnapoli** [comment]
Closing for now.
