### ISSUE TITLE
Logs output throw a validation error

### ISSUE THREAD

**Issue by tiagobrito** [brefphp/bref#412]
Not sure if this is a Bref issue (probably not). A similar issue is already described in Serverless Framework repository https://github.com/serverless/serverless/issues/4850

```bash
$ sls logs -f website
 
  Serverless Error ---------------------------------------
 
  1 validation error detected: Value '[]' at 'logStreamNames' failed to satisfy constraint: Member must have length greater than or equal to 1
```

**Comment by mnapoli** [comment]
Indeed this is a serverless issue, there is not much we can do here I'm afraid.

Closing to keep the issue tracker up to date.

**Comment by tiagobrito** [comment]
@mnapoli but can you confirm that this is a known issue with the serverless framework or is something related to my logging configuration?

**Comment by mnapoli** [comment]
> can you confirm that this is a known issue with the serverless framework

I can't confirm that, I am not following their issue tracker so closely.

> is something related to my logging configuration?

I don't know honestly, I don't really know what your logging configuration is.

> Does this problem exist in standard bref applications?

Ah ok I see what you mean, no: this feature is supposed to work. For example I use it, and that's the first time I hear someone mention that error.

If I were you I would follow that up in the serverless issue tracker and try to debug that with them. There should probably be something specific that is causing the issue in your case.

**Comment by nikita-fuchs** [comment]
same issue happening here.
