### ISSUE TITLE
Remove debug server headers by default

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#413]
On all responses there is a header like `x-powered-by`. There is no point in showing the world that information. 

I think we just need to modify php.ini with `expose_php = Off`

**Comment by mnapoli** [comment]
Is there a reason to remove them?

A reason to let that in that I see is that it helps the w3c (and other 3rd parties) build a list of the most used languages in websites.

**Comment by Nyholm** [comment]
The reason to remove them is just basic security thinking. Why would I expose information that is not needed for the users to use my site? 

This may seam unlikely. but what if there is a bug in PHP 7.x.y that lets a hacker do nasty things. Why would I expose that Im using PHP 7.x.y? I rather make it a little more difficult for a hacker to find me. 

Yes, it is unlikely, yes you may give me a tin foil hat. But there is no win for me to expose this header.

**Comment by mnapoli** [comment]
TBH as long as this is a widespread default, I don't think there's anything we should do differently.

And since it can be disabled via php.ini users are not forced to keep it as well.

Closing for now.

**Comment by Nyholm** [comment]
I found this discussion: https://github.com/php/php-src/pull/3335

Sure, lets fix this issue on PHP instead.

**Comment by M1ke** [comment]
@mnapoli just to ensure this old issue has enough infor for people to implement the suggested php.ini fix, am I on the right track with this process:

1. create a `php/conf.d/` subdirectory in your project
2. create a file in this dir with any name followed by `.ini`
3. This file can contain just the following string `expose_php = Off`

When deployed to Lambda, this will turn off x-powered-by header but not change other defaults from the included 2 ini files?

(ref: https://bref.sh/docs/environment/php)

**Comment by mnapoli** [comment]
@M1ke  that sounds good yes!

**Comment by M1ke** [comment]
Tried that and it worked fine, thanks!
