### ISSUE TITLE
no vendor/bin/bref after composer require bref/bref command

### ISSUE THREAD

**Issue by amcquade** [brefphp/bref#414]
Installed with composer 1.7.3 and PHP 7.0.29

**Comment by mnapoli** [comment]
With PHP 7.0 you shouldn't be able to install Bref (it requires PHP 7.2).

I am guessing you had an error, maybe try to copy/paste the error here so that we can help.

**Comment by amcquade** [comment]
@mnapoli just ended up switching to 7.2, didnt realize 7.0 is technically unsupported. thanks anyway!
