### ISSUE TITLE
[regions] Publish runtimes on China regions.

### ISSUE THREAD

**Issue by ac1982** [brefphp/bref#422]
Please publish the runtimes on chinese regions, like:
cn-northwest-1 (宁夏)
cn-north-1    (北京)
Thanks a lot.

**Comment by mnapoli** [comment]
:+1: if anyone wants to have a go at this you can probably find the region list in this repository easily, but there is also https://github.com/brefphp/runtimes.bref.sh to update.

**Comment by mnapoli** [comment]
Hey @AlessandroMinoccheri was fast 😄, here is the PR in the other repository: https://github.com/brefphp/runtimes.bref.sh/pull/1

I will merge https://github.com/brefphp/runtimes.bref.sh/pull/1 when runtimes are published, so I'll keep it open in the meantime.

What's missing to publish the runtimes:

- update the build scripts in this repository to add the new regions (PR welcome)
- build and publish the runtimes (I'll take care of that)

**Comment by bnusunny** [comment]
@mnapoli AWS China regions is a seperate partition, which require a seperate account. I can help to build and push the runtimes in China region.

**Comment by bnusunny** [comment]
Here are the layers published in China regions. 

layer | region | arn 
---|---|---
php-73|cn-north-1|arn:aws-cn:lambda:cn-north-1:215043275130:layer:php-73:2
php-73-fpm|cn-north-1|arn:aws-cn:lambda:cn-north-1:215043275130:layer:php-73-fpm:2
php-72|cn-north-1|arn:aws-cn:lambda:cn-north-1:215043275130:layer:php-72:2
php-72-fpm|cn-north-1|arn:aws-cn:lambda:cn-north-1:215043275130:layer:php-72-fpm:2
console|cn-north-1|arn:aws-cn:lambda:cn-north-1:215043275130:layer:console:2
php-73|cn-northwest-1|arn:aws-cn:lambda:cn-northwest-1:215043275130:layer:php-73:2
php-73-fpm|cn-northwest-1|arn:aws-cn:lambda:cn-northwest-1:215043275130:layer:php-73-fpm:2
php-72|cn-northwest-1|arn:aws-cn:lambda:cn-northwest-1:215043275130:layer:php-72:2
php-72-fpm|cn-northwest-1|arn:aws-cn:lambda:cn-northwest-1:215043275130:layer:php-72-fpm:2
console|cn-northwest-1|arn:aws-cn:lambda:cn-northwest-1:215043275130:layer:console:2
