### ISSUE TITLE
AWS environment variables in the Context object 

### ISSUE THREAD

**Issue by nhazdun** [brefphp/bref#427]
Hi @mnapoli,
I propose to add AWS environment variables into the Context object. Any lambda has env variables and every time I should copy-paste function which gets env vars from AWS. What do you think about this feature request? I can prepare PR for it.

**Comment by deleugpn** [comment]
The Context object is a standard object provided by AWS on all other runtime. For me it's a no-go, specially the potential to leak secrets into logs.
If this were to be provided, would be best suited as a dedicated object for it.

**Comment by mnapoli** [comment]
At first look I kind of agree with @deleugpn, that object is standard.

Could you explain better what is the problem with using environment variables directly? Why would it be easier if those were in the Context object?

What kind of environment variables are you talking about? Secrets (like database password), or configuration values for the application? Could you give an example?
