### ISSUE TITLE
GD or Imagick layer instructions

### ISSUE THREAD

**Issue by wsheldon** [brefphp/bref#434]
Hi everyone, 

I've seen the other related issues and I understand roughly how the Lambda layers work but could anyone provide step by step instructions how to build a GD or Imagick layer?  For example, how do you compile a PHP extension for AWS Linux locally?  Will send beer or coffee in exchange.  This is a pet project for me.  Currently using 7.2.20 FPM.

Thanks!
Wilson

**Comment by mnapoli** [comment]
Hi, I'm sorry but this duplicates #198, I'll be closing it to keep the issue tracker organized.

Regarding GD you can have a look at #396 by the way.
