### ISSUE TITLE
CodeIgniter documentation

### ISSUE THREAD

**Issue by anandvns** [brefphp/bref#441]
Please give instructions or tutorial on how to use bref for codeigniter for lambda

**Comment by italo1983** [comment]
Does not require any hack.. we already integrated bref on many CI projects:
- Install bref via composer
- Create php/config.d folder with .ini files to enable required extensions like PDO
- Set $config['uri_protocol'] variable to  'PATH_INFO' otherwise will not work via API Gateway
- Set $config['composer_autoload'] to TRUE
- Setup pdo as db driver and use the right syntax to define hostname
- Optionally integrate S3 stream wrapper and autoload it to use s3:// protocol inside CI default libraries/helpers

That's all!

**Comment by anandvns** [comment]
Do have any sample working project

**Comment by italo1983** [comment]
Sorry, private projects only. But it's very simple.. why do you need a sample project?

**Comment by anandvns** [comment]
Actual I am newbie in lambda ...I have a simple project in codeigniter and using xampp on Windows...so I need a little bit instruction...so that it can be successful deployed...

**Comment by anandvns** [comment]
Getting Error Message: Undefined index: SCRIPT_NAME

please check 
https://sspzzrogbl.execute-api.ap-south-1.amazonaws.com/dev/

**Comment by anandvns** [comment]
The SCRIPT_NAME problem is solved now on connecting to database using PDO driver getting error

Message: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

Filename: /var/task/system/database/drivers/pdo/subdrivers/pdo_mysql_driver.php
please check
https://sspzzrogbl.execute-api.ap-south-1.amazonaws.com/dev/

click on MYworld for database connection

**Comment by anandvns** [comment]
> 
> 
> Getting Error Message: Undefined index: SCRIPT_NAME
> 
> please check
> https://sspzzrogbl.execute-api.ap-south-1.amazonaws.com/dev/

**Comment by anandvns** [comment]
> 
> 
> Does not require any hack.. we already integrated bref on many CI projects:
> 
>     * Install bref via composer
> 
>     * Create php/config.d folder with .ini files to enable required extensions like PDO
> 
>     * Set $config['uri_protocol'] variable to  'PATH_INFO' otherwise will not work via API Gateway
> 
>     * Set $config['composer_autoload'] to TRUE
> 
>     * Setup pdo as db driver and use the right syntax to define hostname
> 
>     * Optionally integrate S3 stream wrapper and autoload it to use s3:// protocol inside CI default libraries/helpers
> 
> 
> That's all!

Where to create  php/config.d folder with .ini files to enable required extensions like PDO

**Comment by anandvns** [comment]
> 
> 
> > Does not require any hack.. we already integrated bref on many CI projects:
> > ```
> > * Install bref via composer
> > 
> > * Create php/config.d folder with .ini files to enable required extensions like PDO
> > 
> > * Set $config['uri_protocol'] variable to  'PATH_INFO' otherwise will not work via API Gateway
> > 
> > * Set $config['composer_autoload'] to TRUE
> > 
> > * Setup pdo as db driver and use the right syntax to define hostname
> > 
> > * Optionally integrate S3 stream wrapper and autoload it to use s3:// protocol inside CI default libraries/helpers
> > ```
> > 
> > 
> > That's all!
> 
> Where to create php/config.d folder with .ini files to enable required extensions like PDO

Database stated working with mysqli driver

**Comment by anandvns** [comment]
> 
> 
> > Getting Error Message: Undefined index: SCRIPT_NAME
> > please check
> > https://sspzzrogbl.execute-api.ap-south-1.amazonaws.com/dev/

Solved

> 
> 
> The SCRIPT_NAME problem is solved now on connecting to database using PDO driver getting error
> 
> Message: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'
> 
> Filename: /var/task/system/database/drivers/pdo/subdrivers/pdo_mysql_driver.php
> please check
> https://sspzzrogbl.execute-api.ap-south-1.amazonaws.com/dev/
> 
> click on MYworld for database connection

Solved on using mysqli as driver

**Comment by anandvns** [comment]
codeigniter working with database connection to amazon rds...now i am trying for session management...

**Comment by mnapoli** [comment]
@anandvns please refrain from posting too many messages at once. This notifies a lot of people.

Let's give it a day or two and post a summary of your findings here.
