### ISSUE TITLE
Dashboard doesn't inherit current AWS_PROFILE

### ISSUE THREAD

**Issue by miketheman** [brefphp/bref#443]
Similar, but different, to #406 

The output from the command is masking the real issue, whereas I had no idea that the underlying `serverless info` command was failing due to something, the only feedback I received was:

```shellsession
$ vendor/bin/bref -vvv dashboard



 [ERROR] The command `serverless info` failed



```

By adding more `-vvv` I expected something more to come back, and it didn't.

Once I added `--profile=<myprofile>` this worked, but I'm already setting the correct `$AWS_PROFILE` variable, could you possibly inherit that first, and override it if passed in explicitly?

**Comment by mnapoli** [comment]
Right that makes sense.

We could:

- forward the current value of `AWS_PROFILE` by default (if not set then we forward an empty string, that should be fine)
- else if `--profile` is set we forward the value that is given there

**Comment by miketheman** [comment]
That sounds like the behavior I’d expect to happen.

**Comment by tiagobrito** [comment]
`--profile` is already working but the tag wasn't released yet

**Comment by mnapoli** [comment]
@tiagobrito the `--profile` option has been released already: https://github.com/brefphp/bref/releases/tag/0.5.4

However here we are talking about automatically forwarding the `AWS_PROFILE` environment variable. That means no need to use `--profile` for those that set that variable in their shell.

**Comment by tiagobrito** [comment]
true, I was thinking on `stage` option (this one wasn't released yet)

**Comment by mnapoli** [comment]
Indeed, I've tagged [0.5.5](https://github.com/brefphp/bref/releases/tag/0.5.5)!

**Comment by mnapoli** [comment]
I have pushed a commit that should forward the variable now.
