### ISSUE TITLE
Add the xsl extension

### ISSUE THREAD

**Issue by JGamboa** [brefphp/bref#455]
do anyone knows how to add xsl extension?

**Comment by mnapoli** [comment]
The [xsl extension](https://www.php.net/manual/en/book.xsl.php) isn't installed in Bref layers (see https://bref.sh/docs/environment/php.html#extensions).

However it seems that it is an extension that is usually installed by default (see https://www.php.net/manual/en/xsl.installation.php). If that's the case and it doesn't add too much size to the layers, we should probably add it.

Could you (or anyone else) confirm that the xsl extension is installed and enabled by default in classic distributions of PHP, for example on Debian?

**Comment by italo1983** [comment]
libxml and libxslt are very useful, used also in SOAP webservices or in XLST transformation (XML to PDF/HTML), please  we also need those extensions. Maybe libxml + libxslt + GD will be available on the next release?

**Comment by JGamboa** [comment]
@mnapoli i know that for the install you have to do sudo apt-get install php5-xsl and thats all :B

**Comment by JGamboa** [comment]
any news :D? @mnapoli

**Comment by mnapoli** [comment]
@JGamboa any news will be displayed in this issue.

We are still waiting to learn if this extension is installed by default in most distributions (Debian, Ubuntu, official PHP Docker image…).

**Comment by JGamboa** [comment]
@mnapoli im really sorry i cant answer that because i really dont know about docker, but i will try to learn about it

**Comment by italo1983** [comment]
It's not enabled by default but installed in a tipically LAMP environment. For example: http://devilbox.org/ but also installed and enabled by default with most used hosting control panels like VestaCP. Please can you add it? Installed filesize is +/- 100Kb but i think that's is very useful for application transforming XML or working with xsl files for import/export purpose.

**Comment by JGamboa** [comment]
@mnapoli i have a laradock environment to test laravel apps, and i look at the dockerfile and for the xsl extension this is what is written

###########################################################################
# XSL:
###########################################################################

USER root

ARG INSTALL_XSL=false

RUN if [ ${INSTALL_XSL} = true ]; then \
  # Install the PHP XSL extension
  apt-get -y install libxslt-dev php${LARADOCK_PHP_VERSION}-xsl \
;fi

**Comment by JGamboa** [comment]
###########################################################################

ARG INSTALL_XSL=false

RUN if [ ${INSTALL_XSL} = true ]; then \
    # Install the xsl extension
    apt-get -y install libxslt-dev && \
    docker-php-ext-install xsl \
;fi

###########################################################################

**Comment by tristanbes** [comment]
@mnapoli XSL is required by pinky, which could be required in the new Symfony Mailer component (`twig/extra-bundle twig/inky-extra`) when you want to write your emails in Inky templating language;

https://symfony.com/doc/current/mailer.html#inky-email-templating-language

So, I think it would be worth adding to the bref layer; WDYT ?

**Comment by Kocal** [comment]
XSL extension is required by [pinky](https://github.com/lorenzo/pinky/blob/master/composer.json#L18), which is required by Symfony Twig [Inky extra](https://github.com/twigphp/inky-extra/blob/2.x/composer.json#L18) library.


https://symfony.com/doc/current/mailer.html#inky-email-templating-language

**Comment by JGamboa** [comment]
@Kocal  do you know the vapor project of laravel? do you know how to add xsl to the vapor layer?

**Comment by Kocal** [comment]
I've heard of Laravel Vapor but no I don't know how to add/enable extension XSL with Vapor. Try to ask to their support.

**Comment by Kocal** [comment]
I'm gonna try to open a PR by taking #452 as model :sweat_smile:

**Comment by mnapoli** [comment]
Hi everyone, thanks for confirming, I think it makes sense to include the extension then. We will have to check that it doesn't add too much to the layer.

If anyone of you wants to open a PR 👍

**Comment by Kocal** [comment]
A PR has been opened #

**Comment by JGamboa** [comment]
@Kocal  nice! thanks you
