### ISSUE TITLE
Query String encoding issues when using ALB

### ISSUE THREAD

**Issue by tobyryuk** [brefphp/bref#456]
When running API Gateway, query strings in the event object are automagically URL decoded but when using Application Load Balancer, they're not. This leads to a problem where the `getQueryString` function ([here](https://github.com/brefphp/bref/blob/ccabf70f2e8249ed6cbb52144b8f2af62ffc5533/src/Runtime/PhpFpm.php#L297)) ends up URL encoding ALB query strings twice. ([more information can be found here](https://serverless-training.com/articles/api-gateway-vs-application-load-balancer-technical-details/))

Here's an example of what we get out when using these parameters `?single=value%20with%20spaces&multi[rise%20of%20planets]=hello%20world&multi[death%20of%20planets]=bye%20world` running Laravel.

API Gateway
![Screenshot 2019-09-16 at 15 20 48](https://user-images.githubusercontent.com/9976439/64961566-1cb79c80-d896-11e9-8d7f-c7b8898b3234.png)

Application Load Balancer
![Screenshot 2019-09-16 at 15 20 39](https://user-images.githubusercontent.com/9976439/64961571-204b2380-d896-11e9-98f4-f76fcd3c56ef.png)

From what I've found so far, there's no super clear way of figuring out if the invokation is from API Gateway or Application Load Balancer but what we could do is check the event and see if the API Gateway specific event properties are there or not and URL decode the result of the `http_build_query` once before returning it, if not from API Gateway. ([event differences from SO](https://stackoverflow.com/a/51729273))

**Comment by tobyryuk** [comment]
I've temporarily solved this by overwriting the `PhpFpm.php` file before deploy where I wrap `http_build_query` in `urldecode`.

**Comment by pmayet** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=297772

**Comment by nuvolapl** [comment]
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html

> If the query parameters are URL-encoded, the load balancer does not decode them. You must decode them in your Lambda function.

So, unfortunately, we need to handle it in the lambda function runtime.

**Comment by deleugpn** [comment]
I've been using Lambda with Bref behind ALB quite a lot and I'm not sure why I've been oblivious to this issue.
Is there something specific my requests need in order to cause the problem? I use Laravel, is it relevant for the issue?
We have SPA sending lots of requests using axios and jquery and I never noticed anything regarding encoding. I'd like to better understand this problem in order to figure out if I might be a victim of it at some point

**Comment by mnapoli** [comment]
Should be fixed by #693

**Comment by gregn610** [comment]
I think I'm seeing this with v1.5.4 on AWS API Gateway and Baikal and this worked as a temp fix.

> I've temporarily solved this by overwriting the `PhpFpm.php` file before deploy where I wrap `http_build_query` in `urldecode`.

I've put up a phpinfo() debugging page that I've [reacted & rehosted here](https://gregn610.github.io/public/phpinfo.html) in case it helps.
