### ISSUE TITLE
Cannot find module './vendor/bref/bref'

### ISSUE THREAD

**Issue by khrazy5150** [brefphp/bref#459]
After following the clear instructions on the bref website, just to do a simple "hello world" deployment, I get the following error:

Serverless plugin "./vendor/bref/bref" initialization errored: Cannot find module './vendor/bref/bref'
Require stack:
- /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js
- /usr/local/lib/node_modules/serverless/lib/Serverless.js
- /usr/local/lib/node_modules/serverless/lib/utils/autocomplete.js
- /usr/local/lib/node_modules/serverless/bin/serverless

What did I do wrong?

**Comment by mnapoli** [comment]
Hi, you are very probably using an older version of PHP or Serverless.

See #453

**Comment by khrazy5150** [comment]
Thank you so much! It was in fact my version of Serverless Framework that needed to be updated.
