### ISSUE TITLE
Can bref be used to deploy WordPress on AWS Lambda?

### ISSUE THREAD

**Issue by khrazy5150** [brefphp/bref#460]
In looking at your documentation, bref promises to deploy PHP web applications "as is" to a Lambda function. If this is so, would I be able to deploy WordPress version 5 to the cloud using bref WITHOUT ANY CHANGES???

**Comment by mnapoli** [comment]
Hi, Wordpress would require some changes as it works with a writable filesystem (for updates, plugins, etc.).

However it is possible to run it on Lambda.

**Comment by geoff-ellison** [comment]
EFS (Elastic File Service) just [doubled in speed](https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-elastic-file-system-increases-per-client-throughput/).
Perhaps this could make it viable for this purpose now?
Has anyone had experience running PHP code from an EFS location on Lambda?

**Comment by mnapoli** [comment]
@geoff-ellison is this the minimal throughput that was increased?

In any case, I don't think even a double increase is enough to run code, see https://www.youtube.com/watch?v=yJD7AQgfEJ8

It might be worth trying though.

**Comment by Stevemoretz** [comment]
Well I'm just surfing the web just to see how serverless applications are implemented for my future use.

But I found this which might be useful:

https://aws.amazon.com/quickstart/architecture/sudo-consultants-serverless-wordpress/
https://aws-quickstart.github.io/quickstart-sudo-consultants-serverless-wordpress/

It's been 2 years so you probably either let this go, or already done it but if you haven't this might be helpful.

**Comment by mnapoli** [comment]
There is also https://ymirapp.com, which AFAIK is built on Bref (?). For those who want something that just works.

**Comment by bnusunny** [comment]
Just want to add one project here: https://github.com/aws-samples/serverless-woocommerce-workshop

This runs WordPress in Lambda. The trick to lower cold start is to pre-compile OpCache File Cache. 

And I'm experimenting with SnapStart. This should further improve the cold start.

**Comment by Stevemoretz** [comment]
> Just want to add one project here: https://github.com/aws-samples/serverless-woocommerce-workshop
> 
> It runs WordPress on Lambda. The trick for low cold start is to use OpCache Files Cache and pre generate them.
> 
> And I'm experimenting with SnapStart. This should further reduce the cold start.

@mnapoli Looks like another case of EFS usage, looks like it is now ready to be used, could you try your test once again?

**Comment by kevincerro** [comment]
> There is also https://ymirapp.com, which AFAIK is built on Bref (?). For those who want something that just works.

Yes, its Bref based and mentions you on the public github repo
https://github.com/ymirapp/php-runtime
