### ISSUE TITLE
How to custom layes?

### ISSUE THREAD

**Issue by YuK1Game** [brefphp/bref#463]
Hi.

I want to use Tesseract-OCR with PHP.
My dream is to collect characters from all over the world by extracting characters from images.

However, of course, Tesseract cannot be used as standard.

When using php-73-fpm, I want to describe how to install Tesseract in Dockerfile.
Or is there a difference only method?

Is the path correct in `runtime/layers/fpm/Dockerfile`?

thanks.

**Comment by mnapoli** [comment]
Hi, this duplicates #198 so I'll be closing this one.
