### ISSUE TITLE
Integrate Polyscripting to mitigate code injections

### ISSUE THREAD

**Issue by archisgore** [brefphp/bref#468]
**Background:**

Hello bref community! I am CTO of Polyverse Corporation (polyverse.com). One of our open source (the kind where you can fork it and make billions off of it and we'll be happy for you) R&D projects is called Polyscripting where we generate a new PHP runtime right at deployment, unique to a particular closure of execution.

More details here: https://polyverse.com/polyscripting/

The intent behind this is project is to effectively make code-injections impossible, by evading against the attack entirely (and detecting an attempt thanks to the syntax error.)

We've merged it in Wordpress: https://www.katacoda.com/polyverse/scenarios/polyversepolyscripted-wordpress-v2

Here's a detailed whitepaper of the concept/internals:
[Polyscripting-10-18.pdf](https://github.com/brefphp/bref/files/3666273/Polyscripting-10-18.pdf)

And we prototyped deploying this to lambda as well: https://github.com/polyverse/pxp-lambda

**The Ask:**

My question is, would this be interested to be supported through/merged into bref out of the box? If each function, when a certain parameter is set, were run on a scrambled interpretor of PHP, such that, untrusted, mistaken or backdoored code would find it very difficult to get executed because it wouldn't know what the interpreter is speaking.

Since this is purely a deployment/packaging concern, development and testing never has to know. It merely hardens production workloads and removes a large attack vector.

**What's in it for us/What's the catch**

To be 100% honest, our bread and butter comes from Polymorphic Linux (the same concept applied to machine code at the instruction level.) There's no intent/goal to bait-and-switch or any such thing (happy to transfer copyrights to the code if that makes it comfortable.) It's under the MIT license, which is as permissive as it gets. In short, we're happy to do whatever it takes to provide comfort/confidence.

We wanted to see if we could do it, and then we pulled it off. It's fun, it's applicable, and it's useful. So we'd like to see it used more - call it an ego/validation thing.

So I'm posting an issue here to see if this would be interesting. We'd be happy to invest in integration as well. Looking forward to thoughts, opinions and critique.

**Comment by mnapoli** [comment]
Hi, thank you for opening this issue.

That does sound interesting, but this isn't something that should go in Bref's default behavior I think (at least not for now, there are many topics to deal with at the moment). You (or anyone else) are welcome to create a 3rd party package or documentation for this.
