### ISSUE TITLE
Add the GMP extension

### ISSUE THREAD

**Issue by apipemc** [brefphp/bref#473]
How to enable the extension `gmp` or add it to the layout.
I need to work with this library.
https://github.com/web-push-libs/web-push-php
https://github.com/laravel-notification-channels/webpush
or what a recommendation to make web push.

**Comment by Nyholm** [comment]
To enable this extension. One must compile PHP with `--with-gmp`. 

(https://www.php.net/manual/en/gmp.installation.php)

**Comment by Nyholm** [comment]
This is added in https://github.com/brefphp/extra-php-extensions

This issue can be closed.

**Comment by mnapoli** [comment]
🎉
