### ISSUE TITLE
WordPress on lambda

### ISSUE THREAD

**Issue by nasyrov** [brefphp/bref#477]
Hi @mnapoli ,

Thanks for the great package!

I was wondering whether you or someone has a success running WordPress on lambda? I made it work, but only the frontend part since it's using index.php as a front controller. The admin part is a bit tricky for me since it has a lot of independent entry points like wp-login.php/admin.php/post.php etc - are there any ways to handle them nicely?

Thanks,
Evgenii

**Comment by mnapoli** [comment]
Hello! Thanks :)

Wordpress is a common discussion in Slack but I don't think anyone discussed it on GitHub yet. Some people managed to make it work, there are a few things to consider on top of what you described. For example file uploads, or even plugin installation, updates, etc. do not work with the readonly filesystem. I think you need to use tools that orchestrate and configure Wordpress programmatically.

In any case, there is no Bref documentation on this and I don't think there should be anyway (it could very well be in a separate project), so I will close the issue. But maybe others can chime in to share their experience. Feel free to post in this thread.

**Comment by geoff-ellison** [comment]
Might be of interest: https://github.com/brefphp/bref/issues/460#issuecomment-664798531
