### ISSUE TITLE
[Windows] "vendor/bin/bref init" does not create files on Windows 10

### ISSUE THREAD

**Issue by zemiacsik** [brefphp/bref#483]
Hi,
when I try to [initialize project](https://bref.sh/docs/first-steps.html) by running "vendor/bin/bref init" on win10, it does not create "index.php" nor "serverless.yml" files.
Is it suppose to work on win10 or is there some workaround?
Thank you.

**Comment by mnapoli** [comment]
Thank you for the report. What does the output of the command show in the terminal?

I don't have Windows to help debug, if you can you can see the code that runs here:

https://github.com/brefphp/bref/blob/7361a9c0f1c0eb5a8619fe49195d6e97be62c6aa/bref#L28-L88

If you see anything that doesn't work on Windows let us know.

**Comment by zemiacsik** [comment]
The output is:
![image](https://user-images.githubusercontent.com/9535058/67275682-6c0b7100-f4c3-11e9-93c9-4164d2ee49b3.png)
So it looks like it takes the first "bref" (unix) file from "vendor/bin" and not the Windows Batch File.

Although when I try to run "vendor/bref/bref/bref init" it looks like it is doing fine, I will try to have a look at it.

**Comment by mnapoli** [comment]
🤔 that doesn't look right, this doesn't look like the actual output of `vendor/bin/bref init` right?

**Comment by zemiacsik** [comment]
No, it is just an echo of first "bref" file in "vendor/bin":
![image](https://user-images.githubusercontent.com/9535058/67277067-45026e80-f4c6-11e9-8d5c-a165b55300b8.png)
I think win is not able to execute it so it just returns its content.
In this case, the second file "bref.bat" should be probably executed because of the win environment.

**Comment by mnapoli** [comment]
@zemiacsik yes it seems `vendor/bin/bref.bat` should be used on Windows, can you confirm that this works?

**Comment by zemiacsik** [comment]
@mnapoli Yes, `bref.bat` worked fine on Win10.

**Comment by mnapoli** [comment]
Good to know thanks.

Then in the documentation we can add a note to encourage Windows users to use `bref.bat` instead.

**Comment by aagarwal8** [comment]
This works as well
C:\>"vendor/bin/bref" init
