### ISSUE TITLE
V8Js PHP extension as a separate layer (for SSR)

### ISSUE THREAD

**Issue by EggIt** [brefphp/bref#485]
Hi,

I would like to enable SSR of my vue app, apparently i need the V8Js extension to be able to do that.

Does the fpm layer already packages this extension? i can't see it in the docs...

If not is it possible to add it? or should i create a custom layer and add it on top of bref?

**Comment by mnapoli** [comment]
Hi, this is indeed not packaged in Bref.

Given this is a rather "exotic" extension it would be best to package it in a separate layer.

**Comment by Nyholm** [comment]
@EggIt, I think it should be added to https://github.com/brefphp/extra-php-extensions

Can you send a PR there?

**Comment by ronald2wing** [comment]
@Nyholm I am interested in adding the V8Js layer. Is there any tutorial for me to follow to add this new layer? Thank you.

**Comment by Nyholm** [comment]
Yes. There is a tutorial and there are plenty of examples to look at. 

See https://github.com/brefphp/extra-php-extensions#creating-a-new-layer
