### ISSUE TITLE
Document Symfony Kernel.Terminate

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#486]
The [Symfony page](https://bref.sh/docs/frameworks/symfony.html) in the documentation should be updated with information about `Kernel.terminate`. 

We should tell the Symfony developer not to put work after the request is sent because the user will wait for the request to finish. 

The behaviour makes sense, but should be explain. 

See related issue: https://github.com/brefphp/bref/issues/214
See example project: https://github.com/Nyholm/bref-fastcgi-finish

**Comment by mnapoli** [comment]
👍  that makes sense.

FYI the whole behavior is disabled (see https://github.com/brefphp/bref/commit/a45dcfffb7c575175e67b21cd7bdf415206f9f1f) but I see what you mean, it makes sense to add a warning indeed.
