### ISSUE TITLE
cURL returning 404

### ISSUE THREAD

**Issue by anandvns** [brefphp/bref#496]
I am using runtime arn:aws:lambda:us-east-1:209497400698:layer:php-73-fpm:13 for my project.
PHP cURL  (curl_init & curl_setopt ) working on my localhost but on production to lambda it returns 404. Any Idea

**Comment by mnapoli** [comment]
Do you mean that you have errors when trying to make an HTTP request in your code?

If you have a 404 in that case, I am afraid it isn't something related to Bref right?

**Comment by anandvns** [comment]
> Do you mean that you have errors when trying to make an HTTP request in your code?
> 
> If you have a 404 in that case, I am afraid it isn't something related to Bref right?

No sir, code is okay...it is running fine on localhost and other hosting....may be cURL is not enable in php bref runtime or may be due to other reason. I don't know but on request the page on lambda which have curl code return 404 error

**Comment by mnapoli** [comment]
The curl extension is enabled. 404 is an HTTP error that means that the request is sent correctly but the resource cannot be found. That would also confirm that CURL is installed and working.

Unless the 404 is directly related to Bref or AWS Lambda (check the 404 of the URL: is it a URL you recognize? if not then maybe post the full error here?) you might be better of asking on StackOverflow. I will be closing the issue for now, let's reopen if we identify a problem with Bref itself.
