### ISSUE TITLE
Support imagettftext by compiling GD with freetype

### ISSUE THREAD

**Issue by dwahlqvist** [brefphp/bref#497]
**Use case:** I'm trying to migrate an image manipulation service that's adding text to an animated gif. 

My code works on my regular Ubuntu18 PHP install, but not with Bref 0.5.10 & Lambda.

I get the error message `Call to undefined function ...\\imagettftext()"`.

imagettftext is included in GD, but according to [php.net](https://www.php.net/manual/en/function.imagettftext.php) "This function is only available if PHP is compiled with freetype support (--with-freetype-dir=DIR )" .

It seems to me GD is already included in Bref so, I _believe_ the solution is to compile PHP with freetype support.

I understand it should be technically possible for me to achieve this, by adding a custom layer, as described on [bref.sh](https://bref.sh/docs/environment/php.html#custom-extensions).
I have spent many hours trying, but didn't succeed. There are just too many moving parts for me who is new to both serverless and compiling PHP.

**Comment by mnapoli** [comment]
Hi! Yes, that's something that we can look into adding (I actually would use this myself).

The question would be: how bigger would the layer be with the freetype included? If it's acceptable, then we can add it directly in Bref. If it's too heavy, we should either not include it, or create a separate layer providing just that (better).

**Comment by Nyholm** [comment]
Maybe we should remove GD from core an add it in the bref/extra-php-extensions.

**Comment by mnapoli** [comment]
We could, but is it worth the bc break and the trouble for users (having to install an extra layer)? (since GD is used by a few people)

Ideally we should check if we would save a lot of space? (trimming the layer would help bring cold starts down too) Especially if we take into account this issue (freetype) as well as #531 (that add more to the size of the layer)

**Comment by benoitmenard** [comment]
Hi,

Do you have an ETA for this ? I have an issue with GD and truetype .. 

Do you have a contribute guide ? As I need it quickly, I can work on it :)

Thanks,

**Comment by victormacko** [comment]
@benoitmenard best approach is just to compile it on your end, post the layer sizes for both uncompressed and compressed (compared with the later sizes before any changes were made) -- that's the first step with the majority of extension additions.

**Comment by benoitmenard** [comment]
I did some test and its works well for me; but only for 7.3.

Quick question but not related, I saw that the PHP version used is 7.3.7 and 7.3.17 is available; how do handle the upgrade of PHP; and also related things (libssh, postgres, etc ...)

Thanks

**Comment by Nyholm** [comment]
Have a look here: https://github.com/brefphp/bref/blob/master/runtime/base/php-73.Dockerfile#L16

**Comment by drAlberT** [comment]
> We could, but is it worth the bc break and the trouble for users (having to install an extra layer)? (since GD is used by a few people)
> 
> Ideally we should check if we would save a lot of space? (trimming the layer would help bring cold starts down too) Especially if we take into account this issue (freetype) as well as #531 (that add more to the size of the layer)

@mnapoli  do you think that making it a "shared object" would make it possible to unload the bundled one and load the layers one? This would make the change BC ...

Ppl needing `truetype` will require an additional bref layer, while the others would continue as usual using the bundled (shared, `.so`) GD extention ...

**Comment by mnapoli** [comment]
We could do like imagick though: deprecate the built-in gd extension, and work on the extension in the "extra" layer.

In the next major release, the gd extension could be completely removed from the main layer.

**Comment by drAlberT** [comment]
any ETA?

**Comment by mnapoli** [comment]
Hi, no ETA at the moment.

**Comment by mnapoli** [comment]
Done in https://github.com/brefphp/extra-php-extensions/pull/76
