### ISSUE TITLE
Access to variables within .bref.yml

### ISSUE THREAD

**Issue by gregmsanderson** [brefphp/bref#50]
Hello,

I see you can add a build hook within .bref.yml. I was wondering about using that to run grunt to prepare the static files (CSS, JS etc). So I would run a hook like '_grunt production_' and presumably then those generated (minified) files would get deployed.

... which got me thinking ...

Can you access _variables_ within that .yml file in the same way serverless mentions you can in _its_ yml? (https://serverless.com/framework/docs/providers/aws/guide/variables/). Only if so, would it be possible to set the build hook to be like 'grunt ${opt:stage}'? Since then it could dynamically run 'grunt staging' or 'grunt production', or whatever the stage being deployed was, and so do a different set of operations (like upload them to a different location). Thanks!

**Comment by mnapoli** [comment]
> Can you access variables within that .yml file in the same way serverless mentions you can in its yml? 

It is not possible at the moment indeed. It sounds like a good idea though.

**Comment by gregmsanderson** [comment]
Ok. If you wanted to add for a build hook, I would think you would simply pass it along:

1) https://github.com/mnapoli/bref/blob/master/src/Console/Deployer.php#L74
`$this->generateArchive($io, $progress);`
.... to
`$this->generateArchive($io, $progress, $stage);`

(and the function params would need that third one adding, so it expects it)

2) https://github.com/mnapoli/bref/blob/master/src/Console/Deployer.php#L193
Add a line prior to that one:
```
if (null !== $stage) {
  $buildHook = str_replace('${opt:stage}', $stage, $buildHook);
}
```

... so that would simply turn _'grunt ${opt:stage}'_ into _'grunt production'_ (or whatever). Replacing the string with the stage.
Thanks.
