### ISSUE TITLE
Web application does not get event or context info

### ISSUE THREAD

**Issue by sectoroverload2k** [brefphp/bref#506]
When using API gateway with lamda proxy, php does not get any event or context information. I'm hoping to get authorizer info passed from cognito pool, as well as data from PUT and DELETE methods (STDIN vs $_GET and $_POST) for a REST API.

**Comment by pl4yradam** [comment]
@sectoroverload2k Have a look at my code here: more than welcome to use - I have solved this issue

**Comment by pl4yradam** [comment]
https://github.com/brefphp/bref/pull/501
