### ISSUE TITLE
The recommended way to include custom extensions

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#518]
I would like to discuss the best way to include a PHP extension. There are a long list of issues where people are asking for different extensions. See: https://github.com/brefphp/bref/issues/485, https://github.com/brefphp/bref/issues/473, https://github.com/brefphp/bref/issues/310, https://github.com/brefphp/bref/issues/224, https://github.com/brefphp/bref/issues/455, https://github.com/brefphp/bref/issues/365, https://github.com/brefphp/bref/issues/345, https://github.com/brefphp/bref/issues/292, https://github.com/brefphp/bref/issues/283

### Option A)

**Fork the Bref repo and install whatever you want**. This works great... until you read the latest updates on brefphp/bref and wish that you easily could enjoy the new features. 

### Option B)

**Build a new docker image based on Bref**. I think this could work.. You need to figure out a build process and make sure to not update the PHP package without the docker image. 

### Option C)

**Build your own later**. I think this is the intention of layers, but I dont really know how I can recompile PHP in that layer.. Or maybe it is possible to just add my .so file and make sure the application specify the proper php.ini settings. 

### Option D)

**Use polyfills**...

### Something else?

Im not sure if this list is complete or not. Im also not sure this issue require a code change. I just want to make sure there is a way and that way is documented. 

Have anyone else tried something that works?

**Comment by mnapoli** [comment]
Hi, the situation has changed in the last months. We have built docker images to help, and the documentation explains how to use it: https://bref.sh/docs/environment/php.html#custom-extensions

I wish the documentation was a bit more complete, that's definitely doable (especially creating an example in a repository), but to me the path to follow is now clear.

WDYT?

**Comment by Nyholm** [comment]
Matthew, you are a star!

Thank you. I've missed the updates on that section. I will try to build some extensions and update the docs if I find it needed. 

What I do miss is tags on the docker images. I would like to have one tag with every bref release, right? That way, I dont have to update the infrastructure if I dont want to.

**Comment by mnapoli** [comment]
Ah yes that makes sense! Here is where images are pushed: https://github.com/brefphp/bref/blob/master/Makefile#L7-L21 and here is where they are tagged: https://github.com/brefphp/bref/blob/master/runtime/Makefile#L25

To tag them with each release, I think we need a better setup that is automated, maybe push the images via Travis automatically on a new release?
