### ISSUE TITLE
Documentation for Laravel framework doesn't cover the last framework version

### ISSUE THREAD

**Issue by gerdzhikov** [brefphp/bref#528]
It seems, that the documentation for usage with Laravel framework doesn't cover the current Laravel Framwork 6.*

They are some bootstraping differences and when calling `mkdir(config('view.compiled'), 0755, true);` in `AppServiceProvider.php` throws and exception `mkdir(): Invalid path`

**Comment by mnapoli** [comment]
Thank you for the report. It is possible honestly, I haven't had time to work that much with Laravel lately. The only thing I did was create the example here: https://github.com/brefphp/examples

If you are able to send a pull request that would be awesome.

**Comment by gerdzhikov** [comment]
I mean this https://github.com/mnapoli/bref-laravel-demo example, referenced in the documentation here https://bref.sh/docs/frameworks/laravel.html
Currently I'm looking for solution and if I find something I'll make a pull request.

**Comment by mnapoli** [comment]
Right, but the example here: https://github.com/brefphp/examples is more up to date.
