### ISSUE TITLE
Basic setup encounters error 'couldn't find valid bootstrap'

### ISSUE THREAD

**Issue by jpike88** [brefphp/bref#536]
This is all defaults, with a PHP Function type of project.

Attempting to run it gets this:

```serverless invoke local --docker -f function```

```{"errorType":"exitError","errorMessage":"RequestId: 26bc0da4-7311-16c9-7514-2ffe296837cf Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"}```

**Comment by mnapoli** [comment]
Thanks for the report, I think it's a duplicate of #409

**Comment by vk-sourcefuse** [comment]
On my local, by clearing cache before invoking lambda worked fine, I'm using linux / ubuntu
```

docker system prune --all
sudo apt-get autoremove
sudo apt-get clean
sudo apt-get autoclean
sudo rm -rf ~/.cache/
sudo rm -rf /var/cache/
```
