### ISSUE TITLE
Rewrite and fix runtimes.bref.sh

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#537]
https://runtimes.bref.sh/ is down, it is a permission issue.

It seems AWS changed some permissions, it doesn't seem possible anymore to list layer versions from a 3rd party AWS account.

(for example, this: `aws lambda list-layer-versions --layer-name arn:aws:lambda:us-east-1:209497400698:layer:php-74` doesn't work anymore)

## Suggestion

I suggest we rewrite runtimes.bref.sh so that it's more useful to everyone, while fixing the root issue.

What we could do is, instead of listing the latest layer versions, we could list the layer version for a specific Bref version.

Here is a screenshot of how it could work:

<img width="1295" alt="Capture d’écran 2020-01-26 à 16 13 36" src="https://user-images.githubusercontent.com/720328/73135051-5aec7600-4057-11ea-922b-01e0545ef406.png">

Visitors can choose a Bref version and a region, and they see the matching layer version.

**How to get the layer versions for a specific Bref version?**

Each layer versions are listed here:

https://github.com/brefphp/bref/blob/master/layers.json

By using the "Raw" URL, and changing the `master` branch with a release version in the URL, we can download the JSON. For example:

https://raw.githubusercontent.com/brefphp/bref/0.5.13/layers.json

This is the current call to the AWS Lambda API: https://github.com/brefphp/runtimes.bref.sh/blob/0c98a26d7415d8ed6cdd8e5875a9ec86fc97ae60/index.php#L84-L90 This would be replaced with a HTTP request to download the JSON file.

## Want to help?

Here is the repository for the website: https://github.com/brefphp/runtimes.bref.sh

Pull requests are welcome!

Please keep the code as simple as possible! I.e. unless absolutely necessary, do not split the small application in multiple files and directories. Keep in mind that future contributors to this project will want to send small improvements as easily as possible :)

You can refer to the screenshot to see what to implement:

<img width="1295" alt="Capture d’écran 2020-01-26 à 16 13 36" src="https://user-images.githubusercontent.com/720328/73135106-1e6d4a00-4058-11ea-85f5-295319aeb133.png">

Not a fan of front-end development? I have created a draft of the HTML template here: https://gist.github.com/mnapoli/cb718eb5ec98660880508f79d21ff5f7 That way you can take the CSS classes there.

**How to run the application locally?**

You can edit the `Makefile` because it will be obsolete: the `make preview` command can be replaced by a simple `php -S 127.0.0.1:8000` command. (don't use SAM, it is not necessary if we don't call the AWS API anymore)

**Comment by Nyholm** [comment]
I tested this myself. 

If I run the application but with my account ID (and credentials) I do get the layer versions: 
<img width="1359" alt="Screenshot 2020-01-26 at 13 20 46" src="https://user-images.githubusercontent.com/1275206/73135090-d42b9f00-403e-11ea-8b74-e6926272aa9b.png">


I can also successfully run a similar script in extra-extension. https://github.com/brefphp/extra-php-extensions/blob/master/src/Aws/LayerProvider.php#L39

**Comment by mnapoli** [comment]
@Nyholm makes sense, in that case I guess you host the app in the same account as the layer.

Here with Bref, I have my personnal account (where I run apps), and the Bref account which only contains the layers (for security reasons). That's why there is a cross-account call.

I think this problem is an opportunity for a better service for users (by allowing to select a Bref version). I have updated the description of the issue for suggestions. I'll try to see if anyone is interested to update the application.

**Comment by Nyholm** [comment]
I agree with the rewrite. That would be a great feature since all versions of bref is not compatible with all versions of the layers.

**Comment by mnapoli** [comment]
Fixed by @sgrodzicki, the website is up now: https://runtimes.bref.sh/
