### ISSUE TITLE
Document BREF_LOOP_MAX

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#541]
This is currently an in-official feature and does not fall under an BC promise. This issue serves as a reminder and make sure we don't forget about it. 

When this issue is closed, the feature will be official.  =)

**Comment by mnapoli** [comment]
:+1: perfect!

**Comment by deleugpn** [comment]
Oh I didn't know about it. I'm already using it 😄 😄 😄

**Comment by mnapoli** [comment]
Done in 1.0.
