### ISSUE TITLE
Extensions list it out of date: gd is enabled by default

### ISSUE THREAD

**Issue by WyriHaximus** [brefphp/bref#552]
It looks like the list with extensions on the website is incomplete. Just deployed a microservice running bref using `ext-gd` even though there is no mention of it here: https://bref.sh/docs/environment/php.html#extensions-installed-and-enabled

**Comment by mnapoli** [comment]
Thank you, this was fixed in #529

**Comment by mnapoli** [comment]
(the website will be rebuilt on the next release)

**Comment by WyriHaximus** [comment]
Ok let me make it a bit more interesting, I didn't enable it, it just worked out of the box.

**Comment by mnapoli** [comment]
Good point! Thanks!
