### ISSUE TITLE
Handle HTTP to HTTPS Requests?

### ISSUE THREAD

**Issue by viezel** [brefphp/bref#565]
Ive been building around 6 microservices using Bref already and it has been a blessing. So thank you @mnapoli for this!

The newest project im building is a website, and a new challenge came up: . I **need to handle HTTP to HTTPS redirects**. Quite critical on the website use case since users does not type https in the browser but just example.com and hit ENTER. 
And API gateway does not support http redirects to https 😠. 

I cannot figure out the best way to do this. The requirements are that the entire solution should be cheap, as the website gets few requests/day, but peaks in certain time slots - hence a great use case for serverless. Today its on a $10 server, and want to switch to serverless to handle those peaks without spending more money on it. 

1. ALB could work - but is out due to pricing
2. Cloudfront in front of API Gateway. How to do this in serverless.yml?
3. Other solutions I missed?

Once we figure this out, I think it should be part of the Bref docs as its a very common use case.

**Comment by mnapoli** [comment]
Hi, happy to read that everything is helpful to you :)

Have a look at this documentation: https://bref.sh/docs/websites.html#same-domain

Also regarding API Gateway, it is possible to get the redirect, I am closing this in favor of #546

**Comment by viezel** [comment]
@mnapoli How do I get API Gateway to redirect? Its fine to close this, but I cannot find the answer to this

**Comment by mnapoli** [comment]
That's discussed in #546, this is why I closed this one. As far as we can tell, if you deploy to "edge", you get CloudFront so you get the redirect. If you deploy "regional", you don't get the redirect.
