### ISSUE TITLE
Getting an Error but execution is correct

### ISSUE THREAD

**Issue by jpretelt** [brefphp/bref#566]
The program is executing well. But I getting an error in the file bref/src/Runtime/LambdaRuntime.php
for the line number 266

        $jsonData = json_encode($data);
        if ($jsonData === false) {

and that is happening because the variable $jsonData is empty.

What happen in that cases when the $jsonData is empty? is a bug for bref?

**Comment by mnapoli** [comment]
For reference here is the line: https://github.com/brefphp/bref/blob/0905012b2cdaa4dd88a723d13ba824b00e587c31/src/Runtime/LambdaRuntime.php#L266-L272

I am not sure there is a bug here. Your function can return `null`, `false` or an empty string: `json_encode` will correctly encode it. The result of the encoding should be a string.

If the function returns `false` (not the string `"false"`), it means there was an error encoding the data.

Do you have an example to reproduce the problem?

**Comment by jpretelt** [comment]
This is the error tha I'm getting

![image](https://user-images.githubusercontent.com/4278281/77605170-4525f080-6ee2-11ea-872c-1589844b22fb.png)

This is the code for the command:

<?php

namespace App\Console\LoadFilesCommands;

use App\Components\SAMEEXM;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class LoadPublicFilesCurrentMonthCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'load:PublicFilesCurrentMonth {esquema} {archivos} {fecha=null}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Load Public Files for the Current Month';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        Log::debug("INICIA Sincronizacion de Archivos Publicos desde Servidores de XM para el Mes Actual.");
        Log::debug(date("Y-m-d H:i:s"));
        $esquema = empty($this->argument('esquema')) || $this->argument('esquema') == 'null'  ? 'public' : $this->argument('esquema');
        $strArchivos = empty($this->argument('archivos')) ? null : $this->argument('archivos');
        $archivos = empty($strArchivos) || $strArchivos == 'all'  ? array() : preg_split("/[\s,]+/", $strArchivos);
        $fecha = empty($this->argument('fecha')) || $this->argument('fecha') == 'null'  ? null : $this->argument('fecha');

        $objSAMEEXM = new SAMEEXM();
        $archivosEnHTTP = $objSAMEEXM->validateServerProtocolForFile($archivos, 'HTTP');
        $archivosEnFTP = $objSAMEEXM->validateServerProtocolForFile($archivos, 'FTP');

        print_r($archivosEnHTTP);
        print_r(PHP_EOL);
        print_r($archivosEnFTP);
        
        if(!empty($archivosEnHTTP)) {
            Log::debug("INICIA Sincronizacion de Archivos Publicos desde Servidor HTTP de XM para el Mes Actual.");
            Log::debug(date("Y-m-d H:i:s"));
            //valida si la carga se realizo correctamente
            if(!$objSAMEEXM->cargaPublicaHTTP($archivos, $fecha, $esquema)) {
                Log::debug("ERROR al Ejecutar Sincronizacion de Archivos Publicos desde Servidor HTTP de XM para el Mes Actual.");
            }
        }


        if(!empty($archivosEnFTP)) {
            Log::debug("INICIA Sincronizacion de Archivos Publicos desde Servidor FTP de XM para el Mes Actual.");
            Log::debug(date("Y-m-d H:i:s"));
            //valida si la carga se realizo correctamente
            if(!$objSAMEEXM->cargaPublicaFTP($archivos, $fecha, $esquema)) {
                Log::debug("ERROR al Ejecutar Sincronizacion de Archivos Publicos desde Servidor FTP de XM para el Mes Actual.");
            }
        }

        Log::debug("TERMINA Sincronizacion de Archivos Publicos desde Servidores de XM para el Mes Actual.");
        Log::debug(date("Y-m-d H:i:s"));
    }
}

I'm using this option:

BREF_BINARY_RESPONSES: 1

In the serverless.yml file.

But when I add this code to the file **bref**

if (isset($payload['output'])) {
        $io->writeln($payload['output']);
    } **else if(isset($payload['statusCode'])) {
        //El output se puede ver en AWS CloudWatch
        $io->writeln($payload['body']);
    }** else {
        print_r($payload);
        $io->error('The command did not return a valid response.');
        $io->writeln('<info>Logs:</info>');
        $io->write('<comment>' . $result->getLogs() . '</comment>');
        $io->writeln('<info>Lambda result payload:</info>');
        $io->writeln(json_encode($payload, JSON_PRETTY_PRINT));
        return 1;
    }

And the following code to the LambdaRuntime.php

    private function postJson(string $url, $data): void
    {
        $jsonData = json_encode($data);
        **if(empty($jsonData)){
            $jsonData = '{"statusCode":200,"headers":{"Content-Type":"application/json"},"multiValueHeaders":null,"body":"Success Execution!","isBase64Encoded":false}';
        }**
        if ($jsonData === false) {
            throw new \Exception(sprintf(
                "The Lambda response cannot be encoded to JSON.\nThis error usually happens when you try to return binary content. If you are writing a HTTP application and you want to return a binary HTTP response (like an image, a PDF, etc.), please read this guide: https://bref.sh/docs/runtimes/http.html#binary-responses\nHere is the original JSON error: '%s'",
                json_last_error_msg()
            ));
        }

When I add those lines to the files, I'm not getting any errors and the application work well on AWS

**Comment by jpretelt** [comment]
H!,

I solved the issue, when I removed the readfile() funcion from any sourcecode and then deploy the app to AWS, it works completally well with any error or warnning.

Maybe this is because the readfile() function reads a file (my application reads several csv files) and writes it to the output buffer and possibly the error is with the buffer output.

Thanks in advance.
