### ISSUE TITLE
aws-profile option for the bref cli command 

### ISSUE THREAD

**Issue by monaye** [brefphp/bref#569]
Got the unauthorized error when I try to pass the assumed role profile to `vendor/bin/bref cli`.  
Saw similar report to the `dashboard` command https://github.com/brefphp/bref/issues/406 
Assuming this is not supported yet.

**Comment by mnapoli** [comment]
Correct, the way to set the profile is to set the `AWS_PROFILE` environment variable:

```bash
AWS_PROFILE=foo vendor/bin/bref cli ...
```

Pull requests to implement `--profile` options would be welcome.
