### ISSUE TITLE
Sending email via SES from Lambda without an external HTTP request?

### ISSUE THREAD

**Issue by aran112000** [brefphp/bref#571]
Hi,

We're currently experiencing an issue where we're unable to send emails from our Lambda application via SES, however.

This application is within a VPC so it can talk to our RDS MySQL instances but we don't want to add a NAT gateway into that unless we really have to. There must be some clever way to make calls directly to SES internal to AWS/our VPC?

In case it makes any difference, this is a Laravel application using the SES mail driver.

Thanks in advance :)

**Comment by GromNaN** [comment]
Maybe you can use SNS (which [provides VPC endpoint](https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-sns-now-supports-vpc-endpoint-policies/)) to trigger an other lambda outside of your VPC.

**Comment by aran112000** [comment]
That's a good suggestion, I'll have a look at what's involved to create Laravel workers on Lambda

**Comment by mnapoli** [comment]
Another solution could be:

Lambda in VPC -> Lambda outside VPC -> SES

I.e. skip SNS and directly invoke lambda from lambda. To do this you can use Lambda destinations. However, the execution model might not fit your use case. But be careful with dealing with errors (setup retries, timeouts and DLQ).

@GromNaN's solution is very good as well (probably simpler).

Be aware that with Lambda you don't need to poll SQS or SNS: these services directly invoke Lambda.

Closing as not directly related to the Bref project.
