### ISSUE TITLE
How to keep multiple lambda functions warm to handle concurrent http requests.

### ISSUE THREAD

**Issue by rajjanorkar** [brefphp/bref#573]
This is the first time i am using bref and deploying laravel app.

Just got stuck - i am trying to spin up multiple lamda function of same laravel app and keep them warm. The reason i have to do it is to handle concurrent http requests. 

I have seen pull request where it keep lambda warm, i am assuming it will just keep 1 lambda function warm.

In my case say i want to keep at least 50 lambda functions warm.

Can anyone please let me know how i can achieve this using this package?

Thank you in advance.

**Comment by deleugpn** [comment]
Nowadays you can simply enable provisioned concurrency so that AWS keeps the lambdas warm for you.

**Comment by rajjanorkar** [comment]
Hi @deleugpn 
Thank you, i read about it and it is bit expensive if i want to keep say 100 lambda functions warm.
In that case it would be less expensive to setup EB environment with load balancer.

I heard keeping lambda warm using warmer is cheap compare to using provisioned concurrency.

**Comment by mnapoli** [comment]
Hi, yes it is more expensive keeping functions warm with the provisioned feature.

You can also try to hack together something that will keep many functions warm, but there is no guide in Bref for that.

If ELB is better/cheaper for your use case, and if you absolutely need warm functions, then probably ELB is the best solution here?
