### ISSUE TITLE
Local development issue - serverlesslayersphp-7318: no such file or directory

### ISSUE THREAD

**Issue by DarkoIlieski** [brefphp/bref#584]
I'm following the example shown in the documentation and I stumble to the following error (complete log bellow):

$ serverless invoke local --docker -f myFunction --data '{"name": "Jane"}'
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Writing Dockerfile...
Serverless: Building Docker image...
Serverless: Downloading base Docker image...
Sending build context to Docker daemon  2.979MB
Step 1/2 : FROM lambci/lambda:provided
provided: Pulling from lambci/lambda
79ae1a42d66b: Pulling fs layer
3807be7fb849: Pulling fs layer
3807be7fb849: Verifying Checksum
3807be7fb849: Download complete
79ae1a42d66b: Verifying Checksum
79ae1a42d66b: Download complete
79ae1a42d66b: Pull complete
3807be7fb849: Pull complete
Digest: sha256:008d80b72a532bd42a0f27e71b172594dc150144cbd4b5127dbd81901b1e7498
Status: Downloaded newer image for lambci/lambda:provided
 ---> 1aa9e9fecf65
Step 2/2 : ADD --chown=sbx_user1051:495 .serverless\layers\php-73\18 /opt
ADD failed: stat /var/lib/docker/tmp/docker-builder448443055/.serverlesslayersphp-7318: no such file or directory

  Error --------------------------------------------------

  Error: Failed to build docker image (exit code 1})
      at C:\Users\SR1\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\invokeLocal\index.js:381:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.16.1
     Framework Version:         1.66.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3

Note: I'm using the latest versions of docker, serverless and bref. 
Not sure if this is a docker or bref/serverless error.

**Comment by mnapoli** [comment]
The error messages seems to come from here:

> Step 2/2 : ADD --chown=sbx_user1051:495 .serverless\layers\php-73\18 /opt
> ADD failed: stat /var/lib/docker/tmp/docker-builder448443055/.serverlesslayersphp-7318: no such file or directory

The `.serverless\layers\php-73\18` turns into `.serverlesslayersphp-7318`.

My guess is that the windows path isn't supported by the mechanism in serverless that supports layers 🤔 (the `\` are removed). I think this may be a Windows support issue for the serverless project.
