### ISSUE TITLE
How to use the most current environment

### ISSUE THREAD

**Issue by roenschg** [brefphp/bref#589]
I use the following annotation in my serverless.yaml.

```
${bref:layer.php-73}
```

But this will always use the layer which was used to create the lambda originally.

How can I upgrade to a newer layer, without defining the layer specificly like so:

```
arn:aws:lambda:eu-central-1:209497400698:layer:php-73-fpm:18
```

**Comment by mnapoli** [comment]
`${bref:layer.php-73}` will use the layer that is compatible with the current Bref version installed.

If you want a new version, all you need to do is to update Bref via Composer.
