### ISSUE TITLE
php runtime not found in AWS London cluster

### ISSUE THREAD

**Issue by Leamsi9** [brefphp/bref#592]
My AWS creds and app are hosted in London. Bref doesn't seem to include a runtime for London. I don't get the missing runtime error on other regions, only authentication issues, because I am based in the london cluster, so other clusters can't authenticate. Any workarounds or clarifications if I misunderstood?

**Comment by mnapoli** [comment]
Hi, I'm not sure what you call "London cluster", is this a region? Could you check in this file if the region is present: https://github.com/brefphp/bref/blob/master/runtime/layers/regions.json

**Comment by Leamsi9** [comment]
My bad, noob Aws error. The London region is also known as eu-west-2. Because it is named London in the console I didn't realise they were the same. Wasted a lot of time, apologies if I wasted a bit of yours too.

**Comment by mnapoli** [comment]
No worries! Happy it is solved.
