### ISSUE TITLE
document using rds-data to connect to a database

### ISSUE THREAD

**Issue by Nemo64** [brefphp/bref#596]
I build a doctrine driver to use the rds-data api to connect to an aurora serverless database.
https://github.com/Nemo64/dbal-rds-data

It removes the need for VPC configuration.
I dislike advertising my own stuff but I think it saves a lot of time and makes the setup much simpler.
So my question is if you'd like me to documented in your [Accessing the database from PHP](https://bref.sh/docs/environment/database.html#accessing-the-database-from-php) documentation.

**Comment by mnapoli** [comment]
Oh wow, the work you did is amazing! Congrats on the well-documented README as well!

Adding a mention in the documentation totally makes sense. It would be good however to make sure to mention that this package is still beta/experimental, so that users are aware.
