### ISSUE TITLE
Access S3 thought a VPC Endpoint

### ISSUE THREAD

**Issue by polc** [brefphp/bref#608]
Hi there! 

I've been trying to configure access from Lambda to S3 using a VPC endpoint, but without success.  It's not directly related to Bref but I think it may be worth documenting as it's a common use case (I would be glad to write some doc if I succeed to make it work).

### Issue identification
 
First, I've struggled to identify the issue, because when trying to call my API, I had a timeout and Bref error message was not explicit : 
```
  | 2020-03-31T11:42:30.081+02:00 | START RequestId: 657d03eb-0300-4a5d-b366-8b78348a0eaf Version: $LATEST
  | 2020-03-31T11:42:30.081+02:00 | [31-Mar-2020 09:42:30] NOTICE: fpm is running, pid 8
  | 2020-03-31T11:42:30.081+02:00 | [31-Mar-2020 09:42:30] NOTICE: ready to handle connections
  | 2020-03-31T11:42:58.114+02:00 | END RequestId: 657d03eb-0300-4a5d-b366-8b78348a0eaf
  | 2020-03-31T11:42:58.114+02:00 | REPORT RequestId: 657d03eb-0300-4a5d-b366-8b78348a0eaf Duration: 28028.20 ms Billed Duration: 28400 ms Memory Size: 2048 MB Max Memory Used: 120 MB Init Duration: 329.80 ms
  | 2020-03-31T11:42:58.114+02:00 | 2020-03-31T09:42:58.113Z 657d03eb-0300-4a5d-b366-8b78348a0eaf Task timed out after 28.03 seconds
  | 2020-03-31T11:42:58.543+02:00 | PHP-FPM seems to be running already, this might be because Lambda stopped the bootstrap process but didn't leave us an opportunity to stop PHP-FPM. Stopping PHP-FPM now to restart from a blank slate.
```

### Configuration problem

Now that the problem is identified, here is the Terraform configuration I've been trying to use without success :

```terraform
// VPC used by Lambda (there are also 3 subnets, not shown here) 
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_route_table" "main" {
  vpc_id = aws_vpc.main.id
}

resource "aws_s3_bucket" "uploads" {
  bucket = "uploads"
  acl    = "public-read"
  force_destroy = true
}

resource "aws_vpc_endpoint" "s3" {
  service_name = "com.amazonaws.${data.aws_region.current.name}.s3"
  vpc_id = aws_vpc.main.id
  route_table_ids = [aws_route_table.main.id]
}

resource "aws_vpc_endpoint_route_table_association" "s3" {
  route_table_id = aws_route_table.main.id
  vpc_endpoint_id = aws_vpc_endpoint.s3.id
}
``` 

Is there anything else I should do ? Maybe it's timing-out because of some policy I didn't configure ? Especially, I'm wondering if I should modify the Lambda execution role to allow access to S3.

**Comment by deleugpn** [comment]
Did you put your Lambda inside the same VPC? Does the VPC have a NAT Gateway or NAT Instance configured? Do you have database connection in your Lambda?

It seems to me that your Lambda is probably configured inside the VPC, but lacks a NAT, which results in lack of internet connection and the timeout.

**Comment by polc** [comment]
> Did you put your Lambda inside the same VPC?

Yes !

> Do you have database connection in your Lambda?

Yes they are both in the `main` VPC  and it's working great.

> Does the VPC have a NAT Gateway or NAT Instance configured?

No, I was thinking that the VPC endpoint was enough, but I'm not really sure at this point ? You're right that my Lambda has no internet access.

**Comment by deleugpn** [comment]
If your RDS is publicly accessible it means your Lambda requires internet access to establish a connection there. When you put your Lambda inside the VPC, it loses internet and it won't be able to connect to the database.

If your RDS is privately accessible, then your Lambda requires VPC anyway and you might want to check security groups.

As for the S3 Endpoint, I'd suggest checking what's the Guzzle configuration timeout. I don't remember what's the default that AWS SDK uses, but I know that Guzzle's default is unlimited. Check if you can change such configuration for the AWS SDK to reduce it to less than 5 seconds or so in order to get a fast exception and make it easier to debug.

**Comment by polc** [comment]
My RDS is not public and only accessible from the VPC.

It was a great suggestion to set a timeout for the AWS SDK, I've been able to confirm that it's indeed a timeout : `AWS HTTP error: cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`.

**Comment by polc** [comment]
Solution : VPCs have default `route_table` and I should not have created a new one for the VPC endpoint. 

Not good : 
```terraform
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  enable_dns_support = true
  enable_dns_hostnames = true
}

resource "aws_route_table" "main" {
  vpc_id = aws_vpc.main.id
}

resource "aws_vpc_endpoint" "s3" {
  service_name = "com.amazonaws.${data.aws_region.current.name}.s3"
  vpc_id = aws_vpc.main.id
}

resource "aws_vpc_endpoint_route_table_association" "s3" {
  route_table_id = aws_route_table.main.id
  vpc_endpoint_id = aws_vpc_endpoint.s3.id
}
``` 

Good : 
```terraform
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  enable_dns_support = true
  enable_dns_hostnames = true
}

resource "aws_vpc_endpoint" "s3" {
  service_name = "com.amazonaws.${data.aws_region.current.name}.s3"
  vpc_id = aws_vpc.main.id
}

resource "aws_vpc_endpoint_route_table_association" "s3" {
  route_table_id = aws_vpc.main.main_route_table_id
  vpc_endpoint_id = aws_vpc_endpoint.s3.id
}
```
