### ISSUE TITLE
Add support for WebP on ImageMagick

### ISSUE THREAD

**Issue by FelipoAntonoff** [brefphp/bref#617]
Hello, how are you?

It would be interesting to add support for the WebP format in ImageMagick.

When I try to convert a png image to it using ImageMagick as a driver, I'm giving the error:
`Webp format is not supported by Imagick installation. (0)`

I found this guide interesting by teaching how to compile webP on ImageMagick and use both the most current versions:
https://github.com/rosell-dk/webp-convert/wiki/Installing-Imagick-extension-with-WebP-support
Libwebp-1.0.0.tar.gz changes to libwebp-1.1.0.tar.gz

I would have some guide on how to recompile the ImageMagick used in Bref with WebP support or if you can it would be interesting to add it already natively, as was done with GD, which unfortunately in my tests makes the image bigger, so the preference for ImageMagick.

I am testing using Intervention Image PHP.
Another detail that I noticed, that when running at 128mb and up to 256mb Lambda's error when I try to use $ img-> limitColors (255); , that is, change the PNG to 8bit.

When switching to 512mb it resolves, I believe it is consuming a lot of ram and cpu, then I will test more with 256mb.

**Comment by mnapoli** [comment]
Hi! Thank you for looking into this.

For reference #531 adds support for webp in GD but isn't merged yet. The question for any pull request like this: how much size does this add to the layer. If you can detail the layer sizes that really helps.

**Comment by FelipoAntonoff** [comment]
Hello, thanks for the feedback.

I didn't implement it, I need to learn a little more about Docker, but it remains for a future suggestion.

I can say that the WebP for screenshots is very good, basically maintains the same quality as PNG and much smaller size, even wins from PNG 8 bits.

I am also analyzing the use of Python, if I use PHP, I try to implement it based on the example provided.

**Comment by RikudouSage** [comment]
@mnapoli This was probably solved by my pull request https://github.com/brefphp/extra-php-extensions/pull/31

**Comment by mnapoli** [comment]
Yes indeed! Thank you!
