### ISSUE TITLE
MongoDB max connections 

### ISSUE THREAD

**Issue by alex-catalyst** [brefphp/bref#621]
First off, thanks for an awesome opensource Library.

I attempted to use Bref for a Laravel (5.6) API which connects to a MongoDB Atlas instance using Jens Seger's Laravel-mongo lib. It works perfectly from a EC2 instance, but when run as an AWS Lambda with Bref, I quickly hit the maximum number of mongodb connections.

My conclusion is that this is likely due to the connection not being reused in between calls, and a new connection being created with every invocation.

For nodejs, MongoDB best practice is to move the connection outside the lambda handler which makes it available between invocations (https://docs.atlas.mongodb.com/best-practices-connecting-to-aws-lambda/).

How would I achieve MongoDB connection caching using Bref and Laravel?

This would likely be useful topic for other users in the documentation as it's a common use case.

**Comment by mnapoli** [comment]
Hi! Is the Lambda scaling to a lot of concurrent instances?

If you scale to a few dozens/hundreds of instances, I would understand that you create too many connections to the database.

If you don't scale too much, then I don't understand why the behavior is different between Lambda and EC2. Are you using the FPM layer?

**Comment by alex-catalyst** [comment]
It happens while running a single instance. Yes, I'm using bref:layer.php-73-fpm.

I must confess the code is hitting the database a few too many times and needs to be refactored. Having said that, EC2 would have resulted in the same problem if that was the issue.

Connection pool reuse in Java is achieved in much the same was as with NodeJS, which is by declaring the Mongo client parameter outside the lambda handler. The fact that I've found a specific code solution for both Java and NodeJS makes me believe it something similar is required for PHP.

The PHP manual states that the Mongo driver utilizes persistent connections. My guess is that these connections are supposed to be closed eventually, but because of the ephemeral nature of AWS Lambda, they remain open. Each new Lambda function with the FPM layer is now possibly creating it's own pool again, resulting in many open connections. 

I may be wrong.

**Comment by alex-catalyst** [comment]
I found the same common best practice for Python for other databases as well. "A common best practice in Lambda is to open the database connection in the Lambda execution environment so it in can be reused with each handler call." (https://aws.amazon.com/blogs/database/query-your-aws-database-from-your-serverless-application/)

I might try a raw PHP custom runtime and instantiate a DB connection outside the handler to see if that works.

**Comment by mnapoli** [comment]
OK, what's weird here is that you are using the FPM layer: I would expect what you describe with the `php-74` layer, not the FPM one.

Why? The `php-74` layer creates a new PHP process for every invocation. You could reuse connections by avoiding that reboot by setting the `BREF_LOOP_MAX` environement variable to something higher than 1.

But with the FPM layer, PHP behaves just like on any server (a blank process for every request). If a few hits on your API do that, then there's definitely a problem. I would look into reusing connections across FPM requests, instead of looking at solutions for Lambda (that you can't apply in PHP-FPM).

**Comment by alex-catalyst** [comment]
Thanks for the explanation. 

My understanding is that the MongoDB PHP driver automatically reuses persisted connections (https://github.com/mongodb/mongo-php-driver/issues/794). 

Also, in the PHP manual it says "These connections are saved by the PHP worker process and may be reused between multiple requests." "When MongoDB\Driver\Manager::__construct() is invoked, a hash is created from its arguments (i.e. URI string and array options). The driver will attempt to find a previously persisted » libmongoc client object for that hash. If an existing client cannot be found for the hash, a **new client will be created** (and persisted for future use)." 

From everything I've read, I'm guessing at this point (very much un-egineer-like of me), that because each PHP worker maintains a connection for reuse, and because it's running in Lambda, the workers die (I can hear their little screams) before they can finish their job, leaving an open connection. The new Lambda will bring it's own workers and try to maintain more connections, but alas their are none left.

It appears the only option left is to run some more tests with a basic 'hello world' Bref app talking to MongoDB. I will post the results here when it's done.

**Comment by alex-catalyst** [comment]
I performed a stress test on the EC2 instance, and the number of MongoDB connections remain stable throughout. The workers are clearly performing as expected, reusing the persisted connections, in an always-on environment.

**Comment by mnapoli** [comment]
Good to know!

One thing to be aware about is that Lambda instances boot and stay alive to handle multiple requests (never in parallel, but they'll handle multiple requests one after another).

If you hit a lambda once every second (and assuming your request takes less than a second), you will always hit the same lambda.

In that lambda, PHP-FPM will (should) keep reusing the same PHP-FPM worker. This is why I would assume that the connection reuse would behave identically 🤔 

Something is indeed going wrong here it seems. Might be worth validating that, in your tests:

- you always hit the same lambda (or at least you don't get a new lambda per request, it's ok if you have 2-3 lambdas)
- in one lambda, the PHP-FPM worker is reused over requests (maybe checking the process ID?)

**Comment by talovicnedim** [comment]
I mean @alex-catalyst 😅

**Comment by phishy** [comment]
@alex-catalyst Exactly two years later! What's your verdict? :-)
