### ISSUE TITLE
The `bref cli` command seems to have a timeout

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#629]
I upgraded Bref in a project that uses `vendor/bin/bref cli`.

One of the command that is run takes a long time, and now I get a timeout when the lambda is invoked via the HTTP API:

```
Fatal error: Uncaught Symfony\Component\HttpClient\Exception\TransportException: Idle timeout reached for "https://lambda.*********.amazonaws.com/2015-03-31/functions/app-preprod-console/invocations". in /srv/build/vendor/async-aws/core/src/Response.php on line 106

Call Stack:
    0.0008     490536   1. {main}() /srv/build/vendor/bref/bref/bref:0
    0.0404    6422864   2. Silly\Application->run() /srv/build/vendor/bref/bref/bref:439

AsyncAws\Core\Exception\Http\NetworkException: Could not contact remote server. in /srv/build/vendor/async-aws/core/src/Response.php on line 106

Call Stack:
    0.0008     490536   1. {main}() /srv/build/vendor/bref/bref/bref:0
    0.0404    6422864   2. Silly\Application->run() /srv/build/vendor/bref/bref/bref:439
  120.4705    7793104   3. AsyncAws\Core\Response->__destruct() /srv/build/vendor/async-aws/core/src/Response.php:0
  120.4705    7793104   4. AsyncAws\Core\Response->resolve() /srv/build/vendor/async-aws/core/src/Response.php:73
  120.4708    7810624   5. AsyncAws\Core\Response->getResolveStatus() /srv/build/vendor/async-aws/core/src/Response.php:109
```

From what I read in the code, [async-aws](https://github.com/async-aws/aws) doesn't have a timeout by default to fetch the response. However, here we have a `Idle timeout` which may be a different kind of timeout.

@Nyholm or @jderusse, would you know if there is such a timeout (if so, how to customize it) or if I am looking in the wrong place? I had a look at the docs but couldn't find that info. Thank you in advance :)

**Comment by jderusse** [comment]
The LambdaClient relies on the injected HttpClient to handle network issue.
Extending the default timeout can be achieved by injecting an HttpClient with the right timeout.

```php
$this->lambda = new LambdaClient(
  ['region' => $region, profile' => $profile],
  null, 
  HttpClient::create(['timeout' => 60]),
);
```

if i don't mistaken, this should fix the issue.

**Comment by mnapoli** [comment]
Awesome, thank you for your help!

Note for myself for later (or anyone looking at implementing this), the timeout could be an option passed in the constructor here: https://github.com/brefphp/bref/blob/master/src/Lambda/SimpleLambdaClient.php#L15

In the `bref cli` command ([here](https://github.com/brefphp/bref/blob/faaadafff71d3677782b265b893ef697a2715cbb/bref#L95)) we could then set a timeout of `0` (anything that makes it infinite).

**Comment by Nyholm** [comment]
I can confirm that the fix is working. 

FYI: The default timeout is `ini_get('default_socket_timeout')`.

**Comment by Nyholm** [comment]
Hm.. I cannot see how the 'timeout' is used in the CurlClient. But maybe Im just missing something.. I only see `max_duration`...

**Comment by jderusse** [comment]
>Hm.. I cannot see how the 'timeout' is used in the CurlClient

Injected in Response, and used when streaming content.

**Comment by mnapoli** [comment]
Thanks both, I have opened #637, it does the trick indeed.
