### ISSUE TITLE
Imagick doesn't support the method compositeImageGravity()

### ISSUE THREAD

**Issue by RikudouSage** [brefphp/bref#630]
In my app I use the imagick method `compositeImageGravity()` but I get an error saying that the method does not exist.

After quick googling I found the method was included in imagick 3.4.1.

**Comment by mnapoli** [comment]
Gotcha, if I understand correctly we would need to upgrade Imagick?

**Comment by RikudouSage** [comment]
Well, it's kinda strange, after I wrote the issue I pulled the docker image (`bref/build-php-74`) locally and it already has the latest version of imagick. A quick check also confirmed that the method indeed doesn't exist there.

It's probably some problem with the dependencies for compiling imagick.

**Comment by RikudouSage** [comment]
So I created this pull request that solves the issue:

https://github.com/brefphp/extra-php-extensions/pull/31

**Comment by mnapoli** [comment]
I don't think https://github.com/brefphp/extra-php-extensions/pull/31 makes sense because this extension already exists in Bref core, that would be duplicating the effort 🤔 

Can you sum up the situation, I am confused whether the method exists or not in the end?

**Comment by RikudouSage** [comment]
Due to the outdated ImageMagick binding it does not exist. You can either remove it from the core or copy the steps from the PR I provided into core if you don't want to duplicate the effort. Or do it gracefully, e.g. start recommending the bref-extra one and deprecating the system one.

**Comment by mnapoli** [comment]
I don't understand, if it's a matter of upgrading the version of Imagick, why would we remove it from this repository?

We should upgrade instead, no?

**Comment by RikudouSage** [comment]
I was just listing suggestions, it's up to you. The problem is not the Imagick extension but the ImageMagick library that Imagick depends on.

The version in the repositories is outdated so you have to compile it from source, so I was listing the options:

1) Use the code from my PR and include it here
2) Remove the imagick from core and provide it in extra only since it's not a core php extension but 3rd party one

What you choose is up to you.

**Comment by mnapoli** [comment]
Closing this in favor of https://github.com/brefphp/extra-php-extensions/pull/31 and https://github.com/brefphp/bref/issues/636

Thank you for working on this and creating https://github.com/brefphp/extra-php-extensions/pull/31!
