### ISSUE TITLE
Post body encoded when content-type:x-www-form-urlencoded header is set

### ISSUE THREAD

**Issue by sachink23** [brefphp/bref#631]
My request looks like -

```
POST /event HTTP/1.1
Content-Type: application/x-www-form-urlencoded

key1=data1
```
Response I get
```
$event["body"] = "a2V5MT1kYXRhMQ=="
```

How can I get the post data in PHP?

**Comment by sachink23** [comment]
Got this, 
I missed 
```
$event["isBase64Encoded"] = true
```
Now I can get post query string using
```
$queryString = base64_decode($event["body"]);
```

**Comment by sachink23** [comment]
Is there any way to access the query strings using superglobals like $_GET, $_POST?

**Comment by mnapoli** [comment]
Hi, I recommend you use the HTTP runtime, it should make it easier for you.

Is there any specific reason you don't want to use it?

**Comment by sachink23** [comment]
No there isn't any specific reason, I am just exploring..
