### ISSUE TITLE
Laravel storage folder

### ISSUE THREAD

**Issue by benoitmenard** [brefphp/bref#633]
Hi,

I set up the correct environment variables for Laravel storage:
    APP_STORAGE: '/tmp'
    VIEW_COMPILED_PATH: /tmp/storage/framework/views

But I have some issue:
`[2020-04-23 19:48:41] stage.ERROR: file_put_contents(/tmp/app/5ea1f1196ac0d.png): failed to open stream: No such file or directory (View: /var/task/resources/views/app/partials/qrcode/pdf/list.blade.php) (View: /var/task/resources/views/app/partials/qrcode/pdf/list.blade.php) {"url":"https://stage.tululu.fr","input":[],"exception":"[object] (ErrorException(code: 0): file_put_contents(/tmp/app/5ea1f1196ac0d.png): failed to open stream: No such file or directory (View: /var/task/resources/views/app/partials/qrcode/pdf/list.blade.php) (View: /var/task/resources/views/app/partials/qrcode/pdf/list.blade.php) at /var/task/vendor/endroid/qr-code/src/Writer/AbstractWriter.php:55)`

My question, does Bref or Laravel handle the creation of the directory strucutre ?

Thanks

**Comment by deleugpn** [comment]
Neither of them handles that. Here's my recommendation: 

1. Change bootstrap/app.php file and include the following line. Feel free to use any namespace you prefer.

```
$app = new Illuminate\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

\App\Ports\Bref\Helpers\StorageDirectories::create($app);
```

Setup the StoreDirectories class

```
<?php

namespace App\Ports\Bref\Helpers;

use Illuminate\Foundation\Application;

/**
 * @see https://github.com/laravel/vapor-core/blob/2.0/src/Runtime/StorageDirectories.php
 */
class StorageDirectories
{
    /**
     * The storage path for the execution environment.
     *
     * @var string
     */
    public const PATH = '/tmp/my-app-name/storage';

    /**
     * Ensure the necessary storage directories exist.
     *
     * @return void
     */
    public static function create(Application $app)
    {
        $directories = [
            self::PATH.'/app',
            self::PATH.'/cache',
            self::PATH.'/framework/cache',
            self::PATH.'/framework/views',
        ];

        foreach ($directories as $directory) {
            if (! is_dir($directory)) {
                mkdir($directory, 0755, true);
            }
        }

        $app->useStoragePath(self::PATH);
    }
}
```

Setup the following environment variables:

```
APP_SERVICES_CACHE: /tmp/my-app-name/storage/cache/services.php
APP_PACKAGES_CACHE: /tmp/my-app-name/storage/cache/packages.php
APP_ROUTES_CACHE: /tmp/my-app-name/storage/cache/routes.php
VIEW_COMPILED_PATH: /tmp/my-app-name/storage/framework/views
```

**Comment by mnapoli** [comment]
FYI this is documented in Bref with a simpler solution: https://bref.sh/docs/frameworks/laravel.html#setup
