### ISSUE TITLE
Wrong path when using multiple stages and custom basePath with Laravel 

### ISSUE THREAD

**Issue by nickaguilarh** [brefphp/bref#646]
Thanks for this amazing project it really helped me a lot.
Today I was deploying some staging servers with a custom domain and custom basePath and that's when I got stuck on this problem:

For example:
Calling `staging.myapi.com/$service$/version`  gives a 404 error since the registered route is `version`
Where
- <$service$> is the basePath for a custom domain on API Gateway and it points to one cloudfront endpoint / lambda function

- $service$ changes for service called, e.g. auth, user, orders. Each of this service is deployed into one function.

So, the problem is that the event sent from API Gateway sends the path as `$service$/version` when it should be only `version`.

A possible solution for this is check for `pathParameter` in the event and use the `proxy` parameter when calling the lambda function. 

I already did a quick test of that and it works. 

`$event['path'] = $event['pathParameters']['proxy'];` on processNextEvent function of LambdaRuntime.php

Let me know if that is the way to go, so I can make a PR

See [Setup Lambda Proxy Integration](https://docs.aws.amazon.com/es_es/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html)

**Comment by mnapoli** [comment]
Hi, thanks  for the details. Yes, dealing with those path prefixes is a recurring issue. Either we pass the full path to PHP (and it messes up routing in the frameworks), or we don't and it messes up route generation.

That's something I want to fix in the next major release.

**Comment by mnapoli** [comment]
I'll be closing this one since it duplicates #309
