### ISSUE TITLE
Add new `bref init` options for Laravel

### ISSUE THREAD

**Issue by GeeH** [brefphp/bref#652]
Update the default options when running a `bref init` so that it adds Laravel as an option:

```
 What kind of lambda do you want to create? (you will be able to add more functions later by editing `serverless.yml`) [PHP function]:
  [0] PHP function
  [1] HTTP application
  [2] Console application
  [3] Laravel Web Application
```

The default `serverless.yml` needs to be taken from the docs.

**Comment by mnapoli** [comment]
@chippyash at the moment, I want to support the 2 main frameworks out there: Laravel and Symfony. These are a given on how massive they are used. For the rest, we'll see.

There is also a specific bridge for Laravel: https://github.com/brefphp/laravel-bridge, over time maybe this bridge will replace the need for `bref init` for Laravel. But at the moment it doesn't do that.

**Comment by mnapoli** [comment]
Done and documented here: https://bref.sh/docs/frameworks/laravel.html
