### ISSUE TITLE
JWT keys on AWS lambda ?

### ISSUE THREAD

**Issue by vasilvestre** [brefphp/bref#655]
Hello,

My Symfony application use JWT token and refresh token using JWT files.  Without shared storage, does that mean I have to use s3 to store this file please?

Regards

**Comment by victormacko** [comment]
The files you include with your app do still get shipped with the app -- they're just not served up by API Gateway on request (only the handler functions are exposed).
So in answer to your question -- it depends on if just your app uses these keys, or if they're meant to be available for other users to access them as well (in which case, you'll need to get your PHP app to serve them up)

**Comment by mnapoli** [comment]
And just to complete @victormacko's great response, you can have a look at a bit of documentation here: https://bref.sh/docs/environment/storage.html

Closing since this is not an issue.
