### ISSUE TITLE
PHP Data Structures Extension support

### ISSUE THREAD

**Issue by chippyash** [brefphp/bref#660]
Can we have the [Data Structures extension](https://www.php.net/manual/en/book.ds.php) added as a standard available extension.  These are enormously useful in creating performant data handling and a replacement for the old SPL data structures.

**Comment by mnapoli** [comment]
Hi, I don't think this would make sense adding this as a standard available extension as this is not a widely used one.

However it would make sense to add it here as an "extra" extension: https://github.com/brefphp/extra-php-extensions Feel free to open a pull request/issue there.
