### ISSUE TITLE
No symfony logs using Messenger and AMQP from outside world

### ISSUE THREAD

**Issue by vasilvestre** [brefphp/bref#661]
I try to use messenger component with rabbitMQ and have no logs at all despite using "dev" in APP_ENV

My setup use a VPC but I have all rules needed and I've tried without VPC.

**Comment by mnapoli** [comment]
I'm sorry but that's not enough information to help.

Did you configure Symfony per the Bref documentation? Did you redirect all logs to stderr?

**Comment by mnapoli** [comment]
I'm not sure what to do here. The best we could do is : could you create a reproducible example? (e.g. a repository somewhere)

**Comment by mareg** [comment]
> I'm not sure what to do here. The best we could do is : could you create a reproducible example? (e.g. a repository somewhere)

Sorry for a late response, in my case I had to add the `monolog/monolog` package and it fixed my problem :) Seems like it's not included in Symfony Flex skeleton.
