### ISSUE TITLE
Database connection error PostgessDB

### ISSUE THREAD

**Issue by GORAZIZYAN98** [brefphp/bref#666]
Hi, guys, I have an issue with database cannot migrate database
DB is Postgres
 the severless'yml

> service: truescape-game-api
> provider:
>   name: aws
>   region: eu-central-1
>   runtime: provided
>   environment:
>     APP_STORAGE: '/tmp'
>     APP_ENV: test
>     APP_DEBUG: true # set to false when moving to production
>     LOG_CHANNEL: stderr # this will send logs to CloudWatch automatically
>     DB_CONNECTION: pgsql
>     DB_HOST: PIPELINES_DB_HOST
>     DB_PORT: 5432
>     DB_DATABASE: PIPELINES_DB_DATABASE
>     DB_USERNAME: PIPELINES_DB_USERNAME
>     DB_PASSWORD: PIPELINES_DB_PASSWORD
>     vpc:
>       securityGroupIds:
>         - sg-xxxxx
>       subnetIds:
>         - subnet-xxxx
>   
> plugins:
>   - ./vendor/bref/bref
> package:
>   exclude:
>     - resources/lang/**
>     - storage/**
>     - node_modules/**
>     - tests/**
> functions:
>   website:
>     handler: public/index.php
>     timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
>     layers:
>       - ${bref:layer.php-74-fpm}
>     events:
>       -   http: 'ANY /'
>       -   http: 'ANY /{proxy+}'
>   artisan:
>     handler: artisan
>     timeout: 120 # in seconds
>     layers:
>       - ${bref:layer.php-74-fpm}
>       - ${bref:layer.console}
> 
> 

I have file in root. php/conf.d/php.ini -> 
;extension=/opt/bref-extra/pgsql.so
extension=pdo_pgsql

when run this  command in bitbucket pipelines  
   _vendor/bin/bref cli truescape-game-api-dev-artisan -- migrate --force_
I got error
  could not find driver (SQL: select * from information_schema.tables where t
  able_schema = public and table_name = migrations and table_type = 'BASE TAB
  LE')
In Connector.php line 70:
  could not find driver
 
and when I run just php artisan migrate
I got timeout error

P.S.
all other artisan commands works but migration

**Comment by victormacko** [comment]
I gather you're migrating from MySQL to Postgres?
Depending on the version of Bref you have installed, you may still need to enable the MySQL driver (it was only enabled by default recently).  ... try including pdo_mysql in your php.ini file and see if that works.

**Comment by GORAZIZYAN98** [comment]
@victormacko I cat the .env all vars are there

**Comment by victormacko** [comment]
Dunno then ... maybe someone else has another idea ... you can always try the slack channel (see the 'community' page on the bref.sh site) for support too

**Comment by GORAZIZYAN98** [comment]
yes thanks

**Comment by GORAZIZYAN98** [comment]
both _vendor/bin/bref cli truescape-game-api-dev-artisan -- migrate --force_ and _php artisan migrate --force_ I run in piplines

**Comment by mnapoli** [comment]
In the `artisan` function, you used the `${bref:layer.php-74-fpm}` layer: it should be `${bref:layer.php-74}`.

**Comment by GORAZIZYAN98** [comment]
oh ! 
@mnapoli thx very much!
