### ISSUE TITLE
Custom domain names documentation outdated?

### ISSUE THREAD

**Issue by mykiwi** [brefphp/bref#667]
Hi, 

Disclaimer: I'm a noob with AWS so maybe I missed something.

I tried to set up a domain name on my lambda [like documented here](https://bref.sh/docs/environment/custom-domains.html), but I can't find how to point `https://abcdefghi1.execute-api.eu-west-3.amazonaws.com/dev/` (the lambda) on my custom domain (& path) which is `foobar.io/baz` (for the example).

In the documentation, I see this part:
> - add a "Path mapping" to map the / URL (or any URL you want) to your HTTP application in the Prod stage, for example:
![aws ui](https://bref.sh/docs/environment/custom-domains-path-mapping.png)

But I don't see the same UI. For me this look like this:
![Screen Shot 2020-06-09 at 00 23 09](https://user-images.githubusercontent.com/334432/84086456-3bdbf880-a9e8-11ea-97e4-ffd8af0f5e4d.png)

And this when clicking on "Configure API mappings"
![Screen Shot 2020-06-09 at 00 25 11](https://user-images.githubusercontent.com/334432/84086463-40a0ac80-a9e8-11ea-876e-cc9e67c91514.png)

In the end my domain does not show the bref app.
Could someone explain to me what is wrong (in the doc or my procedure)?

**Comment by mnapoli** [comment]
Thank you for the report, indeed the UI changed. We need to update the screenshot.

The steps should be the same though. Here, it seems correctly configured. Now to use you custom domain `foobar.io`, you need to create a `CNAME` DNS entry that points `foobar.io` to the `xxxx.cloudfront.net` domain name that was generated (you can see it in your screenshot).

Does that make sense?

**Comment by mykiwi** [comment]
Yes, I've finally managed to get it working :)
What was missing is the A record with an alias target on the CloudFront. CNAME was not possible in my case.

**Comment by mnapoli** [comment]
I updated the docs for 1.0.
