### ISSUE TITLE
Question: Trimming the payload

### ISSUE THREAD

**Issue by chippyash** [brefphp/bref#669]
This is not an enhancement request.

In common with many scaffolds, Bref utilises an underlaying technology (Serverless in this case). That is all good. Problem is, we are dealing with PHP.  That brings potential bloat in the upload and memory usage for AWS.

Take the elephant in the room: the AWS PHP SDK. Most often, you need a part of it, not all of it. It is enormous.  I have brought this up in various other forums, with some success, such that useless content has now been removed, but it still remains the case that unless you go through and manually remove sections, there is no way to slim it down. It seems to me, that we need a way to 'cull' redundant code from the vendor directory in a programmatic way.

My call here is that, unless we can find a way to trim down the upload to just that which is required, PHP as 'serious' contender is not going to make the grade for Lambda deployment. And I am a very serious PHP coder!

I don't have an immediate answer, but am opening this up for suggestions.

Have opened a [sister ticket](https://github.com/composer/composer/issues/8968) in the Composer repo

**Comment by victormacko** [comment]
Bref doesn't use the official AWS SDK (which is quite big) ... instead, it uses async-aws which only includes code for the services bref actually needs to operate (eg. so S3 code isn't included for instance, when bref doesn't need S3). The composer.json file has the individual packages in-use.

Serverless (the framework) is optional (you can instead use whatever else you like to deploy if you prefer), and doesn't need to be deployed itself (it helps in the deployment process, but you can exclude the entire node_modules directory from being deployed to Lambda, so the serverless framework doesn't need to actually exist with your code on Lambda).

Personally i've found excluding stuff like examples, docs, tests, etc from the vendor dir has greatly slimmed down the code-base .. but that in itself isn't really a Bref "issue". Likewise, optimising the composer autoloader and numerous other approaches to help with performance are also all valid ideas.

Maybe creating a pull-request for the existing "performance" page on the Bref site would help if you have some other ideas to suggest to the community; https://bref.sh/docs/environment/performances.html

Hope it helps!

**Comment by mnapoli** [comment]
@victormacko 👍 

Other than that, I know that @ubermuda once tried to do something like this (purge unused dependencies from the vendor directory), I'm not sure if it's public/usable/useful.

That being said, PHP isn't that different from NodeJS applications. Most Node applications end up quickly with a huge node_modules directory. In the end, PHP works fine.

**Comment by chippyash** [comment]
suggestion from the Composer ticket: https://github.com/dg/composer-cleaner
That goes some way towards a solution.

**Comment by chippyash** [comment]
I'll take a look at https://github.com/ubermuda/derp

**Comment by marcusirgens** [comment]
You can also use the serverless package section to remove specific
directories, although I understand that it might end up being a very long
list in the case of the AWS SDK if you only use one or two services.

lør. 13. jun. 2020 kl. 12:54 skrev Ashley Kitson <notifications@github.com>:

**Comment by marcusirgens** [comment]
You can also use the serverless package section to remove specific
directories, although I understand that it might end up being a very long
list in the case of the AWS SDK if you only use one or two services.

Example [from the docs: 
```yaml
package: # Optional deployment packaging configuration
  include: # Specify the directories and files which should be included in the deployment package
    - src/**
    - handler.js
  exclude: # Specify the directories and files which should be excluded in the deployment package
    - .git/**
    - .travis.yml
```
