### ISSUE TITLE
Bref config not read ?

### ISSUE THREAD

**Issue by guizmo51** [brefphp/bref#675]
Hi ! 
First thanks for your amazing working I very happy to try this tool and try Lambda as a production env !

I'm running Symfony 5.1 / Api-Platform  with PHP 7.3 and PHP 7.4. Locally I'm not using Docker or thing like that (mac OS and I remove docker because of perf issue) .
I also created a folder php/conf.d with a php.ini file and inside :
```
extension=pdo_pgsql
extension=int
```

The first issue I got is the wrong region used per example when I try to call bref via CLI without region param it's the default one (us-west-1) instead of the one I specified in "serverless.yml" (provider > region) [eu-west-3]. I solve it by adding the right region using bref cli (and param --region)

On lambda side after the deploy I got a "internal server error" and log show "could not find driver", I know why but it's look like an issue where my bref settings are not read during the deploy

**Comment by mnapoli** [comment]
Hi, could you post the full exception message? I just want to make sure that it is about the `pdo_pgsql` extension.

Could you maybe check by logging/dumping the loaded extensions using [get_loaded_extensions()](https://www.php.net/manual/fr/function.get-loaded-extensions.php) ?

And about this line:

```
extension=int
```

I'm not sure what extension this is. Is it `intl` instead?

**Comment by guizmo51** [comment]
it's was a typo
its the "intl" extension
My current issue is the following :
```
In FileLoader.php line 173:

  An exception occurred in driver: could not find driver in . (which is being
   imported from "/var/task/config/routes/api_platform.yaml"). Make sure ther
  e is a loader supporting the "api_platform" type.


In AbstractPostgreSQLDriver.php line 79:

  An exception occurred in driver: could not find driver


In PDOConnection.php line 31:

  could not find driver


In PDOConnection.php line 27:

  could not find driver

```
I thought it was something like pdo or pdo_pgsql not loaded

**Comment by guizmo51** [comment]
Ok. It's weird. I add DATABASE_URL in the "environment" part and now it's OK. I thought keep it in ".env" should be OK.


Thanks for your help !
