### ISSUE TITLE
Possible inconsistency between Bref Docker Images and Layer?

### ISSUE THREAD

**Issue by deleugpn** [brefphp/bref#692]
I just noticed this warning on CloudWatch: `PHP Warning: Module 'pdo_mysql' already loaded in Unknown on line 0`. I think I remember seeing a PR that would enable PDO Mysql by default on the layers. However, if I don't enable it, my tests fail when running phpunit with `bref/php-74`. Could this be an inconsistency between the layer and the provided Docker images?

**Comment by mnapoli** [comment]
Oh it could be, but maybe it's just a matter of updating the docker image? (`docker pull`)

If that's the case, then I would agree it's not an ideal workflow (having to remember to update Docker images), I'm not sure how we could improve this.

**Comment by mnapoli** [comment]
Cleaning up the issue ;)
