### ISSUE TITLE
Support Composer's vendor folder packaging in a separate layer

### ISSUE THREAD

**Issue by aniljaiswal** [brefphp/bref#696]
Currently, if you try packaging the Composer's vendor directory into a separate layer and specify the BREF_AUTOLOAD_PATH environment variable accordingly, the deployment is broken due to the fact that Composer creates the autoloading maps which are different from the Lambda directory structure and the autoloading fails.

Since a non-standard vendor directory path is supported by Bref using the above-mentioned environment variable, I think it's a fair ask to provide support/fix for the Composer vendor directory layer as well as provide the relevant documentation around it. Most people would want to keep their actual Lambda function zip sizes as small as possible (also helping in quick debugging in the AWS Lambda console).

I see that others are also facing this issue. https://github.com/brefphp/bref/pull/556#issuecomment-608303535

**Comment by aniljaiswal** [comment]
By the way, Laravel Vapor is already doing this, so I'm assuming, it shouldn't be a big technical challenge.

**Comment by mnapoli** [comment]
@aniljaiswal please don't assume the amount of work someone else might do, possibly for your benefit.

If you think this is simple, then do it. If not, let's leave it at that 😃

**Comment by aniljaiswal** [comment]
I think you misunderstood my sentiment. Anyway, I do not want to get into a debate here. Thanks for the comment.

**Comment by mnapoli** [comment]
Sorry if I did! You're right, there's no need to turn it into a debate ;)

**Comment by rmundel** [comment]
Anyone accepting bounties to create some magical PR us, fat-lambda guys?

**Comment by rmundel** [comment]
Just found out that what sorcery Laravel Vapor was doing to avoid using some EFS drive. (https://github.com/laravel/vapor-core/pull/4/files)

They're actually using the 500MB of /tmp storage.

**Comment by georgeboot** [comment]
Perhaps the new run-Docker-containers-as-lambda-functions (announced at reinvent 2020) could shine some new light on this?

From what I have seen, one could just as well build a Docker container and deploy that, rather than doing the s3 dance.

**Comment by tomhatzer** [comment]
I‘ve created this PR here to enable separation of the vendor folder from the lambda archive: https://github.com/brefphp/bref/pull/812

**Comment by mnapoli** [comment]
Done in #812 🎉
