### ISSUE TITLE
How do I invoke the getting-started function with AWS CLI?

### ISSUE THREAD

**Issue by douglasnaphas** [brefphp/bref#701]
I can invoke the function created [here](https://bref.sh/docs/first-steps.html#initializing-the-project), which has the text:

```
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

return function ($event) {
    return 'Hello ' . ($event['name'] ?? 'world!!');
};
```

locally by running `serverless invoke -f function`, as documented [here](https://bref.sh/docs/runtimes/function.html#invocation).

Locally, it prints `Hello world!!`.

I would love to invoke the function with the AWS CLI, to convince myself that the deployment worked.

I am attempting with:

```
$ docker run --rm -v ~/.aws:/root/.aws amazon/aws-cli:latest --profile=douglas lambda invoke --function-name arn:aws:lambda:us-east-1:050877257577:function:app-dev-function response.json
```

This prints
```
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
```
to standard output, but it does not create a file `response.json`.

My code is [here](https://github.com/douglasnaphas/cake-app-01).

Does anyone know how I an invoke the function from the getting-started guide with the AWS CLI? It would be a great addition to the guide.

**Comment by mnapoli** [comment]
Hi, that sounds correct, I think this is because the file is created inside your Docker container, not your machine.
