### ISSUE TITLE
Drop support for PHP 7.2

### ISSUE THREAD

**Issue by mnapoli** [brefphp/bref#703]
For version 1.0, we could drop support for PHP 7.2?

**Comment by pizzaminded** [comment]
IMO support for 7.2 should be dropped when it will leave 'Security fixes only' phase. There may be some apps in wild that are not prepared for higher PHP versions but developers decided to put them to Lambda for tests or something. When it reaches EOL, it's out.

**Comment by deleugpn** [comment]
Do you have a timeline for 1.0 estimated ? Are you looking at something from 7.3 that you want to use within the library?

**Comment by mnapoli** [comment]
The timeline could be August/September. I mostly want to avoid the hassle of maintaining 7.2 layers, and that will allow to simplify a few things in the code.

Also, that will be the opportunity to add more types, which are harder to do later for BC reasons.

Finally, the higher the PHP version we require, the less problem we may have with dependencies that we use that could require a higher PHP version (e.g. it's hard to support 7.2 if a dependency we use decides to drop it).

**Comment by Chtiadrien** [comment]
+1 for dropping support for PHP 7.2.
+1 for more types 😄 

It is in security fix only for 4 more months until EOL. People should already have move on to PHP 7.3 at least.

(If not, they can always use an older version of Bref via a constraint on PHP version in composer.json, that's how I'm dealing with an "old" project on 7.1)

**Comment by mnapoli** [comment]
Implemented in #741
