### ISSUE TITLE
Deploying with Serverless CI/CD

### ISSUE THREAD

**Issue by timworld** [brefphp/bref#704]
Hello, I want to deploy a PHP symfony app, I need to execute composer before deploying but the shell command is never called when deploying with Serverless CI/CD (app.serverless.com) even if my serverless.yml do it perfectly. Can you tell me how I can handle this? thanks

Here an extract of my serverless.yml

plugins:
- ./vendor/bref/bref
- serverless-plugin-scripts

custom:
scripts:
hooks:
'before:deploy:deploy': composer install --prefer-dist --optimize-autoloader --no-dev

**Comment by mnapoli** [comment]
I'm sorry but you'll have to get in touch with the Serverless Pro service support.
