### ISSUE TITLE
No Redis support in the PHP 8.0 experimental layer?

### ISSUE THREAD

**Issue by aran112000** [brefphp/bref#705]
Just wondering if there was a reason Redis support was removed on the PHP 8 layer? Was it not compiling at the time, or is there more behind this decision?

https://github.com/brefphp/bref/blob/740e59f62b267ab83721423b2d7e19db7c77fd8c/runtime/base/php-80.Dockerfile#L122

**Comment by mnapoli** [comment]
It wasn't compiling because there was no version in PECL compatible with PHP 8.

Let me know (or send a pull request) when that changes, I'd happily update that!
