### ISSUE TITLE
Help required: Cognito callback function signature

### ISSUE THREAD

**Issue by chippyash** [brefphp/bref#710]
I'm writing a Cognito pre token generation lambda using bref.  The docs at https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html suggest that the callback is called with 2 parameters. If I do that in php e.g.

`$callback(null, $event);`

then I get an error :

```
{
    "errorType": "ArgumentCountError",
    "errorMessage": "Too few arguments to function {closure}(), 2 passed in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 109 and exactly 3 expected",
    "stack": [
        "#0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(109): {closure}()",
        "#1 /opt/bref/bootstrap.php(38): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#2 {main}"
    ]
}
```

I also looked at https://aws.amazon.com/blogs/mobile/how-to-use-cognito-pre-token-generators-to-customize-claims-in-id-tokens/  and simply returned the event which leads to the same error being thrown.

Does anyone know what that callback signature should be for PHP as the node/python examples don't translate.

**Comment by mnapoli** [comment]
I think you need to `return $event`.

**Comment by nephele42** [comment]
Did anyone test this? I have tried returning $event, and many other versions but cognito always fails with invalid lambda response.

**Comment by hmimthiaz** [comment]
@chippyash I am trying to do merge the social account with existing user. Account creation all works and when the authentication process starts it end with the message in the client callback url.

@nephele42 did you succeed with this. I get the same error "Unrecognizable+lambda+output"

 
![CleanShot 2023-02-25 at 09 00 35@2x](https://user-images.githubusercontent.com/705565/221339300-74cd00f8-78be-4591-b829-ceed6e5f6346.jpg)

**Comment by nephele42** [comment]
@hmimthiaz  no I did not, gave up and wrote the lambda in node.
