### ISSUE TITLE
Add zip binary in docker dev image?

### ISSUE THREAD

**Issue by shouze** [brefphp/bref#711]
I'm using bref php-fpm-dev image to package my apps. I'm wondering if it could be a good idea to add zip binary to help producing the packaged deployment inside this image?

This is already the way I do and I find that very convenient. The thing is that I have to extend the default bref dev image for that. So if it can benefit to other people I'm totally OK to make a PR that will make such thing:
```shell
RUN yum install -y zip
```
The question remains if only into fpm-dev image or not, and if yes, how to switch from current user (sbx_user1051) to root user then switch back to current user.

**Comment by mnapoli** [comment]
Hi, AFAICT I don't see a reason to have that binary.

My logic with the Bref runtimes is usually to try and mimick the runtimes produced by AWS: they don't contain the zip binary.

If you need it in Lambda, you should create a layer (yumda can be useful for that). But from what you say you need it in Docker, which is even easier to install via a custom Dockerfile.

You could even use a multi-step build (for example https://github.com/brefphp/bref/blob/master/runtime/layers/fpm-dev/Dockerfile), but TBH I'm not sure if that's the best solution for packaging for deployments.

**Comment by shouze** [comment]
I understand your point of view. I've already built a custom Docker image ontop of yours for development purpose only as I've explained so I'm ok to maintain things like that. About using docker for packaging purpose I find it convenient at the moment but maybe I miss some good packaging tools, do you have any suggestion in this area?

**Comment by mnapoli** [comment]
Do you mean deploying the source code? I use `serverless deploy` and it creates the zip for me, but maybe you meant something else?

**Comment by shouze** [comment]
Yes, on my side I use terraform and not serverless. BTW event if serverless creates a zip for you you probably remove some things or have some custom steps no?

To illustrate, here's what my Dockerfile.lambda is looking:
```Dockerfile
FROM gogaille/bref as builder
WORKDIR /tmp/build
COPY --chown=root:root . .
RUN unset LAMBDA_TASK_ROOT \
  && composer install --classmap-authoritative --no-dev --no-scripts \
  && bin/console cache:warmup --env=prod
RUN find vendor -type d -iname 'test*' | xargs rm -rf \
  && find vendor -type d -name 'assets' | xargs rm -rf \
  && find vendor -type d -name 'doc' | xargs rm -rf \
  && find vendor -type d -name 'docs' | xargs rm -rf \
  && find vendor -type f -name '*.dist' | xargs rm -rf \
  && find vendor -type f -name '*.md' | xargs rm -rf \
  && find vendor -type f -name '*.txt' | xargs rm -rf \
  && find vendor -type f -name '*.jpg' | xargs rm -rf \
  && find vendor -type f -name '*.png' | xargs rm -rf \
  && find vendor -type f -name '*.gif' | xargs rm -rf
RUN rm -rf public/bundles
```

In the future maybe I'll improve it by packaging vendors separately to create a custom layer for example. As we're currently deploying Symfony apps at the moemnt, same for Symfony cache maybe, this way we would get our app's code editable in AWS console (I know, we don't really won't to do that but it could be sometime an emergency/last resort helper on production, or even to quickly evaluate something on staging/preproduction stages).

**Comment by shouze** [comment]
And yes... here's the current Dockerfile for gogaille/bref image:
```Dockerfile
FROM bref/php-74-fpm-dev
USER root
RUN yum install -y zip
USER sbx_user1051
ENV PATH=$PATH:/var/task/bin
COPY --from=composer:2.0.0-alpha3 /usr/bin/composer /usr/local/bin/composer
COPY --from=cytopia/php-cs-fixer:2 /usr/bin/php-cs-fixer /usr/local/bin/php-cs-fixer
```
