### ISSUE TITLE
A note on config cache

### ISSUE THREAD

**Issue by yangm97** [brefphp/bref#715]
From [Bref/Storage/Pre-generating the cache](https://bref.sh/docs/environment/storage.html#pre-generating-the-cache):

> ### Pre-generating the cache
> 
> Some frameworks allow to pre-generate some caches. For example in Symfony the container can be compiled via `bin/console cache:warmup`, or in Laravel the config cache can be generated before deploying.
> 
> When possible **this is the best solution**: no generation will occur in production, and reading from the filesystem will be fast.

From [Laravel/Configuration Caching](https://laravel.com/docs/7.x/configuration#configuration-caching) (emphasis mine):

> Once the configuration has been cached, the .env file will not be loaded and **all calls to the env function will return null**.

Now suppose you're using any AWS service which makes use of the `$AWS_SESSION_TOKEN` environment variable, pre-generating the config cache on deployment will miss runtime variables, which in turn makes them always return `null`.

This could confuse newcomers, as this gotcha isn't obvious and this strategy is actually highlighted as the "best solution". 

Unless I'm missing some Laravel magic, guess the Bref docs need to be updated.

**Comment by mnapoli** [comment]
Hi, this is a very good point, Laravel is a bit special on this regard. We can probably improve the documentation here.

**Comment by georgeboot** [comment]
Perhaps we could run `artisan config:cache` on the startup of the container? Don't believe the session token etc changes between invocations on the same container.

**Comment by mnapoli** [comment]
They don't, but the filesystem is read-only so the cached config cannot be written at runtime.

**Comment by georgeboot** [comment]
I believe Laravel Vapor does this with route caching. I think the cache path is configurable, so we could simple point it to `/tmp`, right?

**Comment by mnapoli** [comment]
Indeed, I'm not a huge fan of moving the whole storage directory to `/tmp` for the following reasons: https://github.com/brefphp/laravel-bridge/pull/9#issuecomment-672684462

Do you think it's possible to move only the config cache to `/tmp`? (instead of the whole storage directory)

**Comment by georgeboot** [comment]
This is, as far as I am aware, currently not possible. Laravel exposes only a storage directory configurable.

We would have to PR the framework for this.

**Comment by oppiansteve** [comment]
This may be possible if you update the bootstrapper list early on.

I do this in a non-bref project so that I can insert a pre-env bootstraper (to allow moving of the env location) and a post-env bootstrapper (to dynamically change the storage location).

In the `Kernel::__construct()` I call an install function after the call to the parent constructor.

```
class Bootstrap
{
    public static function install(array &$bootstrappers)
    {
        static::doInstall($bootstrappers, 0, BootstrapBeforeEnv::class);
        static::doInstall($bootstrappers, 1, BootstrapAfterEnv::class);
    }

    public static function doInstall(array &$bootstrappers, $position, $class_names)
    {
        if (is_string($class_names)) {
            $class_names = [$class_names];
        }

        $env_configure_index = array_search('Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables', $bootstrappers);
        if ($env_configure_index === false) {
            throw new \Exception('Can\'t see when environment is ready');
        }
        array_splice($bootstrappers, $env_configure_index + $position, 0, $class_names);
    }
}
```

Hope that helps.

**Comment by yangm97** [comment]
@georgeboot upstream wasn't very open about making the real time facade cache path non-hardcoded to the storage path, I wouldn't get my hopes high on getting such PR accepted but I would love to be proved wrong.

**Comment by mnapoli** [comment]
> Perhaps we could run artisan config:cache on the startup of the container? Don't believe the session token etc changes between invocations on the same container.

@georgeboot actually implemented that and that's live in the v2 of the new Laravel bridge 🙌
