### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by chrisemerson** [brefphp/bref#732]
I have an issue when I use any of the Bref layers from php72 to php74 - both normal and fpm layers. I always get an error, even when using the simplest of Lambdas with just an index.php with an echo in it (or function), as follows:

    /opt/bin/php: error while loading shared libraries: libexslt.so.0: cannot open shared object file: No such file or directory 

For the php74 layers, it changes to:

    /opt/bin/php: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory 

I am not using any custom php.ini files or any other layers, and the lambda has only a vendor directory with bref/bref and index.php in it, and the handler is set to index.php in each case.

I can't work out what it could be, and I've tried a few previous versions of the runtime with the same result too.

**Comment by mnapoli** [comment]
Hi, thanks for the report, that's very weird indeed.

Can you confirm:

- that you use serverless.yml?
- that you use the `${bref:xxx}` variables in serverless.yml to get the latest layers?
- that you get those errors when running on lambda? (not in Docker)
- that you don't have a `bootstrap` file in your project?

If possible, can you share the serverless.yml file and the PHP file?

Thanks!

**Comment by chrisemerson** [comment]
Hi

 - I'm not using serverless.yml, but have set everything up the same way I have done before with success. Serverless doesn't fit in with my workflow unfortunately. I'm just referencing the layer directly in a new Lambda.
 - I've tried many different versions of the layers including the latest as per the bref website.
 - Errors are indeed in Lambda, and can be got by using Lambda's built in test tools, so not API Gateway either
 - No bootstrap file in the project

**Comment by chrisemerson** [comment]
PHP file is very simple:

```
<?php

echo "Got here";

exit("Got here too");

```

**Comment by chrisemerson** [comment]
Don't you hate it when you spend hours looking for what's going on, report an issue then find out the problem shortly afterwards...

Turns out I was using 'Custom runtime on Amazon Linux 2' instead of 'Custom runtime'

Apologies for the confusion / issue!
