### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by pjebs** [brefphp/bref#733]
A few questions about running a Laravel application:

1. Can the Laravel application connect to an external managed database such as on DigitalOcean (instead of RDS)
2. When I update my code base, can I get zero-downtime deployments (i.e. all existing requests are served by old code until they are served, but all new requests are done by new code base?

**Comment by victormacko** [comment]
Just to help you along a little - Yes to #1 (just think of RDS as an external service, just happens to be provided by AWS). If you're doing that, you may not actually need your lambda to sit inside a VPC either. If you do sit it inside a VPC for some reason though, it'll need external internet access (eg. a NAT Instance/Gateway).

Personally i've not had downtime with lambda deployments, but someone else more knowledgeable will have to comment on #2 there.

**Comment by mnapoli** [comment]
Regarding 2: yes that's our CloudFormation deployment works (blue/green deployment).
