### ISSUE TITLE
Laravel route wrong path

### ISSUE THREAD

**Issue by gzai** [brefphp/bref#738]
Hi,
Thank you for bref package.
after serverless deploy for Laravel [7], endpoint will be : 
```
endpoint:
  ANY - https://randomstr.execute-api.ap-southeast-1.amazonaws.com/dev
  ANY - https://randomstr.execute-api.ap-southeast-1.amazonaws.com/dev/{proxy+}
```
If I have route `login` and click link login, redirect to : 
`https://randomstr.execute-api.ap-southeast-1.amazonaws.com/login` ( Forbidden ) 
should be : 
`https://randomstr.execute-api.ap-southeast-1.amazonaws.com/dev/login` ( 200 ) 

add group previx `dev` in route, click link login, redirect to :
`https://randomstr.execute-api.ap-southeast-1.amazonaws.com/dev/login` ( Forbidden ) 
but If I add `/dev` in url after `/dev` :  
`https://randomstr.execute-api.ap-southeast-1.amazonaws.com/dev/dev/login` ( 200 ) 

changing `htaccess` and `APP_URL env` didn't work to get the appropriate link.

how do we get the appropriate link when access any link, host will be 
`https://randomstr.execute-api.ap-southeast-1.amazonaws.com/dev/{proxy}`

Thanks

Update : 

Can't be tricked from the laravel framework. 
Use custom domain or bref.dev

**Comment by mwkohler** [comment]
This seems like a more serious issue that should be investigated rather than avoided...

**Comment by mnapoli** [comment]
@mwkohler I plan on fixing this in 1.0 but any pull request is welcome to accelerate that. If your company is able, you can also sponsor my time working on this, let me know if that's the case.
