### ISSUE TITLE
Laravel config files and storage views

### ISSUE THREAD

**Issue by grigdodon** [brefphp/bref#757]
I am struggling to have both Laravel views and laravel config facade working.

I have a view I am using for emails and a config file I am using for ENV variables (myapp.php).

`myapp.php`

```
<?php

return [

    'aws' => [
        'access_key_id'     => env('AWS_ACCESS_KEY_ID'),
        'secret_access_key' => env('AWS_SECRET_ACCESS_KEY'),
        'default_region'    => env('AWS_DEFAULT_REGION'),
    ]
];
```

On deployment I have `php artisan config:clear`
Therefore views are working fine, however `config('myapp.aws.access_key_id')` returns null in the AppServiceProvider.

When  on deployment I have `php artisan config:cache`
`config('myapp.aws.access_key_id')` works fine in the AppServiceProvider but views do not work.

How can I have both work in parallel? Thanks

**Comment by mnapoli** [comment]
Hi, what do you mean by "views do not work"?

We'll need more details to help.
