### ISSUE TITLE
New Relic support?

### ISSUE THREAD

**Issue by NeilJ247** [brefphp/bref#759]
Hi,

Found an old PR for New Relic https://github.com/brefphp/bref/pull/34/files but it appears that it was removed later versions of Bref.  

Any ideas if this extension will be supported?  Or if it won't be supported is it ok to ask what issues there are for supporting it?

Thanks.

**Comment by mnapoli** [comment]
Hi, have a look at https://github.com/brefphp/extra-php-extensions/issues/34 as there is a discussion ongoing there.

**Comment by NeilJ247** [comment]
Thanks for the reply.
