### ISSUE TITLE
define LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by shouze** [brefphp/bref#763]
This is related to https://github.com/brefphp/extra-php-extensions/pull/76

I think we need at least to redefine `LD_LIBRARY_PATH` whith `/opt/bref/lib:/opt/bref/lib64` in bref docker images.

But this is probably also a concern, especially when using extra extensions, people should not forget to define this env var too during the deployment of their lambda otherwise each shared library required by some php extension which is not available will make php app crash.

_Originally posted by @shouze in https://github.com/brefphp/extra-php-extensions/pull/76#issuecomment-699884027_

**Comment by mnapoli** [comment]
@shouze do you remember if that is still an issue (or if we can close this)?

**Comment by shouze** [comment]
> @shouze do you remember if that is still an issue (or if we can close this)?

It was more something 8 perceived as a risk during the switch to Amazon Linux 2 images because sometimes we had both libraries versions: the one from the Amazon base layer and the one from the bref layer. I think we can close unless some people open issues related to strange errors/crashes related to shared libraries.
