### ISSUE TITLE
Cakephp 3 Assets (imgs, js, css) in S3

### ISSUE THREAD

**Issue by patrykmoura** [brefphp/bref#777]
Hey Guys, i'm trying to make my cakephp 3 to work with S3, and so far I have it working after changing a few path directories to system temp path, but assets is not working =\ 

Do you guys have any tips to give me a way to make it work?

To reproduce the error:
```
- Simple install a fresh cakephp 3 version: 
composer create-project --prefer-dist cakephp/app:^3.9 my_app_name

- Change the paths of config/paths.php from this:

define('TMP', ROOT . DS . 'tmp' . DS);
define('LOGS', ROOT . DS . 'logs' . DS);
define('CACHE', TMP . 'cache' . DS);

To this:
define('TMP', sys_get_temp_dir() . DS . 'cake-tmp' . DS);
define('LOGS', sys_get_temp_dir() . DS . 'cake-logs' . DS);
define('CACHE', sys_get_temp_dir() . DS . 'cake-cache' . DS);
```

Then install bref, sls deploy

The images, js, css, any assets wont work =\

You guys can see my own tests here:
Controller works: https://l5b67x905j.execute-api.sa-east-1.amazonaws.com/dev/Home/teste
assets don't: https://l5b67x905j.execute-api.sa-east-1.amazonaws.com/dev/css/owl.carousel.css

Tks a lot!

**Comment by mnapoli** [comment]
Assets are not served by API Gateway' check the documentation on the website.
