### ISSUE TITLE
Missing Authorization header

### ISSUE THREAD

**Issue by moynzzz** [brefphp/bref#781]
Hello,

I'm using bref to deploy a Symfony application which uses the Authorization header to authorize users.

The problem I face is that on the deplyed environment I can't find the value.

Environment consist of Cloudfront, API Gateway and a Lambda function.

Is there any limitations from Cloudfront, API Gateway or Lambda that is preventing my header value to propagate to Symfony?

If there is a solution I will be glad to help write a documentation on how to pass my header value to the lambda function.

Thank you in advance.

**Comment by Manuelacosta98** [comment]
Hi @moynzzz can you post your serverless.yml, can be a problem with your configuration

**Comment by mnapoli** [comment]
Hi, this may be because you need to configure CloudFront to forward the `Authorization` header.

See this part of the documentation:

![image](https://user-images.githubusercontent.com/720328/98087482-6ee3c480-1e80-11eb-9fd3-913e01623bbf.png)

**Comment by moynzzz** [comment]
Wow I don't know how I missed this, yea after adding `Authorization` to the `Headers` section it worked. Thanks @mnapoli.
