### ISSUE TITLE
Separate strerr output in console

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#784]
Im trying out a new thing. For internal APIs I don't want to use API-Gateway, ie get around the "problem" with HTTP and authentication. Instead my apps use a Lambda client and invoke the function directly. 

However, I have a problem with logs and error outputs. 

Example: I have a Symfony command that returns some json. After invoking my lambda function, this is what I get: 

```json
{
  "exitCode":0,
  "output":"[2020-11-12T09:10:38+00:00] Symfony cache directory prepared in 6.33ms.\n{\"status\":\"error\",\"message\":\"not found\",\"data\":[]}"
}
```

This looks super good if it wasn't  for "Symfony cache directory prepared in ..."
The issue is here: https://github.com/brefphp/bref/blob/0.5.32/runtime/layers/console/bootstrap#L39-L60

I want to return only the $output but I want to echo the `stderr` and `stdout`. I know Symfony Process component has separated `stderr` from `stdout`. Either we use that component (already included) or we try to duplicate that code.

**Comment by Nyholm** [comment]
My current workaround is to not use the `console` layer and use my own handler.

**Comment by mnapoli** [comment]
The console runtime is a helper to manually run commands in production, it is not meant to be used for building "services".

I would recommend instead to use the native Lambda behavior with the PHP runtime and write Lambda handlers (either anonymous function or classes).

**Comment by Nyholm** [comment]
Yeah. That is what I ended up with. 

What bothers me with the current solution is that I need a custom "router". 
Ie, If I was doing HTTP, I could use the Symfony Router. If I was using the `console` layers, I could use the command name and the normal Symfony `Application` as "router". And I all worked locally too. 

But now I need to write a custom Bref handler that takes some input and based on that input, find the service/logic to execute. 

Hm.. I'll see if I can make a generic handler to run console commands.

**Comment by mnapoli** [comment]
The approach with Lambda is that Lambda is the router: you create one function per whatever behavior you want. Just like when using API Gateway + Lambda (and not using Bref's FPM runtime) then you usually create 1 Lambda per route.

Here Lambda does the routing for you.

**Comment by deleugpn** [comment]
I did something very similar to this and I wrote about it here: https://blog.deleu.dev/using-aws-lambda-as-a-private-laravel-api/

What I ended up doing is that I **chose** to use the Http Kernel and always invoke my lambda using `LARAVEL_ROUTE`, `LARAVEL_METHOD` & `LARAVEL_BODY`.
I think it's technically possible to implement PSR `ClientInterface` that uses AWS  `LambdaClient` to transform a PSR-7 Request into a Lambda Invocation and return a PSR-7 Response.

**Comment by mnapoli** [comment]
I would just argue one last time in favor of splitting functions. With the PSR-11 integration, it becomes really easy to invoke Symfony or Laravel services via Lambda. Here is an example:

```yaml
functions:
    check-license:
        handler: App\CheckLicense
    register-device:
        handler: App\RegisterDevice
```

With a `init.php` file:

```php
<?php

// bootstrap.php here would return the DI container, adjust this with Laravel or Symfony
\Bref\Bref::setContainer(fn() => require __DIR__ . '/config/bootstrap.php');
```

Then in composer.json:

```json
{
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        },
        "files": [
            "init.php"
        ]
    },
}
```

With that solution there is no abstraction or layer to implement.

**Comment by Nyholm** [comment]
I have not seen the PSR11 solution before. I just saw some code related to it and I didn't quite understand it at the time. 

Yeah. This makes more sense. I think this issue can be closed. I'll study up on the docs for this.

Thank you.
