### ISSUE TITLE
Dots in query string are converted to underscores

### ISSUE THREAD

**Issue by ddeboer** [brefphp/bref#786]
I’m using API Platform, where filters on nested fields are denoted using a [dot syntax](https://api-platform.com/docs/core/filters/#filtering-on-nested-properties). Bref converts dots (`.`) in query strings to underscores (`_`), which breaks those API Platform filters.

For instance, a `GET /things?bli.bla=value`:

- works locally, with a `$_SERVER['QUERY_STRING']` of `/things?bli.bla=value`
- but fails on Lambda, where `$_SERVER['QUERY_STRING']` equals `/things?bla_bla=value`.

The culprit is https://github.com/brefphp/bref/blob/master/src/Event/Http/HttpRequestEvent.php#L176, which uses `parse_str()`, for which the [PHP manual documents](https://www.php.net/manual/en/language.variables.external.php):

Dots and spaces in variable names are converted to underscores. For example `<input name="a.b" />` becomes `$_REQUEST["a_b"]`. AWS itself provides the unaltered query string: `rawQueryString` equals `"bli.bla=value"`.

**Comment by mnapoli** [comment]
Thanks for the detailed report.

See #756 and #769

**Comment by ddeboer** [comment]
Good to see this is something already being worked on! Sorry I missed the existing issue & PR.

**Comment by mnapoli** [comment]
No problem!
