### ISSUE TITLE
How to do work after response (websockets)

### ISSUE THREAD

**Issue by stayallive** [brefphp/bref#798]
After seeing the new websockets integration I got excited and went to try it out, it works pretty nice!

However I have a question on how to achieve something (and/or if it's possible).

Consider the following example, I've tried to keep it as small as possible.

```php
class WebsocketServer extends WebsocketHandler
{
    public function handleWebsocket(WebsocketEvent $event, Context $context): HttpResponse
	{
		if ($event->getEventType() === 'CONNECT') {
			// Cannot use SimpleWebsocketClient to send information to socket for $event because connection is not yet accepted

			return new HttpResponse('connect');

			// Want to use the SimpleWebsocketClient but that's not possible ofcourse because if the return
		}

		return new HttpResponse('ok');
	}
}
```

The "problem" is that you cannot send a message to the client before responding to the `CONNECT` event (the actual response content is irrelevant it looks like).

So I would like to be able to send a message to the connected client after the websocket response was sent but I cannot see some `afterResponse` method or some other way to achieve that.

Simple workaround would be to let the client send the first message and respond to that, but unfortunately that is not possible with what I'm building, the "server" needs to send the first event.

This functionality could also be useful for HTTP requests so you can respond immediately to the client but do some cleanup, accounting or API request after response has been sent.

If it's already possible and I missed it please let me know but otherwise consider this a feature request (happy to take a stab at it if there is interest and with a little bit of guidance where to add this).

---

Sidenote, you can use `routeResponseSelectionExpression` to send the response body to the client as a response to a message but that only works for the `$default` (or named) route and not `$connect` (or `$disconnect` but that kinda makes sense) so that is also not a solution unfortunately.

```yaml
    events:
      - websocket: $connect
      - websocket: $disconnect
      - websocket:
          route: $default
          routeResponseSelectionExpression: $default
```

**Comment by mnapoli** [comment]
Hi, I think you would get more help in an AWS-related forum. This is not directly related to Bref.

BTW maybe @danniehansen has an idea.

**Comment by stayallive** [comment]
Hi @mnapoli, thanks for the quick response.

I know AWS could solve this (the example above), but I'm looking for a way to do work after sending a response in Bref and before the Lambda runtime moves on to wait for the next request, that was the gist of what I was trying to "request" / discuss here. I think that could be a thing Bref could provide and be useful for my _example_ use case and for HTTP requests (for example Laravel and Symfony provide similar mechanisms to send a HTTP response and do work after that before the FPM request is finished and the worker is released).

I added the "problems" and trials I had with the websockets integration as a use case example, I'm sorry if it looks like I was asking for you to fix AWS issues / unfinished products 😉 

If you still feel this is not something Bref want to provide feel of course free to close this!

**Comment by mnapoli** [comment]
Ah OK, but it's not possible to run stuff after sending the response. It may be worth looking into how to achieve that in other languages because they will have the same limitation.

**Comment by stayallive** [comment]
Ah, I might have misunderstood the Lambda event loop then...

I was looking at this line: 

https://github.com/brefphp/bref/blob/6ea053f3ec6775f3a923e11a8eafff3754a29a9a/src/Runtime/LambdaRuntime.php#L104

And I thought it could be as "simple" as allowing a callback to be executed after the `sendResponse` call and do some work in that callback, but I realise that I might not understand the runtime correctly and that after `sendResponse` the runtime is immediately killed (I can't find much documentation on it)?

**Comment by mnapoli** [comment]
The way it works for HTTP is that API Gateway does not send the response until Bref asks for the next event, so technically it's impossible.

API Gateway Websockets could work differently, but doing that would be very hacky (if it even works, which is not likely). Which is why I insist on looking at what AWS recommends, or how people do this in other languages.

**Comment by stayallive** [comment]
Ah no, okay that makes it a lot more clear. I understood it as being the other way around and that you had some time between the response and the next event, but that is not the case. In that case it seems like this is impossible and or not feasible at the current state of Lambda's.

Thank you for your quick responses and time!
