### ISSUE TITLE
Runtime `provided` and Bref 1.0

### ISSUE THREAD

**Issue by stayallive** [brefphp/bref#801]
In Bref the default runtime changed to `provided.al2` however on some functions I need to still use the `provided` runtime because other layers are built on that. When using Bref 1.0 and `runtime: provided` it will happily deploy but fails to execute because a Bref PHP layer for `provided.al2` is used which doesn't work on `provided`.

This all makes sense, but I would expect Bref to either error out and tell me I _need_ `provided.al2` or to use a layer compatible with the `runtime` specified in the `serverless.yml`.

It sounded to me from the 1.0 introduction post and docs that the runtime `al2` is optional. Also cannot find any upgrade docs stating that I need to upgrade to `al2` for Bref `1.0`.

For now rolled back to `0.5` which solves the issue, but I wanted to open an issue in case this was an oversight.

**Comment by mnapoli** [comment]
Thanks for the feedback, that's a very good point!

Maybe that wasn't clear enough, so I've pushed da62af8f74a95bf8dc0762f8569f7d2015561e5f to try to make this more explicit.

![image](https://user-images.githubusercontent.com/720328/100455847-b21c0680-30bf-11eb-815f-0e00a3b45833.png)


Let me know if you think we need to improve it further.

**Comment by stayallive** [comment]
Good, I think that at least covers it 😄 

If possible it would be really nice DX if there was an error (or at least a warning) when trying to deploy to `runtime: provided` with Bref `1.0` since it's so easy to change and or use an older template from some blog post that you copy paste.

**Comment by mnapoli** [comment]
Yes that's a good point.

I double checked and the new Bref layers are only compatible with `al2`:

https://github.com/brefphp/bref/blob/73d83948dbb70b8366b13fb21d14d0228d7a3aba/runtime/layers/publish.php#L76-L77

What kind of error did you get? Do you have the full message?

**Comment by stayallive** [comment]
I get an error when invoking the Lambda and so far I've only seen this one:

> /opt/bin/php: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory

Looks like Amazon will allow you to use incompatible layers?

**Comment by reganjohnson** [comment]
> I get an error when invoking the Lambda and so far I've only seen this one:
> 
> > /opt/bin/php: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
> 
> Looks like Amazon will allow you to use incompatible layers?
> 
> Edit: This was on Bref 1.0 with `runtime: provided`, no errors on `serverless deploy`.

I am getting the same error in testing on Bref 1.0 - still debugging.

Using:

```
runtime: provided.al2
```

And these layers:
```
    layers:
      - ${bref:layer.php-74-fpm}
      - ${bref:extra.redis-php-74}
```

**Comment by mnapoli** [comment]
I've added an error when deploying Bref 1.0 with the provided runtime.

Thanks!
