### ISSUE TITLE
Alternative way to perform heavy tasks

### ISSUE THREAD

**Issue by pfazzi** [brefphp/bref#809]
Since the lambda environment is not compatible with `fastcgi_finish_request`, how can I execute heavy tasks easily after the response has been sent?

I tried with something like that, where in shutdown I execute some async tasks, but APIGateway still reaches the timeout limit...
```php
$response = $app->handle($request);

(new Laminas\HttpHandlerRunner\Emitter\SapiEmitter())->emit($response);

$app->shutdown();
```

**Comment by georgeboot** [comment]
Have you considered sending these tasks to a queue (for example, SQS) and processing them asynchronously?
