### ISSUE TITLE
PHP Zlib Extension not woking

### ISSUE THREAD

**Issue by arasu1997** [brefphp/bref#814]
Hi,

I have deployed a simple php application which has default compression enabled.

I'm using `"ini_set('zlib.output_compression', 'On');"` to compress the responses. But I'm receiving "Internal Server Error" as the response.

I tried to manually compress the response by using gzencode() - zlib's function to get the compressed output. Still I'm facing the same issue.
![Screensho
![Screenshot 2020-12-07 at 12 45 32 PM](https://user-images.githubusercontent.com/45655443/101320641-1b530500-388a-11eb-995e-2cb9a8f6f480.png)

**Comment by mnapoli** [comment]
What is the error message in the logs?

**Comment by arasu1997** [comment]
@mnapoli While using gzencode(), I'm getting this :

2946e38f-7a46-43ea-8993-e4cb6f9ea4ee	Invoke Error	
{
    "errorType": "Exception",
    "errorMessage": "The Lambda response cannot be encoded to JSON.\nThis error usually happens when you try to return binary content. If you are writing an HTTP application and you want to return a binary HTTP response (like an image, a PDF, etc.), please read this guide: https://bref.sh/docs/runtimes/http.html#binary-responses\nHere is the original JSON error: 'Malformed UTF-8 characters, possibly incorrectly encoded'",
    "stack": [
        "#0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(187): Bref\\Runtime\\LambdaRuntime->postJson()",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(104): Bref\\Runtime\\LambdaRuntime->sendResponse()",
        "#2 /opt/bootstrap(35): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#3 {main}"
    ]
}

**Comment by mnapoli** [comment]
I guess you have your answer right here then.

**Comment by arasu1997** [comment]
@mnapoli After handling binary-response, I'm getting the response status code as '200'. But the response is not decoded properly. Facing **ERR_CONTENT_DECODING_FAILED** issue in the browser.
![Screenshot 2020-12-07 at 7 02 50 PM](https://user-images.githubusercontent.com/45655443/101356959-d09fb000-38be-11eb-9f16-344e0efd33b3.png)

FYI : Also there is no error logs in CloudWatch. 
- This same code working fine in a Linux machine

**Comment by mnapoli** [comment]
I think PHP's `zlib.output_compression` is not compatible with Lambda and API Gateway.

Have a look at https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html and https://www.serverless.com/plugins/serverless-api-compression if you really want to implement that.
