### ISSUE TITLE
Deprecated use of `ForwardedValues` in "Bref for Web Apps"

### ISSUE THREAD

**Issue by afu-dev** [brefphp/bref#821]
Just discovered when checking the documentation of `ForwardedValues` that this field has been deprecated: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ForwardedValues.html

It's currently used in some place like https://github.com/brefphp/bref/blob/master/docs/websites.md (https://bref.sh/docs/websites.html).

We should be using CachePolicy now (`AWS::CloudFront::CachePolicy`).

**Comment by mnapoli** [comment]
This has been solved when we switched to Lift.
