### ISSUE TITLE
Lambda supporting containers

### ISSUE THREAD

**Issue by akzincsystems** [brefphp/bref#822]
In light of the recent AWS announcement for the support of containers in Lambda (https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/) is there any value in pivoting Bref to this way of working?

**Comment by mnapoli** [comment]
Hi, see https://github.com/brefphp/bref/discussions/817

**Comment by mnapoli** [comment]
(feel free to continue the discussion there)
