### ISSUE TITLE
Symfony Dotenv->bootEnv() error

### ISSUE THREAD

**Issue by eddiejan** [brefphp/bref#826]
Hello all,

Since the new releases I'm encoutering issues with loading the environment variables, specifically with Symfony Dotenv.

By following this guide: https://bref.sh/docs/frameworks/symfony.html
The Lambda gives us the following errors:
![image](https://user-images.githubusercontent.com/65239438/102690087-467f1200-4203-11eb-87ce-2280177cc92a.png)

Not sure why it's looking for the .env file but I assume it has something to do with the recent update on serverless .env file support. https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES

Hope this contributes.

**Comment by shabanbx** [comment]
Same here .env is not read by laravel when deployed using sls deploy

**Comment by mnapoli** [comment]
Thanks, it seems to be caused by https://github.com/serverless/serverless/pull/8634 (a change in serverless). I'll post a comment there.

**Comment by eddiejan** [comment]
If someone else is encountering this problem, you can simply downgrade serverless to 2.15.0 by running the following command:
`npm install -g serverless@2.15.0`

**Comment by 0x346e3730** [comment]
> 
> 
> If someone else is encountering this problem, you can simply downgrade serverless to 2.15.0 by running the following command and your application should be good to go again:
> `npm install -g serverless@2.15.0`

Thank you for the quick workaround !

**Comment by shabanbx** [comment]
put this in your serverless.yml file

package:
  include: ".env*"

https://github.com/serverless/serverless/pull/8648#discussion_r546710547


Thanks to @mnapoli they are discussing the .env file as a need for the framework rather than its need for the lambda itself until then the above should work

**Comment by mnapoli** [comment]
I think https://github.com/serverless/serverless/pull/8648 solves this issue for now (you need to upgrade serverless), should we close this?

**Comment by eddiejan** [comment]
Seems fair right. Maybe update the documentation though?

**Comment by vasilvestre** [comment]
I've kind of fixed it..

bin/console & public/index.php

```diff
- (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
+ if (!isset($_SERVER['LAMBDA_TASK_ROOT'])) (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
```

I used the same thing than what's used for cache configuration in src/Kernel.php

**Comment by mnapoli** [comment]
Closing this issue: `.env` are no longer excluded by default in SF 3.
