### ISSUE TITLE
serveless deploy error

### ISSUE THREAD

**Issue by sankapp** [brefphp/bref#831]
I’m using an ubuntu 16.04 local server in a vagrant box. I use Laravel 8 as my framework. When I use bref.sh to deploy my code to serverless it pops below error

Cannot read file vendor/aws/aws-sdk-php/src/ClientSideMonitoring/Exception/Configurat
ionException.php due to: ENOMEM: not enough memory, open ‘/web/liyanna.com/vendor/aws/a
ws-sdk-php/src/ClientSideMonitoring/Exception/ConfigurationException.php’

what should I do about this error?

**Comment by robmellett** [comment]
More than likely, it's an issue with your vagrant box and a memory related setting.

If you are trying to deploy your application, you should look into github actions.  There's a working example in the demo repository below.

https://github.com/brefphp/examples

**Comment by mnapoli** [comment]
> ENOMEM: not enough memory

Your deployment in the vagrant box seems to hit a memory limit. Try to give more memory to your vagrant box?

In any case, it doesn't seem to be related to Bref itself.

**Comment by sankapp** [comment]
I gave 4GB for vagrant box still the same problem occurs. how much memory needs to serverless deploy?

**Comment by gumiranmarcon** [comment]
I encounter an error when using the "serverless deploy" command

![image](https://user-images.githubusercontent.com/16933061/117108855-5f552200-adb6-11eb-8b2b-c0926d139e11.png)

I'm using Ubuntu 18.04.5 LTS  (16gb Memory) and Laravel Framework 7.0 but after I deleted the vendor folder the command works,  for reference [https://forum.serverless.com/t/not-enough-memory-node-error-when-trying-to-deploy/4938](https://forum.serverless.com/t/not-enough-memory-node-error-when-trying-to-deploy/4938) . 

Here's my environment info : 
![image](https://user-images.githubusercontent.com/16933061/117108704-274ddf00-adb6-11eb-8bcc-c1d7e8276f4f.png)

How can I fix this?

**Comment by mnapoli** [comment]
Please open a discussion in the support forum: https://github.com/brefphp/bref/discussions/categories/support
