### ISSUE TITLE
Build without Serverless (Terraform support)

### ISSUE THREAD

**Issue by soukicz** [brefphp/bref#844]
Bref currently supports installation with Serverless which is really easy to start with but not really compatible with enterprise environment. Any documentation that start with "create admin access to whole account and give it to this binary" is a no go.

Could you please provide same instructions how to build Bref project without Serverless? I could prepare some basic example of Terraform code for documentation but I didn't figure out how to actually build Bref project (get deployment package) manually.

Thank you

**Comment by soukicz** [comment]
It seems it is all a lot less complicated than I thought. That build instructions I was looking for is "just make ZIP" :))

Thank you for your help.

**Comment by Utwo** [comment]
For anyone looking for an example, I created this repo that tries to replicate in Terraform, everything that is created in serverless framework. 

https://github.com/Utwo/brefsh-terraform
