### ISSUE TITLE
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by kirrg001** [brefphp/bref#860]
**Description:**

I am executing a remote command via bref on my lamdba. It always worked, but suddenly stopped with this error message. 

**How to reproduce:**

Not really sure. 

vendor/bin/bref cli --verbose --region eu-central-1 staging-console -- my-command

```
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
```

"bref/bref": "^0.5.20"

Thanks so much :)

**Comment by deleugpn** [comment]
That's just a warning that doesn't stop the execution flow and is highly likely not related to the issue you're having. Maybe look further to see what other error message you might have?

**Comment by kirrg001** [comment]
Oh yeah you are right. Thanks!

**Comment by mnapoli** [comment]
FYI that extension is loaded by default now, you can remove the line in your `php.ini`.

**Comment by basemEk** [comment]
specify more please @mnapoli. How to remove the line in php.ini?

**Comment by mnapoli** [comment]
If you have a `php.ini` file in your project, open it and remove the line.

If you don't have a `php.ini` file, then there is nothing to do.
