### ISSUE TITLE
AWS X-Ray support

### ISSUE THREAD

**Issue by soukicz** [brefphp/bref#882]
Is there some best-practice how to use XRay with Bref? I have found that there is trace id in Context but no mention how to use it. I have tried to use https://github.com/patrickkerrigan/php-xray which was simple to integrate but doesn't seem to be working with Lambda/Bref. I am already using this package on ECS and it works as expected.

It looks like tracing data is created correctly and submitted to XRay daemon but I can see only basic trace data in XRay console. I am guessing that there is some Lambda magic and tracing must be submitted differently than on ECS.

Thank you for any help..

Sample code:
```php
        [$host, $port] = explode(':', $_ENV['AWS_XRAY_DAEMON_ADDRESS']);

        Trace::getInstance()
            ->setTraceHeader($context->getTraceId())
            ->setName('test')
            ->setUrl('https://example.org')
            ->begin(100); // trace all requests

        $segment = new \Pkerrigan\Xray\HttpSegment();
        $segment
            ->setUrl('https://google.com')
            ->setMethod('GET')
            ->setResponseCode(200)
            ->begin();
        sleep(1);
        $segment->end();

        Trace::getInstance()
            ->addSubsegment($segment)
            ->end()
            ->setResponseCode(200)
            ->submit(new DaemonSegmentSubmitter($host, (int) $port));
```

**Comment by soukicz** [comment]
@deleugpn 
> In case you're looking for a bit of inspiration, I have written a prototype here https://github.com/cgauge/php-x-ray-instrumentation/


Does it work on Lambda (reporting subsegments etc)? Do you remember what issues you had to solve to make it work on Lambda?

It would be great if I could make package patrickkerrigan/php-xray work on Lambda because it already has tests etc. and is already running in high traffic production. But I don't see on first look what is done differently.

Your code pointed me to one possible issue but that didn't solve it :(

```diff
- Trace::getInstance()->setTraceHeader($context->getTraceId())
+ Trace::getInstance()->setTraceHeader($_ENV['_X_AMZN_TRACE_ID'] ?? null)
```

**Comment by soukicz** [comment]
My best guess is that I should be sending some subsegment and XRay will patch it together but I cannot get it working.

Next step would be to implement it in Bref handler to trace exceptions but so far I am stuck in first step :))

**Comment by soukicz** [comment]
Okay, I have figured out and it is stupid.... "name" is required in segment. Even when XRay doesn't display it... Thanky for rubber ducking with me a and here is working code:

```php
        [$host, $port] = explode(':', $_ENV['AWS_XRAY_DAEMON_ADDRESS']);

        Trace::getInstance()
            ->setTraceHeader($context->getTraceId())
            ->setName('test')
            ->setUrl('https://example.org')
            ->begin(100); // trace all requests

        $segment = new \Pkerrigan\Xray\HttpSegment();
        $segment
            ->setUrl('https://google.com')
            ->setName('Google')
            ->setMethod('GET')
            ->setResponseCode(200)
            ->begin();
        sleep(1);
        $segment->end();

        Trace::getInstance()
            ->addSubsegment($segment)
            ->end()
            ->setResponseCode(200)
            ->submit(new DaemonSegmentSubmitter($host, (int) $port));
```

**Comment by mnapoli** [comment]
Thank you for sharing the working code!
