### ISSUE TITLE
Make runtimes fails when trying to download packages

### ISSUE THREAD

**Issue by danielclariondoor** [brefphp/bref#885]
**Description:**

Building the runtimes fails with 
`#36 0.365 gzip: stdin: unexpected end of file
#36 0.366 tar: Child returned status 1
#36 0.366 tar: Error is not recoverable: exiting now
`
This happens when trying to download and install libzip, but when I comment the entire section out, it just happens on another package.
It's this exact error: https://twitter.com/matthieunapoli/status/1249699408490442752
I discovered it while building a custom runtime, but it also happens with the repo download fresh and no modifications.
Running the same command locally works without issue.

**How to reproduce:**
Clone repo
`make runtimes`

Latest Bref but also previous version
layer php 73

**Comment by Nyholm** [comment]
This was fixed in https://github.com/brefphp/bref/pull/886. 

Could you confirm?

**Comment by danielclariondoor** [comment]
It works! Thanks!
