### ISSUE TITLE
Laravel set on Rest ApiGateway Resource instead of root don't work properly

### ISSUE THREAD

**Issue by carlosfanti** [brefphp/bref#952]
**Description:**

When installed Laravel at the root of a apiGateway everthing works great, but when I tried to put the Laravel on a resource path, the lambda returns a 404 page. Investigating a little, it seems that the path where is located the lambda is passing on request to the integration and not on Laravel root / at expected.

**How to reproduce:**

Example web function definition
```functions:
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-80-fpm}
    events:
      - http:
          path: laravel-lambda/
          method: ANY
      - http:
          path: laravel-lambda/{proxy+}
          method: ANY
```
    
then on Laravel, since I getting 404, I setted a fallback route on **routes/web.php** to return some information of the request:
```
Route::fallback(function (Request $request) {
    return [
        'path' => $request->path(),
        'method' => $request->method(),
        'header' => $request->header(),
        'all' => $request->all(),
    ];
});
```

And then tested
<img width="781" alt="Captura de pantalla 2021-06-10 a las 8 33 54" src="https://user-images.githubusercontent.com/8270067/121476477-038a4400-c9c7-11eb-94f7-166a7f89f93f.png">

A workaround was to add a prefix on Laravel routes, making changes on **app/Providers/RouteServiceProvider.php**
```
$this->routes(function () {
            Route::prefix('laravel-lambda')
                ->group(function() {
                    Route::prefix('api')
                        ->middleware('api')
                        ->namespace($this->namespace)
                        ->group(base_path('routes/api.php'));
        
                    Route::middleware('web')
                        ->namespace($this->namespace)
                        ->group(base_path('routes/web.php'));
                });
        });
```

But if that is a way to don't have to make this prefixing on Laravel, it will be great!

Thanks, and sorry about my english 😄

**Comment by mnapoli** [comment]
Hi, could you explain more precisely:

- what you expected should happen
- what happened instead?

That way we can compare and understand a bit better the problem. Thanks!

**Comment by carlosfanti** [comment]
Hi @mnapoli, thanks for asking.

I'm trying to put more than one Laravel project in the same ApiGateway, each laravel in its specific path:

```
ApiGateway:
   laravel-A/
        ANY /
        ANY /{proxy+}
   laravel-B/
        ANY /
        ANY /{proxy+}
   ...
```

When accessing the route `GET /laravel-A`, I expect the welcome view from laravel, instead I'm getting a 404 since laravel is receiving a request for `GET /laravel-A` instead `GET /`

**Comment by mnapoli** [comment]
Yes, the URL is `/laravel-A` so Laravel is trying to find a route for that URL.

Maybe write a route for that URL? This isn't really related to API Gateway here I think: you are trying to run Laravel in a subfolder (in the URL) but you didn't change anything in Laravel, so Laravel is confused.

**Comment by carlosfanti** [comment]
Hi, yes I can see now. So the workaround on **app/Providers/RouteServiceProvider.php** is in my case necessary.

Thank you very much for the help, and nice job with this project 😄
