### ISSUE TITLE
change the output stuck of "bref console commands" failure response to a more meaningful error description, it could be the CloudWatch error stack  

### ISSUE THREAD

**Issue by Houssem-Esprit** [brefphp/bref#969]
### Discussed in https://github.com/brefphp/bref/discussions/968

<div type='discussions-op-text'>

<sup>Originally posted by **Houssem-Esprit** July 10, 2021</sup>

So, I'm about to create a serverless api platform with aws lambda using bref. it goas well with the deployment on lambda and connection to MariaDB RDS, then when I jumped to the database operations within my serverless api platform using [bref console commands](https://bref.sh/docs/runtimes/console.html) I kept stuck with the same error `Fatal error: Uncaught TypeError: base64_decode() expects parameter 1 to be string, null given`, the command I used it is `vendor/bin/bref --region=eu-west-1 --profile=default cli symfony-prod-console -- doctrine:database:create`. I did try a bunch of combinations with [options] and without, environment variables, and still can't figure out why this problem came in front.

---------
>Running command: $ vendor/bin/bref --region=eu-west-1 --profile=default cli symfony-prod-console -- doctrine:database:create -vvv  
stack trace : 
`
Fatal error: Uncaught TypeError: base64_decode() expects parameter 1 to be string, null given in C:\Users\HP\Desktop\2020\Confledis\Projects\Nx_Demo\api\backend-module-federation\vendor\bref\bref\src\Lambda\InvocationResult.php:29
Stack trace:
#0 C:\Users\HP\Desktop\2020\Confledis\Projects\Nx_Demo\api\backend-module-federation\vendor\bref\bref\src\Lambda\InvocationResult.php(29): base64_decode(NULL)
#1 C:\Users\HP\Desktop\2020\Confledis\Projects\Nx_Demo\api\backend-module-federation\vendor\bref\bref\src\Lambda\InvocationFailed.php(20): Bref\Lambda\InvocationResult->getLogs()
#2 C:\Users\HP\Desktop\2020\Confledis\Projects\Nx_Demo\api\backend-module-federation\vendor\bin\bref(21) : eval()'d code(109): Bref\Lambda\InvocationFailed->getInvocationLogs()
#3 [internal function]: Silly\Application->{closure}('symfony-prod-co...', 'eu-west-1', 'default', Array, Object(Symfony\Component\Console\Style\SymfonyStyle))
#4 C:\Users\HP\Desktop\2020\Confledis\Projects\Nx_Demo\api\backend-module-federation\vendor\php-di\invoker\src\Invoker in C:\Users\HP\Desktop\2020\Confledis\Projects\Nx_Demo\api\backend-module-federation\vendor\bref\bref\src\Lambda\InvocationResult.php on line 29
` 
---------
 I'm using : 
- PHP 7.3
- Symfony 5.3
- Api Platform 2.6
-  bref 1.2.8
- symfony-bridge : 0.1.2
- Windows 7

can anybody tell me what I'm missing here, or if by any chance this is a problem with bref console commands? </div>

**Comment by mnapoli** [comment]
Duplicate per https://github.com/brefphp/bref/discussions/968#discussioncomment-994603
