### ISSUE TITLE
Support for serverless-offline

### ISSUE THREAD

**Issue by chrisnharvey** [brefphp/bref#977]
Hey there,

I've been trying to get Bref running locally with the `serverless-offline` package, but I keep running into the following error:

```json
{"errorType":"exitError","errorMessage":"RequestId: a0bf7177-cfb5-162f-4620-e5bbc15c07cc Error: fork/exec /opt/bootstrap: exec format error"}
```

Has anyone successfully ran Bref locally using `serverless-offline`? I've noticed some old issues that seemed to try to support it, but they seem a little out of date now.

Could be so cool if `serverless-offline` was supported.

**Comment by mnapoli** [comment]
Hi, check out:

- https://bref.sh/docs/web-apps/local-development.html
- https://bref.sh/docs/function/local-development.html

`serverless-offline` is not supported but it shouldn't be a problem thanks to the solutions above. If not let me know.

**Comment by chrisnharvey** [comment]
@mnapoli Sorry for dragging up this thread, but there are some limitations of the provided solutions, the main one being event-driven apps using API Gateway for routing. Its extremely difficult to test apps built this way locally since for event driven stuff, we only have the CLI command to run our handlers.

serverless-offline simulates API Gateway quite nicely and makes testing applications like this super easy.

I was able to get Bref working using serverless-offline, but only with some hacks. I had to flatten all of the symlinks in the Bref Lambda layer for it to work correctly.

**Comment by mnapoli** [comment]
Hey @chrisnharvey, would https://github.com/brefphp/dev-server help here?

**Comment by chrisnharvey** [comment]
Thanks! Didn't even know that existed :laughing: 

I'll give it a try and report back. Looks like this is exactly what I need though :smile:

**Comment by mnapoli** [comment]
I know it's a bit experimental 😅 let me know if that works fine for you
